In [25]:
# ============================================================
# Stage0 Launch Pad - Starter Program for Any Dataset
# Purpose:
# 1. Ask user for drive, folder name, and dataset name
# 2. Verify dataset path
# 3. Create stage0-launch-pad folder
# 4. Create notepad/text purpose file
# 5. Read dataset safely
# 6. Print columns, rows, and columns count
# 7. Allow user to run layers one by one
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime

# ------------------------------------------------------------
# Step 1: User Inputs
# ------------------------------------------------------------

drive = input("Enter your drive, e.g., C:, D:, E: : ").strip()
folder_name = input("Enter folder name/path after drive, e.g., Med_data : ").strip()
dataset_name = input("Enter dataset file name, e.g., healthcare_dataset.csv : ").strip()

# Build paths
base_path = os.path.join(drive + "\\", folder_name)
dataset_path = os.path.join(base_path, dataset_name)
stage0_path = os.path.join(base_path, "stage0-launch-pad")

# Create stage0 folder
os.makedirs(stage0_path, exist_ok=True)

print("\nBase Folder:", base_path)
print("Dataset Path:", dataset_path)
print("Stage0 Folder:", stage0_path)


# ------------------------------------------------------------
# Step 2: Create Notepad / Purpose File
# ------------------------------------------------------------

purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")
path_file = os.path.join(stage0_path, "selected_dataset_path.txt")

purpose_text = f"""
STAGE0 LAUNCH PAD PURPOSE FILE

Created On:
{datetime.now()}

Dataset Folder:
{base_path}

Dataset File:
{dataset_name}

Full Dataset Path:
{dataset_path}

Purpose:
This Stage0 Launch Pad prepares the dataset folder for future ML/AI work.
It verifies the dataset, checks structure, records metadata, and creates a base
for layer-by-layer dataset understanding before machine learning starts.

Next Stage Instruction:
The next ML/AI stage must read this file first before designing ML problem definitions.

Important Rule:
Raw dataset must not be modified directly.
All cleaned, enriched, or generated files should be stored inside stage0-launch-pad.

"""

with open(purpose_file, "w", encoding="utf-8") as f:
    f.write(purpose_text)

with open(path_file, "w", encoding="utf-8") as f:
    f.write(dataset_path)

print("\nPurpose file created:")
print(purpose_file)


# ------------------------------------------------------------
# Step 3: Dataset Verification and Safe Reading
# ------------------------------------------------------------

def read_dataset_safely(file_path):
    """
    Reads CSV or Excel dataset using common encodings.
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Dataset not found: {file_path}")

    ext = os.path.splitext(file_path)[1].lower()

    if ext == ".csv":
        encodings = ["utf-8", "utf-8-sig", "cp1252", "latin1"]
        last_error = None

        for enc in encodings:
            try:
                df = pd.read_csv(file_path, encoding=enc)
                print(f"\nDataset successfully read using encoding: {enc}")
                return df
            except Exception as e:
                last_error = e

        raise Exception(f"Could not read CSV file. Last error: {last_error}")

    elif ext in [".xlsx", ".xls"]:
        df = pd.read_excel(file_path)
        print("\nExcel dataset successfully read.")
        return df

    else:
        raise ValueError("Unsupported file type. Use CSV, XLSX, or XLS.")


df = read_dataset_safely(dataset_path)

print("\nDataset Verified Successfully.")
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nColumn Names:")
for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")


# ------------------------------------------------------------
# Step 4: Save Basic Dataset Verification Report
# ------------------------------------------------------------

verification_report = os.path.join(stage0_path, "dataset_basic_verification_report.txt")

with open(verification_report, "w", encoding="utf-8") as f:
    f.write("DATASET BASIC VERIFICATION REPORT\n")
    f.write("=" * 50 + "\n\n")
    f.write(f"Created On: {datetime.now()}\n")
    f.write(f"Dataset Path: {dataset_path}\n\n")
    f.write(f"Number of Rows: {df.shape[0]}\n")
    f.write(f"Number of Columns: {df.shape[1]}\n\n")
    f.write("Column Names:\n")
    for i, col in enumerate(df.columns, start=1):
        f.write(f"{i}. {col}\n")

print("\nBasic verification report saved:")
print(verification_report)


# ============================================================
# Layer-by-Layer Execution Functions
# ============================================================

# ------------------------------------------------------------
# Layer 0: Control and Purpose Layer
# ------------------------------------------------------------

def run_layer_0_control():
    layer_path = os.path.join(stage0_path, "00_control_and_purpose")
    os.makedirs(layer_path, exist_ok=True)

    report = os.path.join(layer_path, "layer0_control_summary.txt")

    text = f"""
LAYER 0: CONTROL AND PURPOSE SUMMARY

Dataset:
{dataset_name}

Dataset Path:
{dataset_path}

Rows:
{df.shape[0]}

Columns:
{df.shape[1]}

Purpose:
This layer confirms the dataset identity and creates the control base for next stages.

Next Action:
Run Layer 1 for raw file rescue and encoding checks.
"""

    with open(report, "w", encoding="utf-8") as f:
        f.write(text)

    print("Layer 0 completed:", report)


# ------------------------------------------------------------
# Layer 1: Raw File Rescue Layer
# ------------------------------------------------------------

def run_layer_1_raw_file_rescue():
    layer_path = os.path.join(stage0_path, "01_raw_file_rescue")
    os.makedirs(layer_path, exist_ok=True)

    report = os.path.join(layer_path, "raw_file_rescue_report.txt")

    empty_lines = 0
    total_lines = 0

    try:
        with open(dataset_path, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                total_lines += 1
                if line.strip() == "":
                    empty_lines += 1
    except Exception as e:
        total_lines = "Could not count lines"
        empty_lines = "Could not count empty lines"

    text = f"""
LAYER 1: RAW FILE RESCUE REPORT

Dataset Path:
{dataset_path}

Total Lines:
{total_lines}

Empty Lines:
{empty_lines}

Checks Included:
- File existence
- Encoding fallback during reading
- Empty line detection
- Basic raw file inspection

Next Action:
Run Layer 2 for dataset structure analysis.
"""

    with open(report, "w", encoding="utf-8") as f:
        f.write(text)

    print("Layer 1 completed:", report)


# ------------------------------------------------------------
# Layer 2: Dataset Structure Layer
# ------------------------------------------------------------

def run_layer_2_dataset_structure():
    layer_path = os.path.join(stage0_path, "02_dataset_structure")
    os.makedirs(layer_path, exist_ok=True)

    report = os.path.join(layer_path, "dataset_structure_report.txt")
    columns_csv = os.path.join(layer_path, "column_list.csv")

    column_info = pd.DataFrame({
        "column_name": df.columns,
        "dtype": [str(df[col].dtype) for col in df.columns],
        "non_null_count": [df[col].notna().sum() for col in df.columns],
        "null_count": [df[col].isna().sum() for col in df.columns],
        "unique_values": [df[col].nunique(dropna=True) for col in df.columns]
    })

    column_info.to_csv(columns_csv, index=False)

    text = f"""
LAYER 2: DATASET STRUCTURE REPORT

Rows:
{df.shape[0]}

Columns:
{df.shape[1]}

Duplicate Column Names:
{df.columns.duplicated().sum()}

Column detail saved in:
{columns_csv}

Next Action:
Run Layer 3 for missing values, empty rows, null columns, and quality checks.
"""

    with open(report, "w", encoding="utf-8") as f:
        f.write(text)

    print("Layer 2 completed:", report)
    display(column_info)


# ------------------------------------------------------------
# Layer 3: Data Quality Layer
# ------------------------------------------------------------

def run_layer_3_data_quality():
    layer_path = os.path.join(stage0_path, "03_data_quality")
    os.makedirs(layer_path, exist_ok=True)

    report = os.path.join(layer_path, "data_quality_report.txt")
    missing_csv = os.path.join(layer_path, "missing_values_report.csv")

    missing_report = pd.DataFrame({
        "column_name": df.columns,
        "missing_count": df.isna().sum().values,
        "missing_percentage": (df.isna().sum().values / len(df)) * 100,
        "unique_values": [df[col].nunique(dropna=True) for col in df.columns]
    })

    missing_report.to_csv(missing_csv, index=False)

    empty_rows = df.isna().all(axis=1).sum()
    duplicate_rows = df.duplicated().sum()
    fully_null_columns = df.columns[df.isna().all()].tolist()

    text = f"""
LAYER 3: DATA QUALITY REPORT

Rows:
{df.shape[0]}

Columns:
{df.shape[1]}

Empty Rows:
{empty_rows}

Duplicate Rows:
{duplicate_rows}

Fully Null Columns:
{fully_null_columns}

Missing value report saved in:
{missing_csv}

Next Action:
Run Layer 4 for column semantics and target suggestions.
"""

    with open(report, "w", encoding="utf-8") as f:
        f.write(text)

    print("Layer 3 completed:", report)
    display(missing_report)


# ------------------------------------------------------------
# Layer 4: Column Semantics Layer
# ------------------------------------------------------------

def run_layer_4_column_semantics():
    layer_path = os.path.join(stage0_path, "04_column_semantics")
    os.makedirs(layer_path, exist_ok=True)

    report = os.path.join(layer_path, "column_semantics_report.txt")
    semantics_csv = os.path.join(layer_path, "column_semantics_guess.csv")

    semantic_rows = []

    for col in df.columns:
        col_lower = col.lower()
        unique_count = df[col].nunique(dropna=True)
        dtype = str(df[col].dtype)

        role = "General Feature"

        if "id" in col_lower:
            role = "Possible Identifier"
        elif unique_count <= 2:
            role = "Possible Binary Feature"
        elif df[col].dtype == "object" and unique_count < 30:
            role = "Possible Categorical Feature"
        elif df[col].dtype == "object" and unique_count >= 30:
            role = "Possible Text or High-Cardinality Feature"
        elif "date" in col_lower or "time" in col_lower:
            role = "Possible Date/Time Feature"
        elif pd.api.types.is_numeric_dtype(df[col]):
            role = "Possible Numeric Feature"

        semantic_rows.append({
            "column_name": col,
            "dtype": dtype,
            "unique_values": unique_count,
            "suggested_role": role
        })

    semantics_df = pd.DataFrame(semantic_rows)
    semantics_df.to_csv(semantics_csv, index=False)

    text = f"""
LAYER 4: COLUMN SEMANTICS REPORT

This layer guesses possible column roles.

Important:
These are automatic guesses only.
Domain expert/user confirmation is required before ML.

Column semantics saved in:
{semantics_csv}

Next Action:
Run Layer 5 for statistical profiling.
"""

    with open(report, "w", encoding="utf-8") as f:
        f.write(text)

    print("Layer 4 completed:", report)
    display(semantics_df)


# ------------------------------------------------------------
# Layer 5: Statistical Profile Layer
# ------------------------------------------------------------

def run_layer_5_statistics():
    layer_path = os.path.join(stage0_path, "05_statistics")
    os.makedirs(layer_path, exist_ok=True)

    report = os.path.join(layer_path, "statistics_summary.txt")
    numeric_csv = os.path.join(layer_path, "numeric_statistics.csv")
    categorical_csv = os.path.join(layer_path, "categorical_statistics.csv")

    numeric_df = df.select_dtypes(include=["number"])
    categorical_df = df.select_dtypes(include=["object", "category"])

    if not numeric_df.empty:
        numeric_df.describe().T.to_csv(numeric_csv)

    categorical_summary = []

    for col in categorical_df.columns:
        categorical_summary.append({
            "column_name": col,
            "unique_values": categorical_df[col].nunique(dropna=True),
            "top_value": categorical_df[col].mode(dropna=True).iloc[0] if not categorical_df[col].mode(dropna=True).empty else None
        })

    categorical_summary_df = pd.DataFrame(categorical_summary)
    categorical_summary_df.to_csv(categorical_csv, index=False)

    text = f"""
LAYER 5: STATISTICAL PROFILE REPORT

Numeric Columns:
{len(numeric_df.columns)}

Categorical/Text Columns:
{len(categorical_df.columns)}

Numeric statistics saved in:
{numeric_csv}

Categorical statistics saved in:
{categorical_csv}

Next Action:
Run Layer 6 for metadata generation.
"""

    with open(report, "w", encoding="utf-8") as f:
        f.write(text)

    print("Layer 5 completed:", report)


# ------------------------------------------------------------
# Layer 6: Metadata Generator Layer
# ------------------------------------------------------------

def run_layer_6_metadata():
    layer_path = os.path.join(stage0_path, "06_metadata")
    os.makedirs(layer_path, exist_ok=True)

    metadata_json = os.path.join(layer_path, "dataset_metadata.json")
    metadata_txt = os.path.join(layer_path, "metadata_questions_for_user.txt")

    metadata = {
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "created_on": str(datetime.now()),
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "column_names": list(df.columns),
        "metadata_status": "auto-generated draft; user confirmation required"
    }

    with open(metadata_json, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=4)

    questions = """
METADATA QUESTIONS FOR USER

1. What does each row represent?
2. What does each column mean?
3. Which column is the target column for ML?
4. Is the dataset real, synthetic, sampled, or modified?
5. Are there any privacy restrictions?
6. Are there any sensitive columns?
7. What is the intended ML/AI use?
8. What should not be done with this dataset?
9. Are there known errors or biases?
10. Who created or collected the dataset?
"""

    with open(metadata_txt, "w", encoding="utf-8") as f:
        f.write(questions)

    print("Layer 6 completed:", metadata_json)


# ------------------------------------------------------------
# Layer 7: Next Stage Prompt Generator
# ------------------------------------------------------------

def run_layer_7_next_stage_prompt():
    layer_path = os.path.join(stage0_path, "07_next_stage_prompt")
    os.makedirs(layer_path, exist_ok=True)

    prompt_file = os.path.join(layer_path, "next_prompt_for_ml_problem_definition.txt")

    prompt = f"""
NEXT PROMPT FOR ML/AI STAGE

You are now working after Stage0 Launch Pad.

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Rows:
{df.shape[0]}

Columns:
{df.shape[1]}

Column Names:
{list(df.columns)}

Task:
Read all Stage0 reports first.
Then design possible ML problem definitions.

You must check:
1. Possible target columns
2. Classification possibilities
3. Regression possibilities
4. Clustering possibilities
5. Required cleaning before ML
6. Required metadata confirmation
7. Possible feature engineering
8. Possible research questions
9. Limitations of the dataset
10. Recommended next ML workflow

Important:
Do not start model training until target column, leakage risk, and data quality issues are reviewed.
"""

    with open(prompt_file, "w", encoding="utf-8") as f:
        f.write(prompt)

    print("Layer 7 completed:", prompt_file)


# ============================================================
# Manual Execution Menu
# ============================================================

print("""
Available Layer Commands:

run_layer_0_control()
run_layer_1_raw_file_rescue()
run_layer_2_dataset_structure()
run_layer_3_data_quality()
run_layer_4_column_semantics()
run_layer_5_statistics()
run_layer_6_metadata()
run_layer_7_next_stage_prompt()

Run them one by one in Jupyter.
""")

Enter your drive, e.g., C:, D:, E: :  d:
Enter folder name/path after drive, e.g., Med_data :  Med_data
Enter dataset file name, e.g., healthcare_dataset.csv :  dataset.csv

Base Folder: d:\Med_data
Dataset Path: d:\Med_data\dataset.csv
Stage0 Folder: d:\Med_data\stage0-launch-pad

Purpose file created:
d:\Med_data\stage0-launch-pad\What_is_my_purpose_for_next_stage.txt

Dataset successfully read using encoding: utf-8

Dataset Verified Successfully.
Number of Rows: 55500
Number of Columns: 15

Column Names:
1. Name
2. Age
3. Gender
4. Blood Type
5. Medical Condition
6. Date of Admission
7. Doctor
8. Hospital
9. Insurance Provider
10. Billing Amount
11. Room Number
12. Admission Type
13. Discharge Date
14. Medication
15. Test Results

Basic verification report saved:
d:\Med_data\stage0-launch-pad\dataset_basic_verification_report.txt

Available Layer Commands:

run_layer_0_control()
run_layer_1_raw_file_rescue()
run_layer_2_dataset_structure()
run_layer_3_data_quality()
run_layer_4_column_semantics()
run_layer_5_statistics()
run_layer_6_metadata()
run_layer_7_next_stage_prompt()

Run them one by one in Jupyter.

In [27]:
# ============================================================
# LAYER 0: CONTROL AND PURPOSE
# Run this after dataset is loaded into df
# Required variables:
# df, dataset_name, dataset_path, base_path, stage0_path
# ============================================================

import os
import json
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, ElementTree


def run_layer_0_control():
    # --------------------------------------------------------
    # Create Layer 0 folder
    # --------------------------------------------------------
    layer_path = os.path.join(stage0_path, "00_control_and_purpose")
    os.makedirs(layer_path, exist_ok=True)

    # --------------------------------------------------------
    # Output file paths
    # --------------------------------------------------------
    report_txt = os.path.join(layer_path, "layer0_control_summary.txt")
    contract_json = os.path.join(layer_path, "stage0_control_contract.json")
    contract_xml = os.path.join(layer_path, "stage0_control_contract.xml")
    readme_txt = os.path.join(layer_path, "next_stage_read_me_first.txt")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    # --------------------------------------------------------
    # Control contract dictionary
    # --------------------------------------------------------
    contract = {
        "stage": "Layer 0 - Control and Purpose",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "base_path": base_path,
        "stage0_path": stage0_path,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "column_names": list(df.columns),
        "purpose": "Create a controlled Stage0 base before ML/AI work starts.",
        "important_rules": [
            "Do not modify the raw dataset directly.",
            "All generated files must stay inside stage0-launch-pad.",
            "The next ML/AI stage must read What_is_my_purpose_for_next_stage.txt first.",
            "Separate detected facts from recommendations.",
            "User/domain expert must confirm target column, metadata, and sensitive fields."
        ],
        "next_action": "Run Layer 1 - Raw File Rescue"
    }

    # --------------------------------------------------------
    # Save JSON contract
    # --------------------------------------------------------
    with open(contract_json, "w", encoding="utf-8") as f:
        json.dump(contract, f, indent=4, ensure_ascii=False)

    # --------------------------------------------------------
    # Save XML contract
    # --------------------------------------------------------
    root = Element("stage0_control_contract")

    for key, value in contract.items():
        node = SubElement(root, key)

        if isinstance(value, list):
            for item in value:
                item_node = SubElement(node, "item")
                item_node.text = str(item)
        else:
            node.text = str(value)

    tree = ElementTree(root)
    tree.write(contract_xml, encoding="utf-8", xml_declaration=True)

    # --------------------------------------------------------
    # Main summary text
    # --------------------------------------------------------
    summary_text = f"""
LAYER 0: CONTROL AND PURPOSE SUMMARY
==================================================

Created On:
{datetime.now()}

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Base Folder:
{base_path}

Stage0 Folder:
{stage0_path}

Number of Rows:
{df.shape[0]}

Number of Columns:
{df.shape[1]}

Purpose:
This layer creates the control and purpose base for the Stage0 Launch Pad.

This Stage0 Launch Pad will prepare the dataset folder for future ML/AI work by:
1. Recording dataset identity
2. Creating a control contract
3. Creating a next-stage instruction file
4. Protecting the raw dataset from direct modification
5. Guiding the next layer-by-layer analysis

Important Rules:
1. Do not modify the raw dataset directly.
2. Store all generated files inside stage0-launch-pad.
3. The next ML/AI stage must read What_is_my_purpose_for_next_stage.txt first.
4. User/domain expert must confirm target column, metadata, and sensitive fields.
5. Stage0 reports are guidance, not final business or medical truth.

Next Action:
Run Layer 1 - Raw File Rescue.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(summary_text)

    # --------------------------------------------------------
    # Read-me file for next stage
    # --------------------------------------------------------
    readme_text = f"""
READ ME FIRST FOR NEXT STAGE
==================================================

Before starting ML/AI work, read Stage0 reports.

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Rows:
{df.shape[0]}

Columns:
{df.shape[1]}

Minimum files to read:
1. What_is_my_purpose_for_next_stage.txt
2. stage0_control_contract.json
3. layer0_control_summary.txt

Warning:
Do not start model training until target column, missing values,
sensitive fields, leakage risk, and metadata questions are reviewed.
"""

    with open(readme_txt, "w", encoding="utf-8") as f:
        f.write(readme_text)

    # --------------------------------------------------------
    # Root purpose file
    # --------------------------------------------------------
    purpose_text = f"""
WHAT IS MY PURPOSE FOR NEXT STAGE
==================================================

This file is created by Layer 0 of Stage0 Launch Pad.

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Rows:
{df.shape[0]}

Columns:
{df.shape[1]}

Purpose:
The next ML/AI stage must read this file first.
Its job is to understand the dataset before designing ML problem definitions.

Current Stage:
Layer 0 has created the control and purpose base.

Next Required Stage:
Layer 1 should inspect raw file issues such as encoding, broken rows,
empty lines, null bytes, and file-level problems.

Important:
Raw data must remain unchanged.
All analysis, cleaning candidates, metadata, and recommendations must be stored
inside the stage0-launch-pad folder.
"""

    with open(root_purpose_file, "w", encoding="utf-8") as f:
        f.write(purpose_text)

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------
    print("Layer 0 completed successfully.")
    print("Files created:")
    print(report_txt)
    print(contract_json)
    print(contract_xml)
    print(readme_txt)
    print(root_purpose_file)


# Run Layer 0
run_layer_0_control()

Layer 0 completed successfully.
Files created:
d:\Med_data\stage0-launch-pad\00_control_and_purpose\layer0_control_summary.txt
d:\Med_data\stage0-launch-pad\00_control_and_purpose\stage0_control_contract.json
d:\Med_data\stage0-launch-pad\00_control_and_purpose\stage0_control_contract.xml
d:\Med_data\stage0-launch-pad\00_control_and_purpose\next_stage_read_me_first.txt
d:\Med_data\stage0-launch-pad\What_is_my_purpose_for_next_stage.txt

In [29]:
# ============================================================
# LAYER 1: RAW FILE RESCUE
# Run after Layer 0
# Required variables:
# dataset_path, stage0_path
# Optional variables:
# dataset_name, base_path, df
# ============================================================

import os
import csv
import json
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, ElementTree


def run_layer_1_raw_file_rescue():
    # --------------------------------------------------------
    # Create Layer 1 folder
    # --------------------------------------------------------
    layer_path = os.path.join(stage0_path, "01_raw_file_rescue")
    os.makedirs(layer_path, exist_ok=True)

    # --------------------------------------------------------
    # Output file paths
    # --------------------------------------------------------
    report_txt = os.path.join(layer_path, "raw_file_rescue_report.txt")
    audit_json = os.path.join(layer_path, "raw_file_rescue_audit.json")
    audit_xml = os.path.join(layer_path, "raw_file_rescue_audit.xml")
    broken_rows_csv = os.path.join(layer_path, "broken_rows_report.csv")
    encoding_report_txt = os.path.join(layer_path, "encoding_audit.txt")
    file_inventory_txt = os.path.join(layer_path, "file_inventory.txt")
    delimiter_report_txt = os.path.join(layer_path, "delimiter_and_structure_audit.txt")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    # --------------------------------------------------------
    # Basic file checks
    # --------------------------------------------------------
    file_exists = os.path.exists(dataset_path)
    file_extension = os.path.splitext(dataset_path)[1].lower()
    file_size_bytes = os.path.getsize(dataset_path) if file_exists else 0
    file_size_mb = round(file_size_bytes / (1024 * 1024), 4) if file_exists else 0

    if not file_exists:
        raise FileNotFoundError(f"Dataset file not found: {dataset_path}")

    # --------------------------------------------------------
    # Read raw bytes
    # --------------------------------------------------------
    with open(dataset_path, "rb") as f:
        raw_bytes = f.read()

    bom_detected = raw_bytes.startswith(b"\xef\xbb\xbf")
    null_bytes_count = raw_bytes.count(b"\x00")

    # --------------------------------------------------------
    # Encoding detection attempt
    # --------------------------------------------------------
    encodings_to_test = ["utf-8", "utf-8-sig", "cp1252", "latin1"]
    encoding_results = []
    selected_encoding = None
    decoded_text = ""

    for enc in encodings_to_test:
        try:
            decoded_text = raw_bytes.decode(enc)
            selected_encoding = enc
            encoding_results.append({
                "encoding": enc,
                "status": "success",
                "error": ""
            })
            break
        except Exception as e:
            encoding_results.append({
                "encoding": enc,
                "status": "failed",
                "error": str(e)
            })

    if selected_encoding is None:
        decoded_text = raw_bytes.decode("utf-8", errors="replace")
        selected_encoding = "utf-8_with_replacement"

    replacement_character_count = decoded_text.count("�")

    control_character_count = sum(
        1 for ch in decoded_text
        if ord(ch) < 32 and ch not in ["\n", "\r", "\t"]
    )

    # --------------------------------------------------------
    # Line-level checks
    # --------------------------------------------------------
    lines = decoded_text.splitlines()
    total_lines = len(lines)
    empty_lines = sum(1 for line in lines if line.strip() == "")
    whitespace_only_lines = sum(1 for line in lines if line != "" and line.strip() == "")

    very_long_lines = sum(1 for line in lines if len(line) > 10000)

    # --------------------------------------------------------
    # Delimiter and broken-row checks for CSV/TXT files
    # --------------------------------------------------------
    guessed_delimiter = None
    delimiter_counts = {}
    broken_rows = []
    expected_columns = None

    if file_extension in [".csv", ".txt"]:
        sample_text = "\n".join(lines[:50])
        delimiter_candidates = [",", ";", "\t", "|"]

        delimiter_counts = {
            "comma": sample_text.count(","),
            "semicolon": sample_text.count(";"),
            "tab": sample_text.count("\t"),
            "pipe": sample_text.count("|")
        }

        # Basic delimiter guess
        delimiter_map = {
            "comma": ",",
            "semicolon": ";",
            "tab": "\t",
            "pipe": "|"
        }

        best_delimiter_name = max(delimiter_counts, key=delimiter_counts.get)
        guessed_delimiter = delimiter_map[best_delimiter_name]

        try:
            reader = csv.reader(lines, delimiter=guessed_delimiter)

            for row_number, row in enumerate(reader, start=1):
                if row_number == 1:
                    expected_columns = len(row)
                else:
                    if expected_columns is not None and len(row) != expected_columns:
                        broken_rows.append({
                            "row_number": row_number,
                            "expected_columns": expected_columns,
                            "actual_columns": len(row),
                            "row_preview": str(row)[:300]
                        })

        except Exception as e:
            broken_rows.append({
                "row_number": "unknown",
                "expected_columns": "unknown",
                "actual_columns": "unknown",
                "row_preview": f"CSV structure check failed: {e}"
            })

    # --------------------------------------------------------
    # Save broken rows CSV
    # --------------------------------------------------------
    with open(broken_rows_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["row_number", "expected_columns", "actual_columns", "row_preview"]
        )
        writer.writeheader()
        for row in broken_rows:
            writer.writerow(row)

    # --------------------------------------------------------
    # Status interpretation
    # --------------------------------------------------------
    serious_warnings = []

    if replacement_character_count > 0:
        serious_warnings.append("Possible encoding issue: replacement character found.")

    if null_bytes_count > 0:
        serious_warnings.append("Null bytes detected. File may contain binary or damaged content.")

    if len(broken_rows) > 0:
        serious_warnings.append("Broken or irregular rows detected.")

    if empty_lines > 0:
        serious_warnings.append("Empty lines detected.")

    if very_long_lines > 0:
        serious_warnings.append("Very long lines detected.")

    if len(serious_warnings) == 0:
        layer_status = "PASS"
    else:
        layer_status = "REVIEW_REQUIRED"

    # --------------------------------------------------------
    # JSON audit
    # --------------------------------------------------------
    audit = {
        "stage": "Layer 1 - Raw File Rescue",
        "created_on": str(datetime.now()),
        "dataset_path": dataset_path,
        "file_exists": file_exists,
        "file_extension": file_extension,
        "file_size_bytes": file_size_bytes,
        "file_size_mb": file_size_mb,
        "selected_encoding": selected_encoding,
        "encoding_results": encoding_results,
        "bom_detected": bom_detected,
        "null_bytes_count": null_bytes_count,
        "replacement_character_count": replacement_character_count,
        "control_character_count": control_character_count,
        "total_lines": total_lines,
        "empty_lines": empty_lines,
        "whitespace_only_lines": whitespace_only_lines,
        "very_long_lines": very_long_lines,
        "guessed_delimiter": guessed_delimiter,
        "delimiter_counts": delimiter_counts,
        "expected_columns_from_header": expected_columns,
        "broken_rows_count": len(broken_rows),
        "broken_rows_report": broken_rows_csv,
        "layer_status": layer_status,
        "warnings": serious_warnings,
        "next_action": "Run Layer 2 - Dataset Structure"
    }

    with open(audit_json, "w", encoding="utf-8") as f:
        json.dump(audit, f, indent=4, ensure_ascii=False)

    # --------------------------------------------------------
    # XML audit
    # --------------------------------------------------------
    root = Element("raw_file_rescue_audit")

    for key, value in audit.items():
        node = SubElement(root, key)

        if isinstance(value, list):
            for item in value:
                item_node = SubElement(node, "item")
                item_node.text = str(item)

        elif isinstance(value, dict):
            for k, v in value.items():
                child = SubElement(node, str(k).replace(" ", "_"))
                child.text = str(v)

        else:
            node.text = str(value)

    tree = ElementTree(root)
    tree.write(audit_xml, encoding="utf-8", xml_declaration=True)

    # --------------------------------------------------------
    # TXT reports
    # --------------------------------------------------------
    inventory_text = f"""
FILE INVENTORY
==================================================

Created On:
{datetime.now()}

Dataset Path:
{dataset_path}

File Exists:
{file_exists}

File Extension:
{file_extension}

File Size:
{file_size_bytes} bytes

File Size MB:
{file_size_mb}
"""

    encoding_text = f"""
ENCODING AUDIT
==================================================

Selected Encoding:
{selected_encoding}

BOM Detected:
{bom_detected}

Null Bytes Count:
{null_bytes_count}

Replacement Character Count:
{replacement_character_count}

Control Character Count:
{control_character_count}

Encoding Attempts:
{json.dumps(encoding_results, indent=4)}
"""

    delimiter_text = f"""
DELIMITER AND STRUCTURE AUDIT
==================================================

File Extension:
{file_extension}

Total Lines:
{total_lines}

Empty Lines:
{empty_lines}

Whitespace-Only Lines:
{whitespace_only_lines}

Very Long Lines:
{very_long_lines}

Guessed Delimiter:
{guessed_delimiter}

Delimiter Counts:
{delimiter_counts}

Expected Columns From Header:
{expected_columns}

Broken Rows Count:
{len(broken_rows)}

Broken Rows Report:
{broken_rows_csv}
"""

    report_text = f"""
LAYER 1: RAW FILE RESCUE REPORT
==================================================

Created On:
{datetime.now()}

Dataset Path:
{dataset_path}

Layer Status:
{layer_status}

File Exists:
{file_exists}

File Extension:
{file_extension}

File Size:
{file_size_mb} MB

Selected Encoding:
{selected_encoding}

BOM Detected:
{bom_detected}

Null Bytes Count:
{null_bytes_count}

Replacement Character Count:
{replacement_character_count}

Control Character Count:
{control_character_count}

Total Lines:
{total_lines}

Empty Lines:
{empty_lines}

Whitespace-Only Lines:
{whitespace_only_lines}

Very Long Lines:
{very_long_lines}

Guessed Delimiter:
{guessed_delimiter}

Expected Columns From Header:
{expected_columns}

Broken Rows Count:
{len(broken_rows)}

Warnings:
{serious_warnings}

Files Created:
1. {file_inventory_txt}
2. {encoding_report_txt}
3. {delimiter_report_txt}
4. {broken_rows_csv}
5. {audit_json}
6. {audit_xml}

Meaning:
Layer 1 checks file-level problems before deeper dataset analysis.
It detects encoding issues, BOM, null bytes, empty lines, delimiter structure,
and broken rows.

Important:
This layer does not modify the raw dataset.

Next Action:
Run Layer 2 - Dataset Structure.
"""

    with open(file_inventory_txt, "w", encoding="utf-8") as f:
        f.write(inventory_text)

    with open(encoding_report_txt, "w", encoding="utf-8") as f:
        f.write(encoding_text)

    with open(delimiter_report_txt, "w", encoding="utf-8") as f:
        f.write(delimiter_text)

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report_text)

    # --------------------------------------------------------
    # Update root purpose file
    # --------------------------------------------------------
    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 1 UPDATE: RAW FILE RESCUE
==================================================

Layer 1 completed on:
{datetime.now()}

Layer Status:
{layer_status}

Selected Encoding:
{selected_encoding}

Empty Lines:
{empty_lines}

Broken Rows:
{len(broken_rows)}

Warnings:
{serious_warnings}

Next Required Stage:
Layer 2 should inspect dataset structure, column names, datatypes,
null columns, duplicate columns, and sample values.
""")

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------
    print("Layer 1 completed successfully.")
    print("Layer Status:", layer_status)
    print("Selected Encoding:", selected_encoding)
    print("Empty Lines:", empty_lines)
    print("Broken Rows:", len(broken_rows))
    print("Files created:")
    print(report_txt)
    print(audit_json)
    print(audit_xml)
    print(broken_rows_csv)
    print(encoding_report_txt)
    print(file_inventory_txt)
    print(delimiter_report_txt)


# Run Layer 1
run_layer_1_raw_file_rescue()

Layer 1 completed successfully.
Layer Status: PASS
Selected Encoding: utf-8
Empty Lines: 0
Broken Rows: 0
Files created:
d:\Med_data\stage0-launch-pad\01_raw_file_rescue\raw_file_rescue_report.txt
d:\Med_data\stage0-launch-pad\01_raw_file_rescue\raw_file_rescue_audit.json
d:\Med_data\stage0-launch-pad\01_raw_file_rescue\raw_file_rescue_audit.xml
d:\Med_data\stage0-launch-pad\01_raw_file_rescue\broken_rows_report.csv
d:\Med_data\stage0-launch-pad\01_raw_file_rescue\encoding_audit.txt
d:\Med_data\stage0-launch-pad\01_raw_file_rescue\file_inventory.txt
d:\Med_data\stage0-launch-pad\01_raw_file_rescue\delimiter_and_structure_audit.txt

In [31]:
# ============================================================
# LAYER 2: DATASET STRUCTURE
# Run after Layer 1
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# Optional variables:
# base_path
# ============================================================

import os
import re
import json
import pandas as pd
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, ElementTree


def run_layer_2_dataset_structure():
    # --------------------------------------------------------
    # Create Layer 2 folder
    # --------------------------------------------------------
    layer_path = os.path.join(stage0_path, "02_dataset_structure")
    os.makedirs(layer_path, exist_ok=True)

    # --------------------------------------------------------
    # Output file paths
    # --------------------------------------------------------
    report_txt = os.path.join(layer_path, "dataset_structure_report.txt")
    column_list_csv = os.path.join(layer_path, "column_list.csv")
    schema_json = os.path.join(layer_path, "schema_inferred.json")
    schema_xml = os.path.join(layer_path, "schema_inferred.xml")
    sample_csv = os.path.join(layer_path, "sample_rows_preview.csv")
    column_names_txt = os.path.join(layer_path, "column_names.txt")
    structure_warnings_txt = os.path.join(layer_path, "structure_warnings.txt")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    # --------------------------------------------------------
    # Helper functions
    # --------------------------------------------------------
    def safe_percent(part, total):
        if total == 0:
            return 0
        return round((part / total) * 100, 4)

    def detect_possible_date_column(series, col_name):
        name = str(col_name).lower()

        if "date" in name or "time" in name or "dob" in name:
            return True

        if series.dtype == "object":
            sample = series.dropna().astype(str).head(100)

            if len(sample) == 0:
                return False

            parsed = pd.to_datetime(sample, errors="coerce")
            return parsed.notna().mean() >= 0.60

        return False

    def detect_numeric_stored_as_text(series):
        if series.dtype != "object":
            return False

        sample = series.dropna().astype(str).str.replace(",", "", regex=False).head(200)

        if len(sample) == 0:
            return False

        converted = pd.to_numeric(sample, errors="coerce")
        return converted.notna().mean() >= 0.80

    def detect_id_like_column(series, col_name):
        name = str(col_name).lower()
        unique_count = series.nunique(dropna=True)
        total_rows = len(series)
        unique_ratio = unique_count / total_rows if total_rows > 0 else 0

        if "id" in name and unique_ratio >= 0.70:
            return True

        if unique_ratio >= 0.95:
            return True

        return False

    def detect_possible_pii_column(col_name):
        name = str(col_name).lower()

        pii_keywords = [
            "name", "email", "phone", "mobile", "address", "cnic",
            "passport", "ssn", "patient", "student", "customer",
            "account", "iban", "credit", "card"
        ]

        return any(k in name for k in pii_keywords)

    # --------------------------------------------------------
    # Basic structure checks
    # --------------------------------------------------------
    total_rows = int(df.shape[0])
    total_columns = int(df.shape[1])

    duplicate_column_count = int(pd.Index(df.columns).duplicated().sum())
    duplicate_columns = list(pd.Index(df.columns)[pd.Index(df.columns).duplicated()].astype(str))

    unnamed_columns = [
        str(col) for col in df.columns
        if str(col).lower().startswith("unnamed")
    ]

    empty_column_names = [
        str(col) for col in df.columns
        if str(col).strip() == ""
    ]

    fully_null_columns = [
        str(col) for col in df.columns
        if df[col].isna().all()
    ]

    mostly_null_columns = [
        str(col) for col in df.columns
        if df[col].isna().mean() >= 0.80
    ]

    constant_columns = [
        str(col) for col in df.columns
        if df[col].nunique(dropna=True) <= 1
    ]

    # --------------------------------------------------------
    # Column-level structure profile
    # --------------------------------------------------------
    column_rows = []

    for col in df.columns:
        series = df[col]
        non_null_count = int(series.notna().sum())
        null_count = int(series.isna().sum())
        unique_count = int(series.nunique(dropna=True))

        column_rows.append({
            "column_name": str(col),
            "dtype": str(series.dtype),
            "non_null_count": non_null_count,
            "null_count": null_count,
            "missing_percentage": safe_percent(null_count, total_rows),
            "unique_values": unique_count,
            "unique_percentage": safe_percent(unique_count, total_rows),
            "is_numeric": bool(pd.api.types.is_numeric_dtype(series)),
            "is_object_text": bool(series.dtype == "object"),
            "is_date_like": bool(detect_possible_date_column(series, col)),
            "numeric_stored_as_text": bool(detect_numeric_stored_as_text(series)),
            "is_id_like": bool(detect_id_like_column(series, col)),
            "is_possible_pii": bool(detect_possible_pii_column(col)),
            "sample_values": " | ".join(series.dropna().astype(str).head(5).tolist())
        })

    column_profile_df = pd.DataFrame(column_rows)
    column_profile_df.to_csv(column_list_csv, index=False)

    # --------------------------------------------------------
    # Save sample rows
    # --------------------------------------------------------
    df.head(20).to_csv(sample_csv, index=False)

    # --------------------------------------------------------
    # Column names TXT
    # --------------------------------------------------------
    column_names_text = "COLUMN NAMES\n"
    column_names_text += "=" * 50 + "\n\n"

    for i, col in enumerate(df.columns, start=1):
        column_names_text += f"{i}. {col}\n"

    with open(column_names_txt, "w", encoding="utf-8") as f:
        f.write(column_names_text)

    # --------------------------------------------------------
    # Warnings
    # --------------------------------------------------------
    warnings = []

    if duplicate_column_count > 0:
        warnings.append("Duplicate column names found.")

    if len(unnamed_columns) > 0:
        warnings.append("Unnamed columns found.")

    if len(empty_column_names) > 0:
        warnings.append("Empty column names found.")

    if len(fully_null_columns) > 0:
        warnings.append("Fully null columns found.")

    if len(mostly_null_columns) > 0:
        warnings.append("Mostly null columns, 80% or more missing, found.")

    if len(constant_columns) > 0:
        warnings.append("Constant columns found.")

    numeric_text_cols = column_profile_df[
        column_profile_df["numeric_stored_as_text"] == True
    ]["column_name"].tolist()

    if len(numeric_text_cols) > 0:
        warnings.append("Some numeric values appear to be stored as text.")

    id_like_cols = column_profile_df[
        column_profile_df["is_id_like"] == True
    ]["column_name"].tolist()

    if len(id_like_cols) > 0:
        warnings.append("ID-like columns detected.")

    pii_cols = column_profile_df[
        column_profile_df["is_possible_pii"] == True
    ]["column_name"].tolist()

    if len(pii_cols) > 0:
        warnings.append("Possible PII or sensitive columns detected.")

    if len(warnings) == 0:
        layer_status = "PASS"
    else:
        layer_status = "REVIEW_REQUIRED"

    warnings_text = f"""
STRUCTURE WARNINGS
==================================================

Layer Status:
{layer_status}

Warnings:
{warnings}

Duplicate Columns:
{duplicate_columns}

Unnamed Columns:
{unnamed_columns}

Empty Column Names:
{empty_column_names}

Fully Null Columns:
{fully_null_columns}

Mostly Null Columns, 80%+:
{mostly_null_columns}

Constant Columns:
{constant_columns}

Numeric Stored As Text Columns:
{numeric_text_cols}

ID-Like Columns:
{id_like_cols}

Possible PII Columns:
{pii_cols}
"""

    with open(structure_warnings_txt, "w", encoding="utf-8") as f:
        f.write(warnings_text)

    # --------------------------------------------------------
    # JSON schema
    # --------------------------------------------------------
    schema = {
        "stage": "Layer 2 - Dataset Structure",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": total_columns,
        "layer_status": layer_status,
        "duplicate_column_count": duplicate_column_count,
        "duplicate_columns": duplicate_columns,
        "unnamed_columns": unnamed_columns,
        "empty_column_names": empty_column_names,
        "fully_null_columns": fully_null_columns,
        "mostly_null_columns_80_percent_plus": mostly_null_columns,
        "constant_columns": constant_columns,
        "numeric_stored_as_text_columns": numeric_text_cols,
        "id_like_columns": id_like_cols,
        "possible_pii_columns": pii_cols,
        "warnings": warnings,
        "column_profiles": column_rows,
        "files_created": {
            "column_list_csv": column_list_csv,
            "sample_rows_preview": sample_csv,
            "column_names_txt": column_names_txt,
            "structure_warnings_txt": structure_warnings_txt
        },
        "next_action": "Run Layer 3 - Data Quality"
    }

    with open(schema_json, "w", encoding="utf-8") as f:
        json.dump(schema, f, indent=4, ensure_ascii=False)

    # --------------------------------------------------------
    # XML schema
    # --------------------------------------------------------
    root = Element("schema_inferred")

    for key, value in schema.items():
        node = SubElement(root, key)

        if isinstance(value, list):
            for item in value:
                item_node = SubElement(node, "item")
                item_node.text = str(item)

        elif isinstance(value, dict):
            for k, v in value.items():
                child = SubElement(node, str(k).replace(" ", "_"))
                child.text = str(v)

        else:
            node.text = str(value)

    tree = ElementTree(root)
    tree.write(schema_xml, encoding="utf-8", xml_declaration=True)

    # --------------------------------------------------------
    # Main TXT report
    # --------------------------------------------------------
    report_text = f"""
LAYER 2: DATASET STRUCTURE REPORT
==================================================

Created On:
{datetime.now()}

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Layer Status:
{layer_status}

Number of Rows:
{total_rows}

Number of Columns:
{total_columns}

Duplicate Column Count:
{duplicate_column_count}

Duplicate Columns:
{duplicate_columns}

Unnamed Columns:
{unnamed_columns}

Empty Column Names:
{empty_column_names}

Fully Null Columns:
{fully_null_columns}

Mostly Null Columns, 80%+:
{mostly_null_columns}

Constant Columns:
{constant_columns}

Numeric Stored As Text Columns:
{numeric_text_cols}

ID-Like Columns:
{id_like_cols}

Possible PII Columns:
{pii_cols}

Warnings:
{warnings}

Files Created:
1. {report_txt}
2. {column_list_csv}
3. {schema_json}
4. {schema_xml}
5. {sample_csv}
6. {column_names_txt}
7. {structure_warnings_txt}

Meaning:
Layer 2 studies the basic dataset structure.
It checks rows, columns, names, datatypes, null columns,
constant columns, possible ID columns, possible date columns,
numeric values stored as text, and possible PII columns.

Important:
This layer does not clean or modify the dataset.
It only describes the structure.

Next Action:
Run Layer 3 - Data Quality.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report_text)

    # --------------------------------------------------------
    # Update root purpose file
    # --------------------------------------------------------
    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 2 UPDATE: DATASET STRUCTURE
==================================================

Layer 2 completed on:
{datetime.now()}

Layer Status:
{layer_status}

Rows:
{total_rows}

Columns:
{total_columns}

Duplicate Columns:
{duplicate_columns}

Fully Null Columns:
{fully_null_columns}

Constant Columns:
{constant_columns}

ID-Like Columns:
{id_like_cols}

Possible PII Columns:
{pii_cols}

Warnings:
{warnings}

Next Required Stage:
Layer 3 should inspect missing values, empty rows, duplicate rows,
placeholder missing tokens, noisy values, and overall data quality.
""")

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------
    print("Layer 2 completed successfully.")
    print("Layer Status:", layer_status)
    print("Rows:", total_rows)
    print("Columns:", total_columns)
    print("Warnings:", warnings)
    print("Files created:")
    print(report_txt)
    print(column_list_csv)
    print(schema_json)
    print(schema_xml)
    print(sample_csv)
    print(column_names_txt)
    print(structure_warnings_txt)

    display(column_profile_df)


# Run Layer 2
run_layer_2_dataset_structure()

C:\Users\HC\AppData\Local\Temp\ipykernel_15400\682422224.py:58: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\682422224.py:58: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\682422224.py:58: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\682422224.py:58: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\682422224.py:58: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\682422224.py:58: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\682422224.py:58: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")

Layer 2 completed successfully.
Layer Status: REVIEW_REQUIRED
Rows: 55500
Columns: 15
Warnings: ['Possible PII or sensitive columns detected.']
Files created:
d:\Med_data\stage0-launch-pad\02_dataset_structure\dataset_structure_report.txt
d:\Med_data\stage0-launch-pad\02_dataset_structure\column_list.csv
d:\Med_data\stage0-launch-pad\02_dataset_structure\schema_inferred.json
d:\Med_data\stage0-launch-pad\02_dataset_structure\schema_inferred.xml
d:\Med_data\stage0-launch-pad\02_dataset_structure\sample_rows_preview.csv
d:\Med_data\stage0-launch-pad\02_dataset_structure\column_names.txt
d:\Med_data\stage0-launch-pad\02_dataset_structure\structure_warnings.txt

C:\Users\HC\AppData\Local\Temp\ipykernel_15400\682422224.py:58: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\682422224.py:58: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\682422224.py:58: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")

,column_name,dtype,non_null_count,null_count,missing_percentage,unique_values,unique_percentage,is_numeric,is_object_text,is_date_like,numeric_stored_as_text,is_id_like,is_possible_pii,sample_values
0,Name,object,55500,0,0.0,49992,90.0757,False,True,False,False,False,True,Bobby JacksOn | LesLie TErRy | DaNnY sMitH | a...
1,Age,int64,55500,0,0.0,77,0.1387,True,False,False,False,False,False,30 | 62 | 76 | 28 | 43
2,Gender,object,55500,0,0.0,2,0.0036,False,True,False,False,False,False,Male | Male | Female | Female | Female
3,Blood Type,object,55500,0,0.0,8,0.0144,False,True,False,False,False,False,B- | A+ | A- | O+ | AB+
4,Medical Condition,object,55500,0,0.0,6,0.0108,False,True,False,False,False,False,Cancer | Obesity | Obesity | Diabetes | Cancer
5,Date of Admission,object,55500,0,0.0,1827,3.2919,False,True,True,False,False,False,2024-01-31 | 2019-08-20 | 2022-09-22 | 2020-11...
6,Doctor,object,55500,0,0.0,40341,72.6865,False,True,False,False,False,False,Matthew Smith | Samantha Davies | Tiffany Mitc...
7,Hospital,object,55500,0,0.0,39876,71.8486,False,True,False,False,False,False,Sons and Miller | Kim Inc | Cook PLC | Hernand...
8,Insurance Provider,object,55500,0,0.0,5,0.0090,False,True,False,False,False,False,Blue Cross | Medicare | Aetna | Medicare | Aetna
9,Billing Amount,float64,55500,0,0.0,50000,90.0901,True,False,False,False,False,False,18856.281305978155 | 33643.327286577885 | 2795...
10,Room Number,int64,55500,0,0.0,400,0.7207,True,False,False,False,False,False,328 | 265 | 205 | 450 | 458
11,Admission Type,object,55500,0,0.0,3,0.0054,False,True,False,False,False,False,Urgent | Emergency | Emergency | Elective | Ur...
12,Discharge Date,object,55500,0,0.0,1856,3.3441,False,True,True,False,False,False,2024-02-02 | 2019-08-26 | 2022-10-07 | 2020-12...
13,Medication,object,55500,0,0.0,5,0.0090,False,True,False,False,False,False,Paracetamol | Ibuprofen | Aspirin | Ibuprofen ...
14,Test Results,object,55500,0,0.0,3,0.0054,False,True,False,False,False,False,Normal | Inconclusive | Normal | Abnormal | Ab...

In [33]:
# ============================================================
# LAYER 3: DATA QUALITY
# Run after Layer 2
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import re
import json
import pandas as pd
import numpy as np
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, ElementTree


def run_layer_3_data_quality():
    # --------------------------------------------------------
    # Create Layer 3 folder
    # --------------------------------------------------------
    layer_path = os.path.join(stage0_path, "03_data_quality")
    os.makedirs(layer_path, exist_ok=True)

    # --------------------------------------------------------
    # Output file paths
    # --------------------------------------------------------
    report_txt = os.path.join(layer_path, "data_quality_report.txt")
    missing_csv = os.path.join(layer_path, "missing_values_report.csv")
    empty_rows_csv = os.path.join(layer_path, "empty_rows_report.csv")
    duplicate_rows_csv = os.path.join(layer_path, "duplicate_rows_report.csv")
    noisy_values_csv = os.path.join(layer_path, "noisy_values_report.csv")
    placeholder_values_csv = os.path.join(layer_path, "placeholder_values_report.csv")
    outlier_csv = os.path.join(layer_path, "initial_outlier_scan.csv")
    quality_json = os.path.join(layer_path, "quality_scorecard.json")
    quality_xml = os.path.join(layer_path, "quality_scorecard.xml")
    cleaned_candidate_csv = os.path.join(layer_path, "stage0_cleaned_candidate.csv")
    cleaning_recommendations_txt = os.path.join(layer_path, "cleaning_recommendations.txt")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    # --------------------------------------------------------
    # Helper functions
    # --------------------------------------------------------
    def safe_percent(part, total):
        if total == 0:
            return 0
        return round((part / total) * 100, 4)

    def normalize_missing_tokens(dataframe):
        missing_tokens = [
            "", " ", "NA", "N/A", "na", "n/a", "NULL", "null",
            "None", "none", "NONE", "?", "??", "-", "--",
            "unknown", "Unknown", "UNKNOWN", "missing", "Missing",
            "not available", "Not Available", "NOT AVAILABLE"
        ]

        cleaned = dataframe.copy()

        for col in cleaned.columns:
            if cleaned[col].dtype == "object":
                cleaned[col] = cleaned[col].apply(
                    lambda x: np.nan if isinstance(x, str) and x.strip() in missing_tokens else x
                )

        return cleaned

    # --------------------------------------------------------
    # Normalize obvious missing tokens
    # --------------------------------------------------------
    normalized_df = normalize_missing_tokens(df)

    total_rows = int(normalized_df.shape[0])
    total_columns = int(normalized_df.shape[1])

    # --------------------------------------------------------
    # Missing values report
    # --------------------------------------------------------
    missing_rows = []

    for col in normalized_df.columns:
        missing_count = int(normalized_df[col].isna().sum())
        missing_rows.append({
            "column_name": str(col),
            "missing_count": missing_count,
            "missing_percentage": safe_percent(missing_count, total_rows),
            "non_missing_count": int(normalized_df[col].notna().sum()),
            "unique_values": int(normalized_df[col].nunique(dropna=True))
        })

    missing_df = pd.DataFrame(missing_rows)
    missing_df.to_csv(missing_csv, index=False)

    # --------------------------------------------------------
    # Empty and mostly empty rows
    # --------------------------------------------------------
    empty_rows_df = normalized_df[normalized_df.isna().all(axis=1)]
    mostly_empty_rows_df = normalized_df[normalized_df.isna().mean(axis=1) >= 0.90]

    empty_rows_count = int(len(empty_rows_df))
    mostly_empty_rows_count = int(len(mostly_empty_rows_df))

    mostly_empty_rows_df.to_csv(empty_rows_csv, index=False)

    # --------------------------------------------------------
    # Duplicate rows
    # --------------------------------------------------------
    duplicate_rows_df = normalized_df[normalized_df.duplicated(keep=False)]
    duplicate_rows_count = int(normalized_df.duplicated().sum())
    duplicate_rows_df.to_csv(duplicate_rows_csv, index=False)

    # --------------------------------------------------------
    # Null and mostly null columns
    # --------------------------------------------------------
    fully_null_columns = [
        str(col) for col in normalized_df.columns
        if normalized_df[col].isna().all()
    ]

    mostly_null_columns = [
        str(col) for col in normalized_df.columns
        if normalized_df[col].isna().mean() >= 0.80
    ]

    # --------------------------------------------------------
    # Placeholder value report
    # --------------------------------------------------------
    placeholder_tokens = [
        "NA", "N/A", "NULL", "None", "none", "?", "??",
        "-", "--", "unknown", "Unknown", "UNKNOWN",
        "missing", "Missing", "not available"
    ]

    placeholder_rows = []

    for col in df.columns:
        if df[col].dtype == "object":
            s = df[col].dropna().astype(str).str.strip()

            for token in placeholder_tokens:
                count = int((s == token).sum())

                if count > 0:
                    placeholder_rows.append({
                        "column_name": str(col),
                        "placeholder_value": token,
                        "count": count,
                        "percentage": safe_percent(count, total_rows)
                    })

    placeholder_df = pd.DataFrame(placeholder_rows)
    placeholder_df.to_csv(placeholder_values_csv, index=False)

    # --------------------------------------------------------
    # Noisy text values report
    # --------------------------------------------------------
    noisy_rows = []

    for col in normalized_df.columns:
        if normalized_df[col].dtype == "object":
            s = normalized_df[col].dropna().astype(str)

            leading_trailing_spaces = int(s.apply(lambda x: x != x.strip()).sum())
            multiple_spaces = int(s.apply(lambda x: bool(re.search(r"\s{2,}", x))).sum())
            replacement_chars = int(s.apply(lambda x: "�" in x).sum())
            strange_chars = int(
                s.apply(lambda x: bool(re.search(r"[^\w\s.,:/@+\-()#%&]", x))).sum()
            )

            original_unique = int(s.nunique())
            lower_unique = int(s.str.lower().nunique())

            noisy_rows.append({
                "column_name": str(col),
                "leading_trailing_space_count": leading_trailing_spaces,
                "multiple_space_count": multiple_spaces,
                "replacement_character_count": replacement_chars,
                "strange_character_count": strange_chars,
                "original_unique_values": original_unique,
                "case_normalized_unique_values": lower_unique,
                "possible_case_inconsistency": bool(lower_unique < original_unique)
            })

    noisy_df = pd.DataFrame(noisy_rows)
    noisy_df.to_csv(noisy_values_csv, index=False)

    # --------------------------------------------------------
    # Initial numeric outlier scan using IQR
    # --------------------------------------------------------
    outlier_rows = []

    numeric_df = normalized_df.select_dtypes(include=["number"])

    for col in numeric_df.columns:
        s = numeric_df[col].dropna()

        if len(s) > 0:
            q1 = s.quantile(0.25)
            q3 = s.quantile(0.75)
            iqr = q3 - q1
            lower_bound = q1 - 1.5 * iqr
            upper_bound = q3 + 1.5 * iqr
            outlier_count = int(((s < lower_bound) | (s > upper_bound)).sum())

            outlier_rows.append({
                "column_name": str(col),
                "q1": q1,
                "q3": q3,
                "iqr": iqr,
                "lower_bound": lower_bound,
                "upper_bound": upper_bound,
                "outlier_count": outlier_count,
                "outlier_percentage": safe_percent(outlier_count, len(s))
            })

    outlier_df = pd.DataFrame(outlier_rows)
    outlier_df.to_csv(outlier_csv, index=False)

    # --------------------------------------------------------
    # Quality score
    # --------------------------------------------------------
    average_missing_percentage = round(float(normalized_df.isna().mean().mean() * 100), 4)

    quality_score = 100
    quality_score -= min(30, average_missing_percentage)
    quality_score -= min(20, safe_percent(duplicate_rows_count, total_rows))
    quality_score -= min(20, len(fully_null_columns) * 5)
    quality_score -= min(15, safe_percent(mostly_empty_rows_count, total_rows))
    quality_score -= min(10, len(placeholder_rows))
    quality_score = max(0, round(quality_score, 2))

    # --------------------------------------------------------
    # Warnings
    # --------------------------------------------------------
    warnings = []

    if empty_rows_count > 0:
        warnings.append("Fully empty rows found.")

    if mostly_empty_rows_count > 0:
        warnings.append("Rows with 90% or more missing values found.")

    if duplicate_rows_count > 0:
        warnings.append("Duplicate rows found.")

    if len(fully_null_columns) > 0:
        warnings.append("Fully null columns found.")

    if len(mostly_null_columns) > 0:
        warnings.append("Mostly null columns found.")

    if len(placeholder_rows) > 0:
        warnings.append("Placeholder missing values found.")

    if not noisy_df.empty and noisy_df[
        [
            "leading_trailing_space_count",
            "multiple_space_count",
            "replacement_character_count",
            "strange_character_count"
        ]
    ].sum().sum() > 0:
        warnings.append("Noisy text values found.")

    if quality_score >= 85:
        layer_status = "GOOD"
    elif quality_score >= 70:
        layer_status = "REVIEW_RECOMMENDED"
    else:
        layer_status = "REVIEW_REQUIRED"

    # --------------------------------------------------------
    # Save cleaned candidate
    # --------------------------------------------------------
    normalized_df.to_csv(cleaned_candidate_csv, index=False)

    # --------------------------------------------------------
    # Cleaning recommendations
    # --------------------------------------------------------
    recommendations = []

    if len(fully_null_columns) > 0:
        recommendations.append("Review fully null columns; usually they should be removed after confirmation.")

    if len(mostly_null_columns) > 0:
        recommendations.append("Review mostly null columns; decide whether to remove, impute, or keep with missing flags.")

    if duplicate_rows_count > 0:
        recommendations.append("Review duplicate rows before deleting because some duplicates may be valid repeated records.")

    if empty_rows_count > 0 or mostly_empty_rows_count > 0:
        recommendations.append("Remove fully empty rows and review rows with 90% or more missing values.")

    if len(placeholder_rows) > 0:
        recommendations.append("Normalize placeholder values such as NA, NULL, ?, unknown into proper missing values.")

    if not noisy_df.empty:
        recommendations.append("Trim leading/trailing spaces and standardize category spelling/case where required.")

    if not outlier_df.empty:
        recommendations.append("Review numeric outliers. Do not remove automatically unless domain rules confirm they are invalid.")

    if len(recommendations) == 0:
        recommendations.append("No major data quality issue detected automatically. Manual review is still recommended.")

    cleaning_text = "CLEANING RECOMMENDATIONS\n"
    cleaning_text += "=" * 50 + "\n\n"

    for i, rec in enumerate(recommendations, start=1):
        cleaning_text += f"{i}. {rec}\n"

    cleaning_text += f"""

Important:
This layer creates a cleaned candidate file only.
It does not modify the original raw dataset.

Cleaned Candidate File:
{cleaned_candidate_csv}
"""

    with open(cleaning_recommendations_txt, "w", encoding="utf-8") as f:
        f.write(cleaning_text)

    # --------------------------------------------------------
    # JSON quality scorecard
    # --------------------------------------------------------
    quality = {
        "stage": "Layer 3 - Data Quality",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": total_columns,
        "layer_status": layer_status,
        "quality_score_out_of_100": quality_score,
        "average_missing_percentage": average_missing_percentage,
        "empty_rows_count": empty_rows_count,
        "mostly_empty_rows_90_percent_plus_count": mostly_empty_rows_count,
        "duplicate_rows_count": duplicate_rows_count,
        "fully_null_columns": fully_null_columns,
        "mostly_null_columns_80_percent_plus": mostly_null_columns,
        "placeholder_values_found": len(placeholder_rows),
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "data_quality_report": report_txt,
            "missing_values_report": missing_csv,
            "empty_rows_report": empty_rows_csv,
            "duplicate_rows_report": duplicate_rows_csv,
            "noisy_values_report": noisy_values_csv,
            "placeholder_values_report": placeholder_values_csv,
            "initial_outlier_scan": outlier_csv,
            "quality_scorecard_json": quality_json,
            "quality_scorecard_xml": quality_xml,
            "cleaned_candidate_dataset": cleaned_candidate_csv,
            "cleaning_recommendations": cleaning_recommendations_txt
        },
        "next_action": "Run Layer 4 - Column Semantics"
    }

    with open(quality_json, "w", encoding="utf-8") as f:
        json.dump(quality, f, indent=4, ensure_ascii=False)

    # --------------------------------------------------------
    # XML quality scorecard
    # --------------------------------------------------------
    root = Element("quality_scorecard")

    for key, value in quality.items():
        node = SubElement(root, key)

        if isinstance(value, list):
            for item in value:
                item_node = SubElement(node, "item")
                item_node.text = str(item)

        elif isinstance(value, dict):
            for k, v in value.items():
                child = SubElement(node, str(k).replace(" ", "_"))
                child.text = str(v)

        else:
            node.text = str(value)

    tree = ElementTree(root)
    tree.write(quality_xml, encoding="utf-8", xml_declaration=True)

    # --------------------------------------------------------
    # Main TXT report
    # --------------------------------------------------------
    report_text = f"""
LAYER 3: DATA QUALITY REPORT
==================================================

Created On:
{datetime.now()}

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Layer Status:
{layer_status}

Quality Score:
{quality_score}/100

Rows:
{total_rows}

Columns:
{total_columns}

Average Missing Percentage:
{average_missing_percentage}%

Empty Rows:
{empty_rows_count}

Rows With 90% or More Missing Values:
{mostly_empty_rows_count}

Duplicate Rows:
{duplicate_rows_count}

Fully Null Columns:
{fully_null_columns}

Mostly Null Columns, 80%+:
{mostly_null_columns}

Placeholder Values Found:
{len(placeholder_rows)}

Warnings:
{warnings}

Recommendations:
{recommendations}

Files Created:
1. {report_txt}
2. {missing_csv}
3. {empty_rows_csv}
4. {duplicate_rows_csv}
5. {noisy_values_csv}
6. {placeholder_values_csv}
7. {outlier_csv}
8. {quality_json}
9. {quality_xml}
10. {cleaned_candidate_csv}
11. {cleaning_recommendations_txt}

Meaning:
Layer 3 checks data quality problems such as missing values, empty rows,
duplicate rows, null columns, placeholder values, noisy text, and initial outliers.

Important:
This layer creates a cleaned candidate file but does not modify the original dataset.

Next Action:
Run Layer 4 - Column Semantics.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report_text)

    # --------------------------------------------------------
    # Update root purpose file
    # --------------------------------------------------------
    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 3 UPDATE: DATA QUALITY
==================================================

Layer 3 completed on:
{datetime.now()}

Layer Status:
{layer_status}

Quality Score:
{quality_score}/100

Average Missing Percentage:
{average_missing_percentage}%

Empty Rows:
{empty_rows_count}

Rows With 90%+ Missing:
{mostly_empty_rows_count}

Duplicate Rows:
{duplicate_rows_count}

Fully Null Columns:
{fully_null_columns}

Mostly Null Columns:
{mostly_null_columns}

Warnings:
{warnings}

Next Required Stage:
Layer 4 should understand column meanings, possible feature roles,
possible target columns, PII fields, and leakage-risk columns.
""")

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------
    print("Layer 3 completed successfully.")
    print("Layer Status:", layer_status)
    print("Quality Score:", quality_score)
    print("Average Missing %:", average_missing_percentage)
    print("Empty Rows:", empty_rows_count)
    print("Duplicate Rows:", duplicate_rows_count)
    print("Fully Null Columns:", fully_null_columns)
    print("Files created:")
    print(report_txt)
    print(missing_csv)
    print(empty_rows_csv)
    print(duplicate_rows_csv)
    print(noisy_values_csv)
    print(placeholder_values_csv)
    print(outlier_csv)
    print(quality_json)
    print(quality_xml)
    print(cleaned_candidate_csv)
    print(cleaning_recommendations_txt)

    display(missing_df)


# Run Layer 3
run_layer_3_data_quality()

Layer 3 completed successfully.
Layer Status: GOOD
Quality Score: 99.04
Average Missing %: 0.0
Empty Rows: 0
Duplicate Rows: 534
Fully Null Columns: []
Files created:
d:\Med_data\stage0-launch-pad\03_data_quality\data_quality_report.txt
d:\Med_data\stage0-launch-pad\03_data_quality\missing_values_report.csv
d:\Med_data\stage0-launch-pad\03_data_quality\empty_rows_report.csv
d:\Med_data\stage0-launch-pad\03_data_quality\duplicate_rows_report.csv
d:\Med_data\stage0-launch-pad\03_data_quality\noisy_values_report.csv
d:\Med_data\stage0-launch-pad\03_data_quality\placeholder_values_report.csv
d:\Med_data\stage0-launch-pad\03_data_quality\initial_outlier_scan.csv
d:\Med_data\stage0-launch-pad\03_data_quality\quality_scorecard.json
d:\Med_data\stage0-launch-pad\03_data_quality\quality_scorecard.xml
d:\Med_data\stage0-launch-pad\03_data_quality\stage0_cleaned_candidate.csv
d:\Med_data\stage0-launch-pad\03_data_quality\cleaning_recommendations.txt

,column_name,missing_count,missing_percentage,non_missing_count,unique_values
0,Name,0,0.0,55500,49992
1,Age,0,0.0,55500,77
2,Gender,0,0.0,55500,2
3,Blood Type,0,0.0,55500,8
4,Medical Condition,0,0.0,55500,6
5,Date of Admission,0,0.0,55500,1827
6,Doctor,0,0.0,55500,40341
7,Hospital,0,0.0,55500,39876
8,Insurance Provider,0,0.0,55500,5
9,Billing Amount,0,0.0,55500,50000
10,Room Number,0,0.0,55500,400
11,Admission Type,0,0.0,55500,3
12,Discharge Date,0,0.0,55500,1856
13,Medication,0,0.0,55500,5
14,Test Results,0,0.0,55500,3

In [35]:
# ============================================================
# LAYER 4A: BASIC COLUMN SEMANTICS
# Run after Layer 3
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import re
import json
import pandas as pd
import numpy as np
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, ElementTree


def run_layer_4A_basic_column_semantics():

    # --------------------------------------------------------
    # Create Layer 4A folder
    # --------------------------------------------------------
    layer_path = os.path.join(stage0_path, "04A_basic_column_semantics")
    os.makedirs(layer_path, exist_ok=True)

    # --------------------------------------------------------
    # Output files
    # --------------------------------------------------------
    report_txt = os.path.join(layer_path, "layer4A_basic_column_semantics_report.txt")
    semantics_csv = os.path.join(layer_path, "basic_column_semantics.csv")
    dictionary_csv = os.path.join(layer_path, "column_dictionary_draft.csv")
    summary_json = os.path.join(layer_path, "layer4A_basic_column_semantics.json")
    summary_xml = os.path.join(layer_path, "layer4A_basic_column_semantics.xml")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    # --------------------------------------------------------
    # Helper functions
    # --------------------------------------------------------
    def safe_percent(part, total):
        if total == 0:
            return 0
        return round((part / total) * 100, 4)

    def safe_xml_name(name):
        name = str(name)
        name = re.sub(r"[^a-zA-Z0-9_]", "_", name)

        if name == "":
            name = "empty"

        if name[0].isdigit():
            name = "field_" + name

        return name

    def add_xml_node(parent, key, value):
        child = SubElement(parent, safe_xml_name(key))

        if isinstance(value, dict):
            for k, v in value.items():
                add_xml_node(child, k, v)

        elif isinstance(value, list):
            for item in value:
                item_node = SubElement(child, "item")

                if isinstance(item, dict):
                    for k, v in item.items():
                        add_xml_node(item_node, k, v)
                else:
                    item_node.text = "" if item is None else str(item)

        else:
            child.text = "" if value is None else str(value)

    def save_xml(path, root_name, data):
        root = Element(safe_xml_name(root_name))

        for key, value in data.items():
            add_xml_node(root, key, value)

        tree = ElementTree(root)
        tree.write(path, encoding="utf-8", xml_declaration=True)

    def detect_date_column(series, column_name):
        name = str(column_name).lower()

        if "date" in name or "time" in name or "dob" in name:
            return True

        if series.dtype == "object":
            sample = series.dropna().astype(str).head(100)

            if len(sample) == 0:
                return False

            parsed = pd.to_datetime(sample, errors="coerce")
            return parsed.notna().mean() >= 0.60

        return False

    def detect_numeric_stored_as_text(series):
        if series.dtype != "object":
            return False

        sample = series.dropna().astype(str)
        sample = sample.str.replace(",", "", regex=False).head(200)

        if len(sample) == 0:
            return False

        converted = pd.to_numeric(sample, errors="coerce")
        return converted.notna().mean() >= 0.80

    def infer_basic_role(series, column_name):
        total_rows = len(series)
        unique_count = series.nunique(dropna=True)
        unique_ratio = unique_count / total_rows if total_rows > 0 else 0
        name = str(column_name).lower()

        if series.isna().all():
            return "Fully Null Column"

        if unique_count == 1:
            return "Constant Column"

        if "id" in name and unique_ratio >= 0.70:
            return "Possible Identifier Column"

        if detect_date_column(series, column_name):
            return "Date or Time Column"

        if pd.api.types.is_numeric_dtype(series):
            if unique_count <= 2:
                return "Binary Numeric Column"
            return "Numeric Column"

        if detect_numeric_stored_as_text(series):
            return "Numeric Stored as Text"

        if unique_count <= 2:
            return "Binary Categorical Column"

        if series.dtype == "object":
            average_length = series.dropna().astype(str).str.len().mean()

            if unique_count <= 30:
                return "Categorical Column"

            if unique_ratio >= 0.70 and average_length > 20:
                return "Free Text Column"

            return "High Cardinality Categorical Column"

        return "General Column"

    # --------------------------------------------------------
    # Main analysis
    # --------------------------------------------------------
    total_rows = int(df.shape[0])
    total_columns = int(df.shape[1])

    semantic_rows = []
    dictionary_rows = []

    role_counts = {}

    for index, column_name in enumerate(df.columns):
        series = df.iloc[:, index]
        column_name = str(column_name)

        missing_count = int(series.isna().sum())
        missing_percentage = safe_percent(missing_count, total_rows)
        non_missing_count = int(series.notna().sum())
        unique_count = int(series.nunique(dropna=True))
        unique_percentage = safe_percent(unique_count, total_rows)

        basic_role = infer_basic_role(series, column_name)
        role_counts[basic_role] = role_counts.get(basic_role, 0) + 1

        sample_values = " | ".join(series.dropna().astype(str).head(5).tolist())

        semantic_rows.append({
            "column_index": index,
            "column_name": column_name,
            "dtype": str(series.dtype),
            "basic_semantic_role": basic_role,
            "non_missing_count": non_missing_count,
            "missing_count": missing_count,
            "missing_percentage": missing_percentage,
            "unique_values": unique_count,
            "unique_percentage": unique_percentage,
            "sample_values": sample_values
        })

        dictionary_rows.append({
            "column_index": index,
            "column_name": column_name,
            "current_dtype": str(series.dtype),
            "basic_semantic_role": basic_role,
            "meaning_to_be_filled_by_user": "",
            "unit_if_any": "",
            "allowed_values_or_range": "",
            "notes": "Auto-generated draft. User/domain expert must confirm."
        })

    semantics_df = pd.DataFrame(semantic_rows)
    dictionary_df = pd.DataFrame(dictionary_rows)

    semantics_df.to_csv(semantics_csv, index=False)
    dictionary_df.to_csv(dictionary_csv, index=False)

    # --------------------------------------------------------
    # Status and warnings
    # --------------------------------------------------------
    warnings = []

    if "Fully Null Column" in role_counts:
        warnings.append("Fully null columns found.")

    if "Constant Column" in role_counts:
        warnings.append("Constant columns found.")

    if "Numeric Stored as Text" in role_counts:
        warnings.append("Numeric values stored as text found.")

    if "High Cardinality Categorical Column" in role_counts:
        warnings.append("High-cardinality categorical columns found.")

    layer_status = "PASS" if len(warnings) == 0 else "REVIEW_REQUIRED"

    # --------------------------------------------------------
    # JSON summary
    # --------------------------------------------------------
    summary = {
        "stage": "Layer 4A - Basic Column Semantics",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": total_columns,
        "layer_status": layer_status,
        "role_counts": role_counts,
        "warnings": warnings,
        "files_created": {
            "report_txt": report_txt,
            "basic_column_semantics_csv": semantics_csv,
            "column_dictionary_draft_csv": dictionary_csv,
            "summary_json": summary_json,
            "summary_xml": summary_xml
        },
        "next_action": "Run Layer 4B - Target, PII, Leakage and ML Usability Analysis"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False)

    save_xml(summary_xml, "layer4A_basic_column_semantics", summary)

    # --------------------------------------------------------
    # Main TXT report
    # --------------------------------------------------------
    report_text = f"""
LAYER 4A: BASIC COLUMN SEMANTICS REPORT
==================================================

Created On:
{datetime.now()}

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Layer Status:
{layer_status}

Rows:
{total_rows}

Columns:
{total_columns}

Role Counts:
{role_counts}

Warnings:
{warnings}

Files Created:
1. {report_txt}
2. {semantics_csv}
3. {dictionary_csv}
4. {summary_json}
5. {summary_xml}

Meaning:
Layer 4A gives a basic semantic role to each column.

It detects:
1. Numeric columns
2. Categorical columns
3. Binary columns
4. Date or time columns
5. Free text columns
6. Identifier-like columns
7. Fully null columns
8. Constant columns
9. Numeric values stored as text
10. High-cardinality categorical columns

Important:
Layer 4A does not decide target columns, PII risk, leakage risk, or ML usability.
Those deeper checks will be handled in Layer 4B.

Next Action:
Run Layer 4B - Target, PII, Leakage and ML Usability Analysis.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report_text)

    # --------------------------------------------------------
    # Update root purpose file
    # --------------------------------------------------------
    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 4A UPDATE: BASIC COLUMN SEMANTICS
==================================================

Layer 4A completed on:
{datetime.now()}

Layer Status:
{layer_status}

Role Counts:
{role_counts}

Warnings:
{warnings}

Next Required Stage:
Layer 4B should inspect possible target columns, PII fields,
sensitive columns, leakage-risk columns, and feature usability.
""")

    # --------------------------------------------------------
    # Print output
    # --------------------------------------------------------
    print("Layer 4A completed successfully.")
    print("Layer Status:", layer_status)
    print("Role Counts:", role_counts)
    print("Warnings:", warnings)
    print("Files created:")
    print(report_txt)
    print(semantics_csv)
    print(dictionary_csv)
    print(summary_json)
    print(summary_xml)

    display(semantics_df)


# Run Layer 4A
run_layer_4A_basic_column_semantics()

C:\Users\HC\AppData\Local\Temp\ipykernel_15400\3259802488.py:98: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\3259802488.py:98: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\3259802488.py:98: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\3259802488.py:98: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\3259802488.py:98: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\3259802488.py:98: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\3259802488.py:98: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\3259802488.py:98: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\3259802488.py:98: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")

Layer 4A completed successfully.
Layer Status: REVIEW_REQUIRED
Role Counts: {'High Cardinality Categorical Column': 3, 'Numeric Column': 3, 'Binary Categorical Column': 1, 'Categorical Column': 6, 'Date or Time Column': 2}
Warnings: ['High-cardinality categorical columns found.']
Files created:
d:\Med_data\stage0-launch-pad\04A_basic_column_semantics\layer4A_basic_column_semantics_report.txt
d:\Med_data\stage0-launch-pad\04A_basic_column_semantics\basic_column_semantics.csv
d:\Med_data\stage0-launch-pad\04A_basic_column_semantics\column_dictionary_draft.csv
d:\Med_data\stage0-launch-pad\04A_basic_column_semantics\layer4A_basic_column_semantics.json
d:\Med_data\stage0-launch-pad\04A_basic_column_semantics\layer4A_basic_column_semantics.xml

C:\Users\HC\AppData\Local\Temp\ipykernel_15400\3259802488.py:98: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")

,column_index,column_name,dtype,basic_semantic_role,non_missing_count,missing_count,missing_percentage,unique_values,unique_percentage,sample_values
0,0,Name,object,High Cardinality Categorical Column,55500,0,0.0,49992,90.0757,Bobby JacksOn | LesLie TErRy | DaNnY sMitH | a...
1,1,Age,int64,Numeric Column,55500,0,0.0,77,0.1387,30 | 62 | 76 | 28 | 43
2,2,Gender,object,Binary Categorical Column,55500,0,0.0,2,0.0036,Male | Male | Female | Female | Female
3,3,Blood Type,object,Categorical Column,55500,0,0.0,8,0.0144,B- | A+ | A- | O+ | AB+
4,4,Medical Condition,object,Categorical Column,55500,0,0.0,6,0.0108,Cancer | Obesity | Obesity | Diabetes | Cancer
5,5,Date of Admission,object,Date or Time Column,55500,0,0.0,1827,3.2919,2024-01-31 | 2019-08-20 | 2022-09-22 | 2020-11...
6,6,Doctor,object,High Cardinality Categorical Column,55500,0,0.0,40341,72.6865,Matthew Smith | Samantha Davies | Tiffany Mitc...
7,7,Hospital,object,High Cardinality Categorical Column,55500,0,0.0,39876,71.8486,Sons and Miller | Kim Inc | Cook PLC | Hernand...
8,8,Insurance Provider,object,Categorical Column,55500,0,0.0,5,0.0090,Blue Cross | Medicare | Aetna | Medicare | Aetna
9,9,Billing Amount,float64,Numeric Column,55500,0,0.0,50000,90.0901,18856.281305978155 | 33643.327286577885 | 2795...
10,10,Room Number,int64,Numeric Column,55500,0,0.0,400,0.7207,328 | 265 | 205 | 450 | 458
11,11,Admission Type,object,Categorical Column,55500,0,0.0,3,0.0054,Urgent | Emergency | Emergency | Elective | Ur...
12,12,Discharge Date,object,Date or Time Column,55500,0,0.0,1856,3.3441,2024-02-02 | 2019-08-26 | 2022-10-07 | 2020-12...
13,13,Medication,object,Categorical Column,55500,0,0.0,5,0.0090,Paracetamol | Ibuprofen | Aspirin | Ibuprofen ...
14,14,Test Results,object,Categorical Column,55500,0,0.0,3,0.0054,Normal | Inconclusive | Normal | Abnormal | Ab...

In [37]:
# ============================================================
# LAYER 4B: TARGET, PII, LEAKAGE, FEATURE USABILITY & ML READINESS
# Run after Layer 4A
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import re
import json
import pandas as pd
import numpy as np
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, ElementTree
from IPython.display import display


def run_layer_4B_target_pii_leakage_ml_usability():

    # --------------------------------------------------------
    # Create Layer 4B folder
    # --------------------------------------------------------
    layer_path = os.path.join(stage0_path, "04B_target_pii_leakage_ml_usability")
    os.makedirs(layer_path, exist_ok=True)

    # --------------------------------------------------------
    # Output files
    # --------------------------------------------------------
    report_txt = os.path.join(layer_path, "layer4B_target_pii_leakage_ml_usability_report.txt")
    target_csv = os.path.join(layer_path, "target_candidate_report.csv")
    pii_csv = os.path.join(layer_path, "pii_sensitive_scan.csv")
    leakage_csv = os.path.join(layer_path, "leakage_risk_report.csv")
    feature_csv = os.path.join(layer_path, "feature_usability_report.csv")
    ml_possibility_txt = os.path.join(layer_path, "ml_problem_possibility_report.txt")
    recommendations_txt = os.path.join(layer_path, "layer4B_recommendations.txt")
    summary_json = os.path.join(layer_path, "layer4B_summary.json")
    summary_xml = os.path.join(layer_path, "layer4B_summary.xml")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    # --------------------------------------------------------
    # Helper functions
    # --------------------------------------------------------
    def safe_percent(part, total):
        if total == 0:
            return 0
        return round((part / total) * 100, 4)

    def safe_xml_name(name):
        name = str(name)
        name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        if name == "":
            name = "empty"
        if name[0].isdigit():
            name = "field_" + name
        return name

    def add_xml_node(parent, key, value):
        child = SubElement(parent, safe_xml_name(key))

        if isinstance(value, dict):
            for k, v in value.items():
                add_xml_node(child, k, v)

        elif isinstance(value, list):
            for item in value:
                item_node = SubElement(child, "item")
                if isinstance(item, dict):
                    for k, v in item.items():
                        add_xml_node(item_node, k, v)
                else:
                    item_node.text = "" if item is None else str(item)

        else:
            child.text = "" if value is None else str(value)

    def save_xml(path, root_name, data):
        root = Element(safe_xml_name(root_name))
        for key, value in data.items():
            add_xml_node(root, key, value)
        tree = ElementTree(root)
        tree.write(path, encoding="utf-8", xml_declaration=True)

    def detect_pii_column(column_name):
        name = str(column_name).lower().strip()

        pii_keywords = [
            "first_name", "last_name", "full_name", "patient_name",
            "student_name", "customer_name", "employee_name",
            "email", "phone", "mobile", "contact", "address",
            "cnic", "passport", "ssn", "national_id",
            "patient_id", "student_id", "customer_id", "employee_id",
            "account_number", "iban", "credit_card", "card_number"
        ]

        if any(keyword in name for keyword in pii_keywords):
            return True

        # Safer ID check: avoid false positives like "admission"
        words = re.split(r"[^a-zA-Z0-9]+", name)
        if "id" in words or name.endswith("_id") or name.endswith(" id"):
            return True

        return False

    def detect_sensitive_column(column_name):
        name = str(column_name).lower().strip()

        sensitive_keywords = [
            "age", "gender", "sex", "dob", "birth",
            "blood", "medical condition", "condition", "diagnosis",
            "disease", "medication", "test result", "test_results",
            "salary", "income", "religion", "race", "ethnicity"
        ]

        return any(keyword in name for keyword in sensitive_keywords)

    def detect_leakage_column(column_name):
        name = str(column_name).lower().strip()

        leakage_keywords = [
            "result", "outcome", "label", "target",
            "final", "discharge", "diagnosis",
            "approved", "rejected", "status",
            "billing", "bill", "charges", "payment"
        ]

        return any(keyword in name for keyword in leakage_keywords)

    def detect_date_column(series, column_name):
        name = str(column_name).lower()

        if "date" in name or "time" in name or "dob" in name:
            return True

        if series.dtype == "object":
            sample = series.dropna().astype(str).head(100)
            if len(sample) == 0:
                return False
            parsed = pd.to_datetime(sample, errors="coerce")
            return parsed.notna().mean() >= 0.60

        return False

    def estimate_feature_usability(series, column_name):
        total_rows = len(series)
        missing_pct = safe_percent(series.isna().sum(), total_rows)
        unique_count = int(series.nunique(dropna=True))
        unique_ratio = unique_count / total_rows if total_rows > 0 else 0

        score = 100
        reasons = []

        if series.isna().all():
            return "Do Not Use", 0, "fully null column"

        if unique_count <= 1:
            return "Do Not Use", 5, "constant column"

        if detect_pii_column(column_name):
            score -= 70
            reasons.append("PII or identifier risk")

        if missing_pct >= 80:
            score -= 50
            reasons.append("very high missing values")

        elif missing_pct >= 40:
            score -= 25
            reasons.append("high missing values")

        if unique_ratio >= 0.95 and series.dtype == "object":
            score -= 25
            reasons.append("very high cardinality")

        if detect_leakage_column(column_name):
            score -= 40
            reasons.append("possible leakage-risk column")

        score = max(0, min(100, round(score, 2)))

        if score >= 75:
            usability = "Good Candidate Feature"
        elif score >= 40:
            usability = "Use With Review"
        elif score > 0:
            usability = "Weak or Risky Feature"
        else:
            usability = "Do Not Use"

        if len(reasons) == 0:
            reasons.append("no major automatic usability issue detected")

        return usability, score, "; ".join(reasons)

    def estimate_target_candidate(series, column_name):
        total_rows = len(series)
        missing_pct = safe_percent(series.isna().sum(), total_rows)
        unique_count = int(series.nunique(dropna=True))
        name = str(column_name).lower().strip()

        score = 0
        reasons = []

        if series.isna().all():
            return -10, "Not Suitable", "fully null column"

        if unique_count <= 1:
            return -10, "Not Suitable", "constant column"

        if missing_pct < 30:
            score += 2
            reasons.append("acceptable missing percentage")

        if 2 <= unique_count <= 30:
            score += 3
            reasons.append("classification target possible")

        if pd.api.types.is_numeric_dtype(series) and unique_count > 30:
            score += 2
            reasons.append("regression target possible")

        target_keywords = [
            "target", "label", "class", "result",
            "outcome", "condition", "diagnosis",
            "status", "risk", "score"
        ]

        if any(keyword in name for keyword in target_keywords):
            score += 4
            reasons.append("target-like column name")

        if detect_pii_column(column_name):
            score -= 8
            reasons.append("PII/identifier is not suitable as target")

        if missing_pct >= 40:
            score -= 3
            reasons.append("high missing percentage")

        if 2 <= unique_count <= 30:
            ml_type = "Classification"
        elif pd.api.types.is_numeric_dtype(series) and unique_count > 30:
            ml_type = "Regression"
        else:
            ml_type = "Needs Review"

        return score, ml_type, "; ".join(reasons)

    # --------------------------------------------------------
    # Main analysis
    # --------------------------------------------------------
    total_rows = int(df.shape[0])
    total_columns = int(df.shape[1])

    target_rows = []
    pii_rows = []
    leakage_rows = []
    feature_rows = []

    possible_target_columns = []
    possible_pii_columns = []
    possible_sensitive_columns = []
    possible_leakage_columns = []
    good_feature_columns = []
    review_feature_columns = []
    weak_feature_columns = []

    for index, column_name in enumerate(df.columns):
        series = df.iloc[:, index]
        column_name = str(column_name)

        missing_count = int(series.isna().sum())
        missing_pct = safe_percent(missing_count, total_rows)
        unique_count = int(series.nunique(dropna=True))

        is_pii = detect_pii_column(column_name)
        is_sensitive = detect_sensitive_column(column_name)
        is_leakage = detect_leakage_column(column_name)
        is_date = detect_date_column(series, column_name)

        if is_pii:
            possible_pii_columns.append(column_name)

        if is_sensitive:
            possible_sensitive_columns.append(column_name)

        if is_leakage:
            possible_leakage_columns.append(column_name)

        t_score, ml_type, t_reason = estimate_target_candidate(series, column_name)

        if t_score >= 5:
            possible_target_columns.append(column_name)

        usability, usability_score, usability_reason = estimate_feature_usability(series, column_name)

        if usability == "Good Candidate Feature":
            good_feature_columns.append(column_name)
        elif usability == "Use With Review":
            review_feature_columns.append(column_name)
        else:
            weak_feature_columns.append(column_name)

        target_rows.append({
            "column_index": index,
            "column_name": column_name,
            "target_score": t_score,
            "possible_ml_type": ml_type,
            "missing_percentage": missing_pct,
            "unique_values": unique_count,
            "reason": t_reason
        })

        pii_rows.append({
            "column_index": index,
            "column_name": column_name,
            "possible_pii": is_pii,
            "possible_sensitive": is_sensitive,
            "manual_review_required": bool(is_pii or is_sensitive)
        })

        leakage_rows.append({
            "column_index": index,
            "column_name": column_name,
            "possible_leakage": is_leakage,
            "warning": "Review before using as input feature" if is_leakage else ""
        })

        feature_rows.append({
            "column_index": index,
            "column_name": column_name,
            "dtype": str(series.dtype),
            "missing_percentage": missing_pct,
            "unique_values": unique_count,
            "possible_date": is_date,
            "feature_usability": usability,
            "feature_usability_score": usability_score,
            "reason": usability_reason
        })

    target_df = pd.DataFrame(target_rows).sort_values(by="target_score", ascending=False)
    pii_df = pd.DataFrame(pii_rows)
    leakage_df = pd.DataFrame(leakage_rows)
    feature_df = pd.DataFrame(feature_rows).sort_values(by="feature_usability_score", ascending=False)

    target_df.to_csv(target_csv, index=False)
    pii_df.to_csv(pii_csv, index=False)
    leakage_df.to_csv(leakage_csv, index=False)
    feature_df.to_csv(feature_csv, index=False)

    # --------------------------------------------------------
    # ML possibility summary
    # --------------------------------------------------------
    ml_possibilities = []

    if len(possible_target_columns) > 0:
        ml_possibilities.append("Supervised learning may be possible after target confirmation.")

    if any(row["possible_ml_type"] == "Classification" and row["target_score"] >= 5 for row in target_rows):
        ml_possibilities.append("Classification problems may be possible.")

    if any(row["possible_ml_type"] == "Regression" and row["target_score"] >= 5 for row in target_rows):
        ml_possibilities.append("Regression problems may be possible.")

    numeric_columns_count = len(df.select_dtypes(include=["number"]).columns)
    if numeric_columns_count >= 2:
        ml_possibilities.append("Clustering or anomaly detection may be possible.")

    if any(detect_date_column(df.iloc[:, i], col) for i, col in enumerate(df.columns)):
        ml_possibilities.append("Time-based feature engineering may be possible.")

    if len(ml_possibilities) == 0:
        ml_possibilities.append("No strong ML direction detected automatically. Metadata and target confirmation are required.")

    ml_text = f"""
ML PROBLEM POSSIBILITY REPORT
==================================================

Created On:
{datetime.now()}

Possible Target Columns:
{possible_target_columns}

Possible ML Directions:
{ml_possibilities}

Important:
These are automatic suggestions only.
The real ML objective must be confirmed by user/domain expert.

Do Not Start ML Until:
1. Target column is confirmed.
2. PII columns are reviewed.
3. Leakage-risk columns are reviewed.
4. Metadata questions are answered.
5. Data quality issues from Layer 3 are reviewed.
"""

    with open(ml_possibility_txt, "w", encoding="utf-8") as f:
        f.write(ml_text)

    # --------------------------------------------------------
    # Warnings and recommendations
    # --------------------------------------------------------
    warnings = []

    if len(possible_target_columns) == 0:
        warnings.append("No strong target column detected automatically.")

    if len(possible_pii_columns) > 0:
        warnings.append("Possible PII columns detected.")

    if len(possible_sensitive_columns) > 0:
        warnings.append("Possible sensitive columns detected.")

    if len(possible_leakage_columns) > 0:
        warnings.append("Possible leakage-risk columns detected.")

    if len(weak_feature_columns) > 0:
        warnings.append("Some weak or risky features detected.")

    layer_status = "PASS" if len(warnings) == 0 else "REVIEW_REQUIRED"

    recommendations = [
        "Confirm the real target column before ML.",
        "Do not use PII columns as features unless anonymized and approved.",
        "Review sensitive columns for ethical and legal concerns.",
        "Review leakage-risk columns before using them as input features.",
        "Use Good Candidate Feature columns first for early baseline modeling.",
        "Use Review Feature columns only after human inspection.",
        "Avoid Weak or Risky Feature columns unless there is a strong reason.",
        "Read Layer 3 data quality report before ML."
    ]

    rec_text = "LAYER 4B RECOMMENDATIONS\n"
    rec_text += "=" * 50 + "\n\n"

    for i, rec in enumerate(recommendations, start=1):
        rec_text += f"{i}. {rec}\n"

    with open(recommendations_txt, "w", encoding="utf-8") as f:
        f.write(rec_text)

    # --------------------------------------------------------
    # JSON and XML summary
    # --------------------------------------------------------
    summary = {
        "stage": "Layer 4B - Target, PII, Leakage and ML Usability",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": total_columns,
        "layer_status": layer_status,
        "possible_target_columns": possible_target_columns,
        "possible_pii_columns": possible_pii_columns,
        "possible_sensitive_columns": possible_sensitive_columns,
        "possible_leakage_columns": possible_leakage_columns,
        "good_feature_columns": good_feature_columns,
        "review_feature_columns": review_feature_columns,
        "weak_or_risky_feature_columns": weak_feature_columns,
        "possible_ml_directions": ml_possibilities,
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "report_txt": report_txt,
            "target_candidate_report": target_csv,
            "pii_sensitive_scan": pii_csv,
            "leakage_risk_report": leakage_csv,
            "feature_usability_report": feature_csv,
            "ml_problem_possibility_report": ml_possibility_txt,
            "recommendations_txt": recommendations_txt,
            "summary_json": summary_json,
            "summary_xml": summary_xml
        },
        "next_action": "Run Layer 5 - Statistical Profile"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False)

    save_xml(summary_xml, "layer4B_summary", summary)

    # --------------------------------------------------------
    # Main TXT report
    # --------------------------------------------------------
    report_text = f"""
LAYER 4B: TARGET, PII, LEAKAGE AND ML USABILITY REPORT
==================================================

Created On:
{datetime.now()}

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Layer Status:
{layer_status}

Rows:
{total_rows}

Columns:
{total_columns}

Possible Target Columns:
{possible_target_columns}

Possible PII Columns:
{possible_pii_columns}

Possible Sensitive Columns:
{possible_sensitive_columns}

Possible Leakage-Risk Columns:
{possible_leakage_columns}

Good Candidate Feature Columns:
{good_feature_columns}

Review Feature Columns:
{review_feature_columns}

Weak or Risky Feature Columns:
{weak_feature_columns}

Possible ML Directions:
{ml_possibilities}

Warnings:
{warnings}

Files Created:
1. {report_txt}
2. {target_csv}
3. {pii_csv}
4. {leakage_csv}
5. {feature_csv}
6. {ml_possibility_txt}
7. {recommendations_txt}
8. {summary_json}
9. {summary_xml}

Meaning:
Layer 4B checks possible ML target columns, PII/sensitive columns,
leakage-risk columns, feature usability, and possible ML problem directions.

Important:
This layer gives automatic suggestions only.
User/domain expert confirmation is required before ML.

Next Action:
Run Layer 5 - Statistical Profile.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report_text)

    # --------------------------------------------------------
    # Update root purpose file
    # --------------------------------------------------------
    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 4B UPDATE: TARGET, PII, LEAKAGE AND ML USABILITY
==================================================

Layer 4B completed on:
{datetime.now()}

Layer Status:
{layer_status}

Possible Target Columns:
{possible_target_columns}

Possible PII Columns:
{possible_pii_columns}

Possible Sensitive Columns:
{possible_sensitive_columns}

Possible Leakage-Risk Columns:
{possible_leakage_columns}

Possible ML Directions:
{ml_possibilities}

Warnings:
{warnings}

Next Required Stage:
Layer 5 should generate statistical profile, numeric summary,
categorical summary, correlation report, and outlier scan.
""")

    # --------------------------------------------------------
    # Print output
    # --------------------------------------------------------
    print("Layer 4B completed successfully.")
    print("Layer Status:", layer_status)
    print("Possible Target Columns:", possible_target_columns)
    print("Possible PII Columns:", possible_pii_columns)
    print("Possible Sensitive Columns:", possible_sensitive_columns)
    print("Possible Leakage-Risk Columns:", possible_leakage_columns)
    print("Possible ML Directions:", ml_possibilities)
    print("Files created:")
    print(report_txt)
    print(target_csv)
    print(pii_csv)
    print(leakage_csv)
    print(feature_csv)
    print(ml_possibility_txt)
    print(recommendations_txt)
    print(summary_json)
    print(summary_xml)

    display(target_df.head(10))
    display(feature_df.head(10))
    display(pii_df)
    display(leakage_df)


# Run Layer 4B
run_layer_4B_target_pii_leakage_ml_usability()

C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")

Layer 4B completed successfully.
Layer Status: REVIEW_REQUIRED
Possible Target Columns: ['Gender', 'Blood Type', 'Medical Condition', 'Insurance Provider', 'Admission Type', 'Medication', 'Test Results']
Possible PII Columns: []
Possible Sensitive Columns: ['Age', 'Gender', 'Blood Type', 'Medical Condition', 'Medication', 'Test Results']
Possible Leakage-Risk Columns: ['Billing Amount', 'Discharge Date', 'Test Results']
Possible ML Directions: ['Supervised learning may be possible after target confirmation.', 'Classification problems may be possible.', 'Clustering or anomaly detection may be possible.', 'Time-based feature engineering may be possible.']
Files created:
d:\Med_data\stage0-launch-pad\04B_target_pii_leakage_ml_usability\layer4B_target_pii_leakage_ml_usability_report.txt
d:\Med_data\stage0-launch-pad\04B_target_pii_leakage_ml_usability\target_candidate_report.csv
d:\Med_data\stage0-launch-pad\04B_target_pii_leakage_ml_usability\pii_sensitive_scan.csv
d:\Med_data\stage0-launch-pad\04B_target_pii_leakage_ml_usability\leakage_risk_report.csv
d:\Med_data\stage0-launch-pad\04B_target_pii_leakage_ml_usability\feature_usability_report.csv
d:\Med_data\stage0-launch-pad\04B_target_pii_leakage_ml_usability\ml_problem_possibility_report.txt
d:\Med_data\stage0-launch-pad\04B_target_pii_leakage_ml_usability\layer4B_recommendations.txt
d:\Med_data\stage0-launch-pad\04B_target_pii_leakage_ml_usability\layer4B_summary.json
d:\Med_data\stage0-launch-pad\04B_target_pii_leakage_ml_usability\layer4B_summary.xml

C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")
C:\Users\HC\AppData\Local\Temp\ipykernel_15400\600652832.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(sample, errors="coerce")

,column_index,column_name,target_score,possible_ml_type,missing_percentage,unique_values,reason
4,4,Medical Condition,9,Classification,0.0,6,acceptable missing percentage; classification ...
14,14,Test Results,9,Classification,0.0,3,acceptable missing percentage; classification ...
2,2,Gender,5,Classification,0.0,2,acceptable missing percentage; classification ...
3,3,Blood Type,5,Classification,0.0,8,acceptable missing percentage; classification ...
8,8,Insurance Provider,5,Classification,0.0,5,acceptable missing percentage; classification ...
11,11,Admission Type,5,Classification,0.0,3,acceptable missing percentage; classification ...
13,13,Medication,5,Classification,0.0,5,acceptable missing percentage; classification ...
1,1,Age,4,Regression,0.0,77,acceptable missing percentage; regression targ...
9,9,Billing Amount,4,Regression,0.0,50000,acceptable missing percentage; regression targ...
10,10,Room Number,4,Regression,0.0,400,acceptable missing percentage; regression targ...

,column_index,column_name,dtype,missing_percentage,unique_values,possible_date,feature_usability,feature_usability_score,reason
0,0,Name,object,0.0,49992,False,Good Candidate Feature,100,no major automatic usability issue detected
1,1,Age,int64,0.0,77,False,Good Candidate Feature,100,no major automatic usability issue detected
2,2,Gender,object,0.0,2,False,Good Candidate Feature,100,no major automatic usability issue detected
3,3,Blood Type,object,0.0,8,False,Good Candidate Feature,100,no major automatic usability issue detected
4,4,Medical Condition,object,0.0,6,False,Good Candidate Feature,100,no major automatic usability issue detected
5,5,Date of Admission,object,0.0,1827,True,Good Candidate Feature,100,no major automatic usability issue detected
6,6,Doctor,object,0.0,40341,False,Good Candidate Feature,100,no major automatic usability issue detected
7,7,Hospital,object,0.0,39876,False,Good Candidate Feature,100,no major automatic usability issue detected
8,8,Insurance Provider,object,0.0,5,False,Good Candidate Feature,100,no major automatic usability issue detected
10,10,Room Number,int64,0.0,400,False,Good Candidate Feature,100,no major automatic usability issue detected

,column_index,column_name,possible_pii,possible_sensitive,manual_review_required
0,0,Name,False,False,False
1,1,Age,False,True,True
2,2,Gender,False,True,True
3,3,Blood Type,False,True,True
4,4,Medical Condition,False,True,True
5,5,Date of Admission,False,False,False
6,6,Doctor,False,False,False
7,7,Hospital,False,False,False
8,8,Insurance Provider,False,False,False
9,9,Billing Amount,False,False,False
10,10,Room Number,False,False,False
11,11,Admission Type,False,False,False
12,12,Discharge Date,False,False,False
13,13,Medication,False,True,True
14,14,Test Results,False,True,True

,column_index,column_name,possible_leakage,warning
0,0,Name,False,
1,1,Age,False,
2,2,Gender,False,
3,3,Blood Type,False,
4,4,Medical Condition,False,
5,5,Date of Admission,False,
6,6,Doctor,False,
7,7,Hospital,False,
8,8,Insurance Provider,False,
9,9,Billing Amount,True,Review before using as input feature
10,10,Room Number,False,
11,11,Admission Type,False,
12,12,Discharge Date,True,Review before using as input feature
13,13,Medication,False,
14,14,Test Results,True,Review before using as input feature

In [39]:
# ============================================================
# LAYER 5: NUMERIC BASIC STATISTICS
# Run after Layer 4
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, ElementTree
from IPython.display import display


def run_layer_5_numeric_basic_statistics():

    # --------------------------------------------------------
    # Create Layer 5 folder
    # --------------------------------------------------------
    layer_path = os.path.join(stage0_path, "05_numeric_basic_statistics")
    os.makedirs(layer_path, exist_ok=True)

    # --------------------------------------------------------
    # Output files
    # --------------------------------------------------------
    report_txt = os.path.join(layer_path, "layer5_numeric_basic_statistics_report.txt")
    numeric_stats_csv = os.path.join(layer_path, "numeric_basic_statistics.csv")
    summary_json = os.path.join(layer_path, "layer5_numeric_basic_statistics.json")
    summary_xml = os.path.join(layer_path, "layer5_numeric_basic_statistics.xml")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    # --------------------------------------------------------
    # Helper
    # --------------------------------------------------------
    def safe_percent(part, total):
        if total == 0:
            return 0
        return round((part / total) * 100, 4)

    # --------------------------------------------------------
    # Select numeric columns
    # --------------------------------------------------------
    total_rows = int(df.shape[0])
    total_columns = int(df.shape[1])

    numeric_df = df.select_dtypes(include=["number"])
    numeric_columns = list(numeric_df.columns)

    numeric_rows = []

    for col in numeric_columns:
        series = numeric_df[col]
        clean_series = series.dropna()

        if len(clean_series) > 0:
            numeric_rows.append({
                "column_name": str(col),
                "dtype": str(series.dtype),
                "count": int(clean_series.count()),
                "missing_count": int(series.isna().sum()),
                "missing_percentage": safe_percent(series.isna().sum(), total_rows),
                "unique_values": int(series.nunique(dropna=True)),
                "mean": round(float(clean_series.mean()), 6),
                "median": round(float(clean_series.median()), 6),
                "standard_deviation": round(float(clean_series.std()), 6) if len(clean_series) > 1 else 0,
                "minimum": round(float(clean_series.min()), 6),
                "q1_25_percent": round(float(clean_series.quantile(0.25)), 6),
                "q2_50_percent": round(float(clean_series.quantile(0.50)), 6),
                "q3_75_percent": round(float(clean_series.quantile(0.75)), 6),
                "maximum": round(float(clean_series.max()), 6)
            })

    numeric_stats_df = pd.DataFrame(numeric_rows)

    if numeric_stats_df.empty:
        numeric_stats_df = pd.DataFrame({
            "message": ["No numeric columns found in this dataset."]
        })

    numeric_stats_df.to_csv(numeric_stats_csv, index=False)

    # --------------------------------------------------------
    # Status, warnings, strengths
    # --------------------------------------------------------
    strengths = []
    warnings = []

    if len(numeric_columns) > 0:
        strengths.append("Numeric columns are available for statistical analysis.")
    else:
        warnings.append("No numeric columns found.")

    if total_rows >= 1000:
        strengths.append("Dataset has enough rows for basic numeric summary.")
    else:
        warnings.append("Dataset has small row count; numeric summary may be less stable.")

    layer_status = "PASS" if len(warnings) == 0 else "REVIEW_RECOMMENDED"

    # --------------------------------------------------------
    # JSON summary
    # --------------------------------------------------------
    summary = {
        "stage": "Layer 5 - Numeric Basic Statistics",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": total_columns,
        "numeric_columns_count": len(numeric_columns),
        "numeric_columns": [str(col) for col in numeric_columns],
        "layer_status": layer_status,
        "strengths": strengths,
        "warnings": warnings,
        "files_created": {
            "report_txt": report_txt,
            "numeric_stats_csv": numeric_stats_csv,
            "summary_json": summary_json,
            "summary_xml": summary_xml
        },
        "next_action": "Run Layer 6 - Categorical Basic Statistics"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False)

    # --------------------------------------------------------
    # XML summary
    # --------------------------------------------------------
    root = Element("layer5_numeric_basic_statistics")

    for key, value in summary.items():
        node = SubElement(root, key)

        if isinstance(value, list):
            for item in value:
                item_node = SubElement(node, "item")
                item_node.text = str(item)

        elif isinstance(value, dict):
            for k, v in value.items():
                child = SubElement(node, str(k))
                child.text = str(v)

        else:
            node.text = str(value)

    tree = ElementTree(root)
    tree.write(summary_xml, encoding="utf-8", xml_declaration=True)

    # --------------------------------------------------------
    # TXT report
    # --------------------------------------------------------
    report_text = f"""
LAYER 5: NUMERIC BASIC STATISTICS REPORT
==================================================

Created On:
{datetime.now()}

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Layer Status:
{layer_status}

Rows:
{total_rows}

Columns:
{total_columns}

Numeric Columns Count:
{len(numeric_columns)}

Numeric Columns:
{[str(col) for col in numeric_columns]}

Strengths:
{strengths}

Warnings:
{warnings}

Files Created:
1. {report_txt}
2. {numeric_stats_csv}
3. {summary_json}
4. {summary_xml}

Meaning:
Layer 5 creates basic descriptive statistics for numeric columns.

It includes:
1. Count
2. Missing values
3. Unique values
4. Mean
5. Median
6. Standard deviation
7. Minimum
8. Quartiles
9. Maximum

Important:
This layer does not check correlation, outliers, skewness, or categorical values.
Those will be handled in later smaller layers.

Next Action:
Run Layer 6 - Categorical Basic Statistics.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report_text)

    # --------------------------------------------------------
    # Update root purpose file
    # --------------------------------------------------------
    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 5 UPDATE: NUMERIC BASIC STATISTICS
==================================================

Layer 5 completed on:
{datetime.now()}

Layer Status:
{layer_status}

Numeric Columns Count:
{len(numeric_columns)}

Numeric Columns:
{[str(col) for col in numeric_columns]}

Warnings:
{warnings}

Next Required Stage:
Layer 6 should generate categorical basic statistics.
""")

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------
    print("Layer 5 completed successfully.")
    print("Layer Status:", layer_status)
    print("Numeric Columns Count:", len(numeric_columns))
    print("Files created:")
    print(report_txt)
    print(numeric_stats_csv)
    print(summary_json)
    print(summary_xml)

    display(numeric_stats_df)


# Run Layer 5
run_layer_5_numeric_basic_statistics()

Layer 5 completed successfully.
Layer Status: PASS
Numeric Columns Count: 3
Files created:
d:\Med_data\stage0-launch-pad\05_numeric_basic_statistics\layer5_numeric_basic_statistics_report.txt
d:\Med_data\stage0-launch-pad\05_numeric_basic_statistics\numeric_basic_statistics.csv
d:\Med_data\stage0-launch-pad\05_numeric_basic_statistics\layer5_numeric_basic_statistics.json
d:\Med_data\stage0-launch-pad\05_numeric_basic_statistics\layer5_numeric_basic_statistics.xml

,column_name,dtype,count,missing_count,missing_percentage,unique_values,mean,median,standard_deviation,minimum,q1_25_percent,q2_50_percent,q3_75_percent,maximum
0,Age,int64,55500,0,0.0,77,51.539459,52.000000,19.602454,13.00000,35.000000,52.000000,68.000000,89.000000
1,Billing Amount,float64,55500,0,0.0,50000,25539.316097,25538.069376,14211.454431,-2008.49214,13241.224652,25538.069376,37820.508436,52764.276736
2,Room Number,int64,55500,0,0.0,400,301.134829,302.000000,115.243069,101.00000,202.000000,302.000000,401.000000,500.000000

In [41]:
# ============================================================
# LAYER 6: CATEGORICAL BASIC STATISTICS
# Run after Layer 5
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, ElementTree
from IPython.display import display


def run_layer_6_categorical_basic_statistics():

    # --------------------------------------------------------
    # Create Layer 6 folder
    # --------------------------------------------------------
    layer_path = os.path.join(stage0_path, "06_categorical_basic_statistics")
    os.makedirs(layer_path, exist_ok=True)

    # --------------------------------------------------------
    # Output files
    # --------------------------------------------------------
    report_txt = os.path.join(layer_path, "layer6_categorical_basic_statistics_report.txt")
    categorical_stats_csv = os.path.join(layer_path, "categorical_basic_statistics.csv")
    top_values_csv = os.path.join(layer_path, "categorical_top_values.csv")
    summary_json = os.path.join(layer_path, "layer6_categorical_basic_statistics.json")
    summary_xml = os.path.join(layer_path, "layer6_categorical_basic_statistics.xml")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    # --------------------------------------------------------
    # Helper
    # --------------------------------------------------------
    def safe_percent(part, total):
        if total == 0:
            return 0
        return round((part / total) * 100, 4)

    # --------------------------------------------------------
    # Select categorical/text columns
    # --------------------------------------------------------
    total_rows = int(df.shape[0])
    total_columns = int(df.shape[1])

    categorical_df = df.select_dtypes(include=["object", "category", "bool"])
    categorical_columns = list(categorical_df.columns)

    categorical_rows = []
    top_value_rows = []

    for col in categorical_columns:
        series = categorical_df[col]
        clean_series = series.dropna()

        unique_count = int(series.nunique(dropna=True))
        missing_count = int(series.isna().sum())

        if len(clean_series) > 0:
            mode_values = clean_series.mode()
            top_value = mode_values.iloc[0] if not mode_values.empty else None
            top_count = int((series == top_value).sum()) if top_value is not None else 0
            sample_values = " | ".join(clean_series.astype(str).head(5).tolist())
        else:
            top_value = None
            top_count = 0
            sample_values = ""

        categorical_rows.append({
            "column_name": str(col),
            "dtype": str(series.dtype),
            "count": int(clean_series.count()),
            "missing_count": missing_count,
            "missing_percentage": safe_percent(missing_count, total_rows),
            "unique_values": unique_count,
            "top_value": top_value,
            "top_value_count": top_count,
            "top_value_percentage": safe_percent(top_count, total_rows),
            "sample_values": sample_values,
            "is_low_cardinality": bool(2 <= unique_count <= 20),
            "is_high_cardinality": bool(unique_count > 50),
            "is_constant": bool(unique_count <= 1)
        })

        value_counts = series.value_counts(dropna=True).head(10)

        for value, count in value_counts.items():
            top_value_rows.append({
                "column_name": str(col),
                "value": str(value),
                "count": int(count),
                "percentage": safe_percent(count, total_rows)
            })

    categorical_stats_df = pd.DataFrame(categorical_rows)
    top_values_df = pd.DataFrame(top_value_rows)

    if categorical_stats_df.empty:
        categorical_stats_df = pd.DataFrame({
            "message": ["No categorical/text columns found in this dataset."]
        })

    if top_values_df.empty:
        top_values_df = pd.DataFrame({
            "message": ["No categorical top values available."]
        })

    categorical_stats_df.to_csv(categorical_stats_csv, index=False)
    top_values_df.to_csv(top_values_csv, index=False)

    # --------------------------------------------------------
    # Status, strengths, warnings
    # --------------------------------------------------------
    strengths = []
    warnings = []

    if len(categorical_columns) > 0:
        strengths.append("Categorical/text columns are available for frequency analysis.")
    else:
        warnings.append("No categorical/text columns found.")

    low_cardinality_columns = []
    high_cardinality_columns = []
    constant_columns = []

    if "is_low_cardinality" in categorical_stats_df.columns:
        low_cardinality_columns = categorical_stats_df[
            categorical_stats_df["is_low_cardinality"] == True
        ]["column_name"].tolist()

    if "is_high_cardinality" in categorical_stats_df.columns:
        high_cardinality_columns = categorical_stats_df[
            categorical_stats_df["is_high_cardinality"] == True
        ]["column_name"].tolist()

    if "is_constant" in categorical_stats_df.columns:
        constant_columns = categorical_stats_df[
            categorical_stats_df["is_constant"] == True
        ]["column_name"].tolist()

    if len(low_cardinality_columns) > 0:
        strengths.append("Low-cardinality categorical columns may support classification or grouping.")

    if len(high_cardinality_columns) > 0:
        warnings.append("High-cardinality categorical/text columns found.")

    if len(constant_columns) > 0:
        warnings.append("Constant categorical columns found.")

    layer_status = "PASS" if len(warnings) == 0 else "REVIEW_RECOMMENDED"

    # --------------------------------------------------------
    # JSON summary
    # --------------------------------------------------------
    summary = {
        "stage": "Layer 6 - Categorical Basic Statistics",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": total_columns,
        "categorical_columns_count": len(categorical_columns),
        "categorical_columns": [str(col) for col in categorical_columns],
        "low_cardinality_columns": low_cardinality_columns,
        "high_cardinality_columns": high_cardinality_columns,
        "constant_categorical_columns": constant_columns,
        "layer_status": layer_status,
        "strengths": strengths,
        "warnings": warnings,
        "files_created": {
            "report_txt": report_txt,
            "categorical_stats_csv": categorical_stats_csv,
            "top_values_csv": top_values_csv,
            "summary_json": summary_json,
            "summary_xml": summary_xml
        },
        "next_action": "Run Layer 7 - Distribution Summary"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    # --------------------------------------------------------
    # XML summary
    # --------------------------------------------------------
    root = Element("layer6_categorical_basic_statistics")

    for key, value in summary.items():
        node = SubElement(root, key)

        if isinstance(value, list):
            for item in value:
                item_node = SubElement(node, "item")
                item_node.text = str(item)

        elif isinstance(value, dict):
            for k, v in value.items():
                child = SubElement(node, str(k))
                child.text = str(v)

        else:
            node.text = str(value)

    tree = ElementTree(root)
    tree.write(summary_xml, encoding="utf-8", xml_declaration=True)

    # --------------------------------------------------------
    # TXT report
    # --------------------------------------------------------
    report_text = f"""
LAYER 6: CATEGORICAL BASIC STATISTICS REPORT
==================================================

Created On:
{datetime.now()}

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Layer Status:
{layer_status}

Rows:
{total_rows}

Columns:
{total_columns}

Categorical/Text Columns Count:
{len(categorical_columns)}

Categorical/Text Columns:
{[str(col) for col in categorical_columns]}

Low-Cardinality Columns:
{low_cardinality_columns}

High-Cardinality Columns:
{high_cardinality_columns}

Constant Categorical Columns:
{constant_columns}

Strengths:
{strengths}

Warnings:
{warnings}

Files Created:
1. {report_txt}
2. {categorical_stats_csv}
3. {top_values_csv}
4. {summary_json}
5. {summary_xml}

Meaning:
Layer 6 creates basic descriptive statistics for categorical and text columns.

It includes:
1. Count
2. Missing values
3. Unique values
4. Top value
5. Top value percentage
6. Low-cardinality flags
7. High-cardinality flags
8. Top 10 values per categorical column

Important:
This layer does not check rare categories, class imbalance, or advanced encoding.
Those will be handled in later smaller layers.

Next Action:
Run Layer 7 - Distribution Summary.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report_text)

    # --------------------------------------------------------
    # Update root purpose file
    # --------------------------------------------------------
    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 6 UPDATE: CATEGORICAL BASIC STATISTICS
==================================================

Layer 6 completed on:
{datetime.now()}

Layer Status:
{layer_status}

Categorical/Text Columns Count:
{len(categorical_columns)}

Categorical/Text Columns:
{[str(col) for col in categorical_columns]}

Warnings:
{warnings}

Next Required Stage:
Layer 7 should generate distribution summary for all columns.
""")

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------
    print("Layer 6 completed successfully.")
    print("Layer Status:", layer_status)
    print("Categorical/Text Columns Count:", len(categorical_columns))
    print("Files created:")
    print(report_txt)
    print(categorical_stats_csv)
    print(top_values_csv)
    print(summary_json)
    print(summary_xml)

    display(categorical_stats_df)
    display(top_values_df)


# Run Layer 6
run_layer_6_categorical_basic_statistics()

Layer 6 completed successfully.
Layer Status: REVIEW_RECOMMENDED
Categorical/Text Columns Count: 12
Files created:
d:\Med_data\stage0-launch-pad\06_categorical_basic_statistics\layer6_categorical_basic_statistics_report.txt
d:\Med_data\stage0-launch-pad\06_categorical_basic_statistics\categorical_basic_statistics.csv
d:\Med_data\stage0-launch-pad\06_categorical_basic_statistics\categorical_top_values.csv
d:\Med_data\stage0-launch-pad\06_categorical_basic_statistics\layer6_categorical_basic_statistics.json
d:\Med_data\stage0-launch-pad\06_categorical_basic_statistics\layer6_categorical_basic_statistics.xml

,column_name,dtype,count,missing_count,missing_percentage,unique_values,top_value,top_value_count,top_value_percentage,sample_values,is_low_cardinality,is_high_cardinality,is_constant
0,Name,object,55500,0,0.0,49992,DAvId muNoZ,3,0.0054,Bobby JacksOn | LesLie TErRy | DaNnY sMitH | a...,False,True,False
1,Gender,object,55500,0,0.0,2,Male,27774,50.0432,Male | Male | Female | Female | Female,True,False,False
2,Blood Type,object,55500,0,0.0,8,A-,6969,12.5568,B- | A+ | A- | O+ | AB+,True,False,False
3,Medical Condition,object,55500,0,0.0,6,Arthritis,9308,16.7712,Cancer | Obesity | Obesity | Diabetes | Cancer,True,False,False
4,Date of Admission,object,55500,0,0.0,1827,2024-03-16,50,0.0901,2024-01-31 | 2019-08-20 | 2022-09-22 | 2020-11...,False,True,False
5,Doctor,object,55500,0,0.0,40341,Michael Smith,27,0.0486,Matthew Smith | Samantha Davies | Tiffany Mitc...,False,True,False
6,Hospital,object,55500,0,0.0,39876,LLC Smith,44,0.0793,Sons and Miller | Kim Inc | Cook PLC | Hernand...,False,True,False
7,Insurance Provider,object,55500,0,0.0,5,Cigna,11249,20.2685,Blue Cross | Medicare | Aetna | Medicare | Aetna,True,False,False
8,Admission Type,object,55500,0,0.0,3,Elective,18655,33.6126,Urgent | Emergency | Emergency | Elective | Ur...,True,False,False
9,Discharge Date,object,55500,0,0.0,1856,2020-03-15,53,0.0955,2024-02-02 | 2019-08-26 | 2022-10-07 | 2020-12...,False,True,False
10,Medication,object,55500,0,0.0,5,Lipitor,11140,20.0721,Paracetamol | Ibuprofen | Aspirin | Ibuprofen ...,True,False,False
11,Test Results,object,55500,0,0.0,3,Abnormal,18627,33.5622,Normal | Inconclusive | Normal | Abnormal | Ab...,True,False,False

     column_name           value  count  percentage
0           Name     DAvId muNoZ      3      0.0054
1           Name     SOnYa aDams      2      0.0036
2           Name  terRY gONZaLeZ      2      0.0036
3           Name  JaCKsON BARbeR      2      0.0036
4           Name    doNALD aViLA      2      0.0036
..           ...             ...    ...         ...
77    Medication     Paracetamol  11071     19.9477
78    Medication      Penicillin  11068     19.9423
79  Test Results        Abnormal  18627     33.5622
80  Test Results          Normal  18517     33.3640
81  Test Results    Inconclusive  18356     33.0739

[82 rows x 4 columns]

In [43]:
# ============================================================
# LAYER 7: DISTRIBUTION SUMMARY
# Run after Layer 6
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import re
import json
import pandas as pd
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, ElementTree
from IPython.display import display


def run_layer_7_distribution_summary():

    # --------------------------------------------------------
    # Create Layer 7 folder
    # --------------------------------------------------------
    layer_path = os.path.join(stage0_path, "07_distribution_summary")
    os.makedirs(layer_path, exist_ok=True)

    # --------------------------------------------------------
    # Output files
    # --------------------------------------------------------
    report_txt = os.path.join(layer_path, "layer7_distribution_summary_report.txt")
    distribution_csv = os.path.join(layer_path, "distribution_summary.csv")
    dominance_csv = os.path.join(layer_path, "dominant_value_report.csv")
    summary_json = os.path.join(layer_path, "layer7_distribution_summary.json")
    summary_xml = os.path.join(layer_path, "layer7_distribution_summary.xml")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    # --------------------------------------------------------
    # Helper functions
    # --------------------------------------------------------
    def safe_percent(part, total):
        if total == 0:
            return 0
        return round((part / total) * 100, 4)

    def safe_xml_name(name):
        name = str(name)
        name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        if name == "":
            name = "empty"
        if name[0].isdigit():
            name = "field_" + name
        return name

    def save_xml(path, root_name, data):
        root = Element(safe_xml_name(root_name))

        for key, value in data.items():
            node = SubElement(root, safe_xml_name(key))

            if isinstance(value, list):
                for item in value:
                    item_node = SubElement(node, "item")
                    item_node.text = str(item)

            elif isinstance(value, dict):
                for k, v in value.items():
                    child = SubElement(node, safe_xml_name(k))
                    child.text = str(v)

            else:
                node.text = str(value)

        tree = ElementTree(root)
        tree.write(path, encoding="utf-8", xml_declaration=True)

    # --------------------------------------------------------
    # Main distribution analysis
    # --------------------------------------------------------
    total_rows = int(df.shape[0])
    total_columns = int(df.shape[1])

    distribution_rows = []
    dominance_rows = []

    for col in df.columns:
        series = df[col]
        clean_series = series.dropna()

        missing_count = int(series.isna().sum())
        unique_count = int(series.nunique(dropna=True))

        if unique_count > 0:
            value_counts = series.value_counts(dropna=True)
            dominant_value = value_counts.index[0]
            dominant_count = int(value_counts.iloc[0])
            dominant_percentage = safe_percent(dominant_count, total_rows)
        else:
            dominant_value = None
            dominant_count = 0
            dominant_percentage = 0

        distribution_rows.append({
            "column_name": str(col),
            "dtype": str(series.dtype),
            "total_rows": total_rows,
            "non_missing_count": int(clean_series.count()),
            "missing_count": missing_count,
            "missing_percentage": safe_percent(missing_count, total_rows),
            "unique_values": unique_count,
            "unique_percentage": safe_percent(unique_count, total_rows),
            "dominant_value": str(dominant_value),
            "dominant_count": dominant_count,
            "dominant_percentage": dominant_percentage,
            "is_numeric": bool(pd.api.types.is_numeric_dtype(series)),
            "is_constant": bool(unique_count <= 1),
            "is_binary": bool(unique_count == 2),
            "is_low_cardinality": bool(2 <= unique_count <= 20),
            "is_high_cardinality": bool(unique_count > 50),
            "is_dominated_by_one_value": bool(dominant_percentage >= 80)
        })

        if dominant_percentage >= 80:
            dominance_rows.append({
                "column_name": str(col),
                "dominant_value": str(dominant_value),
                "dominant_count": dominant_count,
                "dominant_percentage": dominant_percentage,
                "warning": "One value dominates 80% or more of this column."
            })

    distribution_df = pd.DataFrame(distribution_rows)
    dominance_df = pd.DataFrame(dominance_rows)

    if dominance_df.empty:
        dominance_df = pd.DataFrame({
            "message": ["No column dominated by one value at 80% or above."]
        })

    distribution_df.to_csv(distribution_csv, index=False)
    dominance_df.to_csv(dominance_csv, index=False)

    # --------------------------------------------------------
    # Summary lists
    # --------------------------------------------------------
    constant_columns = distribution_df[
        distribution_df["is_constant"] == True
    ]["column_name"].tolist()

    binary_columns = distribution_df[
        distribution_df["is_binary"] == True
    ]["column_name"].tolist()

    low_cardinality_columns = distribution_df[
        distribution_df["is_low_cardinality"] == True
    ]["column_name"].tolist()

    high_cardinality_columns = distribution_df[
        distribution_df["is_high_cardinality"] == True
    ]["column_name"].tolist()

    dominated_columns = distribution_df[
        distribution_df["is_dominated_by_one_value"] == True
    ]["column_name"].tolist()

    # --------------------------------------------------------
    # Strengths and warnings
    # --------------------------------------------------------
    strengths = []
    warnings = []

    if len(binary_columns) > 0:
        strengths.append("Binary columns are available and may support classification or flag features.")

    if len(low_cardinality_columns) > 0:
        strengths.append("Low-cardinality columns are available for grouping or classification analysis.")

    if len(high_cardinality_columns) > 0:
        warnings.append("High-cardinality columns found; encoding review may be needed.")

    if len(constant_columns) > 0:
        warnings.append("Constant columns found; these usually have little ML value.")

    if len(dominated_columns) > 0:
        warnings.append("Some columns are dominated by one value at 80% or above.")

    layer_status = "PASS" if len(warnings) == 0 else "REVIEW_RECOMMENDED"

    # --------------------------------------------------------
    # JSON and XML summary
    # --------------------------------------------------------
    summary = {
        "stage": "Layer 7 - Distribution Summary",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": total_columns,
        "layer_status": layer_status,
        "constant_columns": constant_columns,
        "binary_columns": binary_columns,
        "low_cardinality_columns": low_cardinality_columns,
        "high_cardinality_columns": high_cardinality_columns,
        "dominated_columns_80_percent_plus": dominated_columns,
        "strengths": strengths,
        "warnings": warnings,
        "files_created": {
            "report_txt": report_txt,
            "distribution_csv": distribution_csv,
            "dominance_csv": dominance_csv,
            "summary_json": summary_json,
            "summary_xml": summary_xml
        },
        "next_action": "Run Layer 8 - Correlation Analysis"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    save_xml(summary_xml, "layer7_distribution_summary", summary)

    # --------------------------------------------------------
    # TXT report
    # --------------------------------------------------------
    report_text = f"""
LAYER 7: DISTRIBUTION SUMMARY REPORT
==================================================

Created On:
{datetime.now()}

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Layer Status:
{layer_status}

Rows:
{total_rows}

Columns:
{total_columns}

Constant Columns:
{constant_columns}

Binary Columns:
{binary_columns}

Low-Cardinality Columns:
{low_cardinality_columns}

High-Cardinality Columns:
{high_cardinality_columns}

Dominated Columns, 80%+:
{dominated_columns}

Strengths:
{strengths}

Warnings:
{warnings}

Files Created:
1. {report_txt}
2. {distribution_csv}
3. {dominance_csv}
4. {summary_json}
5. {summary_xml}

Meaning:
Layer 7 studies the distribution pattern of every column.

It checks:
1. Missing percentage
2. Unique values
3. Dominant value
4. Constant columns
5. Binary columns
6. Low-cardinality columns
7. High-cardinality columns
8. Columns dominated by one value

Important:
This layer does not calculate correlation or outliers.
Those will be handled in later smaller layers.

Next Action:
Run Layer 8 - Correlation Analysis.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report_text)

    # --------------------------------------------------------
    # Update root purpose file
    # --------------------------------------------------------
    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 7 UPDATE: DISTRIBUTION SUMMARY
==================================================

Layer 7 completed on:
{datetime.now()}

Layer Status:
{layer_status}

Constant Columns:
{constant_columns}

Binary Columns:
{binary_columns}

Low-Cardinality Columns:
{low_cardinality_columns}

High-Cardinality Columns:
{high_cardinality_columns}

Dominated Columns, 80%+:
{dominated_columns}

Warnings:
{warnings}

Next Required Stage:
Layer 8 should generate numeric correlation analysis.
""")

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------
    print("Layer 7 completed successfully.")
    print("Layer Status:", layer_status)
    print("Constant Columns:", constant_columns)
    print("Binary Columns:", binary_columns)
    print("High-Cardinality Columns:", high_cardinality_columns)
    print("Files created:")
    print(report_txt)
    print(distribution_csv)
    print(dominance_csv)
    print(summary_json)
    print(summary_xml)

    display(distribution_df)
    display(dominance_df)


# Run Layer 7
run_layer_7_distribution_summary()

Layer 7 completed successfully.
Layer Status: REVIEW_RECOMMENDED
Constant Columns: []
Binary Columns: ['Gender']
High-Cardinality Columns: ['Name', 'Age', 'Date of Admission', 'Doctor', 'Hospital', 'Billing Amount', 'Room Number', 'Discharge Date']
Files created:
d:\Med_data\stage0-launch-pad\07_distribution_summary\layer7_distribution_summary_report.txt
d:\Med_data\stage0-launch-pad\07_distribution_summary\distribution_summary.csv
d:\Med_data\stage0-launch-pad\07_distribution_summary\dominant_value_report.csv
d:\Med_data\stage0-launch-pad\07_distribution_summary\layer7_distribution_summary.json
d:\Med_data\stage0-launch-pad\07_distribution_summary\layer7_distribution_summary.xml

,column_name,dtype,total_rows,non_missing_count,missing_count,missing_percentage,unique_values,unique_percentage,dominant_value,dominant_count,dominant_percentage,is_numeric,is_constant,is_binary,is_low_cardinality,is_high_cardinality,is_dominated_by_one_value
0,Name,object,55500,55500,0,0.0,49992,90.0757,DAvId muNoZ,3,0.0054,False,False,False,False,True,False
1,Age,int64,55500,55500,0,0.0,77,0.1387,38,897,1.6162,True,False,False,False,True,False
2,Gender,object,55500,55500,0,0.0,2,0.0036,Male,27774,50.0432,False,False,True,True,False,False
3,Blood Type,object,55500,55500,0,0.0,8,0.0144,A-,6969,12.5568,False,False,False,True,False,False
4,Medical Condition,object,55500,55500,0,0.0,6,0.0108,Arthritis,9308,16.7712,False,False,False,True,False,False
5,Date of Admission,object,55500,55500,0,0.0,1827,3.2919,2024-03-16,50,0.0901,False,False,False,False,True,False
6,Doctor,object,55500,55500,0,0.0,40341,72.6865,Michael Smith,27,0.0486,False,False,False,False,True,False
7,Hospital,object,55500,55500,0,0.0,39876,71.8486,LLC Smith,44,0.0793,False,False,False,False,True,False
8,Insurance Provider,object,55500,55500,0,0.0,5,0.0090,Cigna,11249,20.2685,False,False,False,True,False,False
9,Billing Amount,float64,55500,55500,0,0.0,50000,90.0901,8926.285937326065,2,0.0036,True,False,False,False,True,False
10,Room Number,int64,55500,55500,0,0.0,400,0.7207,393,181,0.3261,True,False,False,False,True,False
11,Admission Type,object,55500,55500,0,0.0,3,0.0054,Elective,18655,33.6126,False,False,False,True,False,False
12,Discharge Date,object,55500,55500,0,0.0,1856,3.3441,2020-03-15,53,0.0955,False,False,False,False,True,False
13,Medication,object,55500,55500,0,0.0,5,0.0090,Lipitor,11140,20.0721,False,False,False,True,False,False
14,Test Results,object,55500,55500,0,0.0,3,0.0054,Abnormal,18627,33.5622,False,False,False,True,False,False

                                             message
0  No column dominated by one value at 80% or above.

In [45]:
# ============================================================
# LAYER 8: CORRELATION ANALYSIS
# Run after Layer 7
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import re
import json
import pandas as pd
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, ElementTree
from IPython.display import display


def run_layer_8_correlation_analysis():

    # --------------------------------------------------------
    # Create Layer 8 folder
    # --------------------------------------------------------
    layer_path = os.path.join(stage0_path, "08_correlation_analysis")
    os.makedirs(layer_path, exist_ok=True)

    # --------------------------------------------------------
    # Output files
    # --------------------------------------------------------
    report_txt = os.path.join(layer_path, "layer8_correlation_analysis_report.txt")
    correlation_csv = os.path.join(layer_path, "correlation_matrix.csv")
    high_corr_csv = os.path.join(layer_path, "high_correlation_pairs.csv")
    summary_json = os.path.join(layer_path, "layer8_correlation_analysis.json")
    summary_xml = os.path.join(layer_path, "layer8_correlation_analysis.xml")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    # --------------------------------------------------------
    # Helper functions
    # --------------------------------------------------------
    def safe_xml_name(name):
        name = str(name)
        name = re.sub(r"[^a-zA-Z0-9_]", "_", name)

        if name == "":
            name = "empty"

        if name[0].isdigit():
            name = "field_" + name

        return name

    def save_xml(path, root_name, data):
        root = Element(safe_xml_name(root_name))

        for key, value in data.items():
            node = SubElement(root, safe_xml_name(key))

            if isinstance(value, list):
                for item in value:
                    item_node = SubElement(node, "item")
                    item_node.text = str(item)

            elif isinstance(value, dict):
                for k, v in value.items():
                    child = SubElement(node, safe_xml_name(k))
                    child.text = str(v)

            else:
                node.text = str(value)

        tree = ElementTree(root)
        tree.write(path, encoding="utf-8", xml_declaration=True)

    # --------------------------------------------------------
    # Select numeric columns
    # --------------------------------------------------------
    total_rows = int(df.shape[0])
    total_columns = int(df.shape[1])

    numeric_df = df.select_dtypes(include=["number"])
    numeric_columns = list(numeric_df.columns)

    high_corr_pairs = []
    strengths = []
    warnings = []
    recommendations = []

    # --------------------------------------------------------
    # Correlation analysis
    # --------------------------------------------------------
    if len(numeric_columns) >= 2:

        correlation_df = numeric_df.corr(numeric_only=True)
        correlation_df.to_csv(correlation_csv)

        for i in range(len(correlation_df.columns)):
            for j in range(i + 1, len(correlation_df.columns)):

                col1 = correlation_df.columns[i]
                col2 = correlation_df.columns[j]
                corr_value = correlation_df.iloc[i, j]

                if pd.notna(corr_value):

                    if abs(corr_value) >= 0.80:
                        strength = "High"
                    elif abs(corr_value) >= 0.50:
                        strength = "Moderate"
                    elif abs(corr_value) >= 0.30:
                        strength = "Weak"
                    else:
                        strength = "Very Weak"

                    if abs(corr_value) >= 0.80:
                        high_corr_pairs.append({
                            "column_1": str(col1),
                            "column_2": str(col2),
                            "correlation": round(float(corr_value), 6),
                            "correlation_strength": strength,
                            "direction": "Positive" if corr_value > 0 else "Negative",
                            "recommendation": "Review before ML because highly correlated features may be redundant."
                        })

        high_corr_df = pd.DataFrame(high_corr_pairs)

        if high_corr_df.empty:
            high_corr_df = pd.DataFrame({
                "message": ["No high-correlation pairs found at threshold >= 0.80."]
            })

        high_corr_df.to_csv(high_corr_csv, index=False)

        strengths.append("Correlation analysis is possible because at least two numeric columns exist.")

        if len(high_corr_pairs) > 0:
            warnings.append("High-correlation numeric column pairs detected.")
            recommendations.append("Review highly correlated columns before ML to reduce redundancy or multicollinearity.")
        else:
            strengths.append("No high-correlation pairs detected at threshold >= 0.80.")

        layer_status = "PASS" if len(warnings) == 0 else "REVIEW_RECOMMENDED"

    else:
        correlation_df = pd.DataFrame({
            "message": ["Correlation analysis requires at least two numeric columns."]
        })

        high_corr_df = pd.DataFrame({
            "message": ["High-correlation scan not possible because fewer than two numeric columns exist."]
        })

        correlation_df.to_csv(correlation_csv, index=False)
        high_corr_df.to_csv(high_corr_csv, index=False)

        warnings.append("Correlation analysis is not possible because fewer than two numeric columns exist.")
        recommendations.append("Continue with categorical analysis, outlier checks, and metadata review.")

        layer_status = "REVIEW_RECOMMENDED"

    # --------------------------------------------------------
    # JSON and XML summary
    # --------------------------------------------------------
    summary = {
        "stage": "Layer 8 - Correlation Analysis",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": total_columns,
        "numeric_columns_count": len(numeric_columns),
        "numeric_columns": [str(col) for col in numeric_columns],
        "high_correlation_pairs_count": len(high_corr_pairs),
        "layer_status": layer_status,
        "strengths": strengths,
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "report_txt": report_txt,
            "correlation_matrix": correlation_csv,
            "high_correlation_pairs": high_corr_csv,
            "summary_json": summary_json,
            "summary_xml": summary_xml
        },
        "next_action": "Run Layer 9 - Outlier Analysis"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    save_xml(summary_xml, "layer8_correlation_analysis", summary)

    # --------------------------------------------------------
    # TXT report
    # --------------------------------------------------------
    report_text = f"""
LAYER 8: CORRELATION ANALYSIS REPORT
==================================================

Created On:
{datetime.now()}

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Layer Status:
{layer_status}

Rows:
{total_rows}

Columns:
{total_columns}

Numeric Columns Count:
{len(numeric_columns)}

Numeric Columns:
{[str(col) for col in numeric_columns]}

High-Correlation Pairs Count:
{len(high_corr_pairs)}

Strengths:
{strengths}

Warnings:
{warnings}

Recommendations:
{recommendations}

Files Created:
1. {report_txt}
2. {correlation_csv}
3. {high_corr_csv}
4. {summary_json}
5. {summary_xml}

Meaning:
Layer 8 checks correlation between numeric columns.

It creates:
1. Correlation matrix
2. High-correlation pair report
3. Correlation summary

Important:
High correlation does not always mean a column should be removed.
It only means the columns should be reviewed before ML.

Next Action:
Run Layer 9 - Outlier Analysis.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report_text)

    # --------------------------------------------------------
    # Update root purpose file
    # --------------------------------------------------------
    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 8 UPDATE: CORRELATION ANALYSIS
==================================================

Layer 8 completed on:
{datetime.now()}

Layer Status:
{layer_status}

Numeric Columns Count:
{len(numeric_columns)}

High-Correlation Pairs Count:
{len(high_corr_pairs)}

Warnings:
{warnings}

Recommendations:
{recommendations}

Next Required Stage:
Layer 9 should generate outlier analysis for numeric columns.
""")

    # --------------------------------------------------------
    # Print result
    # --------------------------------------------------------
    print("Layer 8 completed successfully.")
    print("Layer Status:", layer_status)
    print("Numeric Columns Count:", len(numeric_columns))
    print("High-Correlation Pairs Count:", len(high_corr_pairs))
    print("Files created:")
    print(report_txt)
    print(correlation_csv)
    print(high_corr_csv)
    print(summary_json)
    print(summary_xml)

    display(correlation_df)
    display(high_corr_df)


# Run Layer 8
run_layer_8_correlation_analysis()

Layer 8 completed successfully.
Layer Status: PASS
Numeric Columns Count: 3
High-Correlation Pairs Count: 0
Files created:
d:\Med_data\stage0-launch-pad\08_correlation_analysis\layer8_correlation_analysis_report.txt
d:\Med_data\stage0-launch-pad\08_correlation_analysis\correlation_matrix.csv
d:\Med_data\stage0-launch-pad\08_correlation_analysis\high_correlation_pairs.csv
d:\Med_data\stage0-launch-pad\08_correlation_analysis\layer8_correlation_analysis.json
d:\Med_data\stage0-launch-pad\08_correlation_analysis\layer8_correlation_analysis.xml

                     Age  Billing Amount  Room Number
Age             1.000000       -0.003832    -0.000720
Billing Amount -0.003832        1.000000    -0.002943
Room Number    -0.000720       -0.002943     1.000000

                                             message
0  No high-correlation pairs found at threshold >...

In [47]:
# ============================================================
# LAYER 9: OUTLIER ANALYSIS - SHORT & SAFE VERSION
# Run after Layer 8
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_9_outlier_analysis():

    layer_path = os.path.join(stage0_path, "09_outlier_analysis")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer9_outlier_report.txt")
    outlier_csv = os.path.join(layer_path, "outlier_summary_iqr.csv")
    preview_csv = os.path.join(layer_path, "outlier_preview_rows.csv")
    summary_json = os.path.join(layer_path, "layer9_outlier_summary.json")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    def pct(part, total):
        return round((part / total) * 100, 4) if total else 0

    total_rows = df.shape[0]
    numeric_df = df.select_dtypes(include=["number"])
    numeric_cols = list(numeric_df.columns)

    summary_rows = []
    preview_rows = []

    for col in numeric_cols:
        s = numeric_df[col].dropna()

        if s.empty:
            continue

        q1 = s.quantile(0.25)
        q3 = s.quantile(0.75)
        iqr = q3 - q1
        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        mask = (numeric_df[col] < lower) | (numeric_df[col] > upper)
        outlier_count = int(mask.sum())

        summary_rows.append({
            "column_name": col,
            "q1": round(q1, 6),
            "q3": round(q3, 6),
            "iqr": round(iqr, 6),
            "lower_bound": round(lower, 6),
            "upper_bound": round(upper, 6),
            "outlier_count": outlier_count,
            "outlier_percentage": pct(outlier_count, len(s)),
            "min": round(s.min(), 6),
            "max": round(s.max(), 6)
        })

        for idx, value in numeric_df.loc[mask, col].head(20).items():
            preview_rows.append({
                "row_index": idx,
                "column_name": col,
                "outlier_value": value,
                "lower_bound": round(lower, 6),
                "upper_bound": round(upper, 6)
            })

    outlier_df = pd.DataFrame(summary_rows)
    preview_df = pd.DataFrame(preview_rows)

    if outlier_df.empty:
        outlier_df = pd.DataFrame({"message": ["No numeric columns found for outlier analysis."]})

    if preview_df.empty:
        preview_df = pd.DataFrame({"message": ["No outlier rows found."]})

    outlier_df.to_csv(outlier_csv, index=False)
    preview_df.to_csv(preview_csv, index=False)

    if "outlier_count" in outlier_df.columns:
        cols_with_outliers = outlier_df[outlier_df["outlier_count"] > 0]["column_name"].tolist()
    else:
        cols_with_outliers = []

    warnings = []
    recommendations = []

    if not numeric_cols:
        warnings.append("No numeric columns found.")
    elif cols_with_outliers:
        warnings.append("Outliers detected in numeric columns.")
        recommendations.append("Review outliers before removing or capping them.")
    else:
        recommendations.append("No IQR outliers detected automatically.")

    layer_status = "PASS" if not warnings else "REVIEW_RECOMMENDED"

    summary = {
        "stage": "Layer 9 - Outlier Analysis",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "numeric_columns_count": len(numeric_cols),
        "columns_with_outliers": cols_with_outliers,
        "layer_status": layer_status,
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "report_txt": report_txt,
            "outlier_summary_csv": outlier_csv,
            "outlier_preview_csv": preview_csv,
            "summary_json": summary_json
        },
        "next_action": "Run Layer 10 - Skewness and Kurtosis Analysis"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    report = f"""
LAYER 9: OUTLIER ANALYSIS REPORT
==================================================

Created On: {datetime.now()}

Dataset Name: {dataset_name}
Dataset Path: {dataset_path}

Layer Status: {layer_status}

Rows: {df.shape[0]}
Columns: {df.shape[1]}
Numeric Columns Count: {len(numeric_cols)}
Columns With Outliers: {cols_with_outliers}

Warnings:
{warnings}

Recommendations:
{recommendations}

Files Created:
1. {outlier_csv}
2. {preview_csv}
3. {summary_json}

Meaning:
Layer 9 detects numeric outliers using the IQR method.

Formula:
IQR = Q3 - Q1
Lower Bound = Q1 - 1.5 × IQR
Upper Bound = Q3 + 1.5 × IQR

Important:
Outliers are not always errors. Review them before removing.

Next Action:
Run Layer 10 - Skewness and Kurtosis Analysis.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report)

    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 9 UPDATE: OUTLIER ANALYSIS
==================================================

Layer 9 completed on: {datetime.now()}
Layer Status: {layer_status}
Columns With Outliers: {cols_with_outliers}
Next Required Stage: Layer 10 - Skewness and Kurtosis Analysis.
""")

    print("Layer 9 completed successfully.")
    print("Layer Status:", layer_status)
    print("Columns With Outliers:", cols_with_outliers)
    print("Files created:")
    print(report_txt)
    print(outlier_csv)
    print(preview_csv)
    print(summary_json)

    display(outlier_df)
    display(preview_df)


# Run Layer 9
run_layer_9_outlier_analysis()

Layer 9 completed successfully.
Layer Status: PASS
Columns With Outliers: []
Files created:
d:\Med_data\stage0-launch-pad\09_outlier_analysis\layer9_outlier_report.txt
d:\Med_data\stage0-launch-pad\09_outlier_analysis\outlier_summary_iqr.csv
d:\Med_data\stage0-launch-pad\09_outlier_analysis\outlier_preview_rows.csv
d:\Med_data\stage0-launch-pad\09_outlier_analysis\layer9_outlier_summary.json

,column_name,q1,q3,iqr,lower_bound,upper_bound,outlier_count,outlier_percentage,min,max
0,Age,35.000000,68.000000,33.000000,-14.500000,117.500000,0,0.0,13.00000,89.000000
1,Billing Amount,13241.224652,37820.508436,24579.283783,-23627.701023,74689.434111,0,0.0,-2008.49214,52764.276736
2,Room Number,202.000000,401.000000,199.000000,-96.500000,699.500000,0,0.0,101.00000,500.000000

                  message
0  No outlier rows found.

In [49]:
# ============================================================
# LAYER 10: SKEWNESS & KURTOSIS ANALYSIS - SHORT VERSION
# Run after Layer 9
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_10_skewness_kurtosis_analysis():

    layer_path = os.path.join(stage0_path, "10_skewness_kurtosis_analysis")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer10_skewness_kurtosis_report.txt")
    skew_csv = os.path.join(layer_path, "skewness_kurtosis_summary.csv")
    summary_json = os.path.join(layer_path, "layer10_skewness_kurtosis_summary.json")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    numeric_df = df.select_dtypes(include=["number"])
    numeric_cols = list(numeric_df.columns)

    rows = []

    for col in numeric_cols:
        s = numeric_df[col].dropna()

        if len(s) < 3:
            rows.append({
                "column_name": col,
                "skewness": None,
                "kurtosis": None,
                "skewness_interpretation": "Not enough data",
                "kurtosis_interpretation": "Not enough data"
            })
            continue

        skew_value = s.skew()
        kurt_value = s.kurtosis()

        if abs(skew_value) < 0.5:
            skew_text = "Approximately symmetric"
        elif abs(skew_value) < 1:
            skew_text = "Moderately skewed"
        else:
            skew_text = "Highly skewed"

        if kurt_value > 1:
            kurt_text = "Heavy-tailed distribution"
        elif kurt_value < -1:
            kurt_text = "Light-tailed distribution"
        else:
            kurt_text = "Near-normal tail behavior"

        rows.append({
            "column_name": col,
            "skewness": round(float(skew_value), 6),
            "kurtosis": round(float(kurt_value), 6),
            "skewness_interpretation": skew_text,
            "kurtosis_interpretation": kurt_text
        })

    skew_df = pd.DataFrame(rows)

    if skew_df.empty:
        skew_df = pd.DataFrame({
            "message": ["No numeric columns found for skewness/kurtosis analysis."]
        })

    skew_df.to_csv(skew_csv, index=False)

    highly_skewed_cols = []
    heavy_tail_cols = []

    if "skewness_interpretation" in skew_df.columns:
        highly_skewed_cols = skew_df[
            skew_df["skewness_interpretation"] == "Highly skewed"
        ]["column_name"].tolist()

    if "kurtosis_interpretation" in skew_df.columns:
        heavy_tail_cols = skew_df[
            skew_df["kurtosis_interpretation"] == "Heavy-tailed distribution"
        ]["column_name"].tolist()

    warnings = []
    recommendations = []

    if not numeric_cols:
        warnings.append("No numeric columns found.")

    if highly_skewed_cols:
        warnings.append("Highly skewed numeric columns detected.")
        recommendations.append("Consider log transform, square-root transform, binning, or robust scaling if meaningful.")

    if heavy_tail_cols:
        warnings.append("Heavy-tailed numeric columns detected.")
        recommendations.append("Review extreme values and consider robust models or scaling.")

    if not recommendations:
        recommendations.append("No major skewness/kurtosis issue detected automatically.")

    layer_status = "PASS" if not warnings else "REVIEW_RECOMMENDED"

    summary = {
        "stage": "Layer 10 - Skewness and Kurtosis Analysis",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "numeric_columns_count": len(numeric_cols),
        "highly_skewed_columns": highly_skewed_cols,
        "heavy_tail_columns": heavy_tail_cols,
        "layer_status": layer_status,
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "report_txt": report_txt,
            "skewness_kurtosis_csv": skew_csv,
            "summary_json": summary_json
        },
        "next_action": "Run Layer 11 - Class Balance Analysis"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    report = f"""
LAYER 10: SKEWNESS AND KURTOSIS ANALYSIS REPORT
==================================================

Created On: {datetime.now()}

Dataset Name: {dataset_name}
Dataset Path: {dataset_path}

Layer Status: {layer_status}

Rows: {df.shape[0]}
Columns: {df.shape[1]}
Numeric Columns Count: {len(numeric_cols)}

Highly Skewed Columns:
{highly_skewed_cols}

Heavy-Tailed Columns:
{heavy_tail_cols}

Warnings:
{warnings}

Recommendations:
{recommendations}

Files Created:
1. {skew_csv}
2. {summary_json}

Meaning:
Layer 10 checks the shape of numeric distributions.

Skewness:
Shows whether values are balanced, right-skewed, or left-skewed.

Kurtosis:
Shows whether the column has heavy tails or extreme values.

Important:
Do not transform columns automatically. Confirm meaning first.

Next Action:
Run Layer 11 - Class Balance Analysis.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report)

    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 10 UPDATE: SKEWNESS AND KURTOSIS
==================================================

Layer 10 completed on: {datetime.now()}
Layer Status: {layer_status}
Highly Skewed Columns: {highly_skewed_cols}
Heavy-Tailed Columns: {heavy_tail_cols}
Next Required Stage: Layer 11 - Class Balance Analysis.
""")

    print("Layer 10 completed successfully.")
    print("Layer Status:", layer_status)
    print("Highly Skewed Columns:", highly_skewed_cols)
    print("Heavy-Tailed Columns:", heavy_tail_cols)
    print("Files created:")
    print(report_txt)
    print(skew_csv)
    print(summary_json)

    display(skew_df)


# Run Layer 10
run_layer_10_skewness_kurtosis_analysis()# ============================================================
# LAYER 10: SKEWNESS & KURTOSIS ANALYSIS - SHORT VERSION
# Run after Layer 9
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_10_skewness_kurtosis_analysis():

    layer_path = os.path.join(stage0_path, "10_skewness_kurtosis_analysis")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer10_skewness_kurtosis_report.txt")
    skew_csv = os.path.join(layer_path, "skewness_kurtosis_summary.csv")
    summary_json = os.path.join(layer_path, "layer10_skewness_kurtosis_summary.json")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    numeric_df = df.select_dtypes(include=["number"])
    numeric_cols = list(numeric_df.columns)

    rows = []

    for col in numeric_cols:
        s = numeric_df[col].dropna()

        if len(s) < 3:
            rows.append({
                "column_name": col,
                "skewness": None,
                "kurtosis": None,
                "skewness_interpretation": "Not enough data",
                "kurtosis_interpretation": "Not enough data"
            })
            continue

        skew_value = s.skew()
        kurt_value = s.kurtosis()

        if abs(skew_value) < 0.5:
            skew_text = "Approximately symmetric"
        elif abs(skew_value) < 1:
            skew_text = "Moderately skewed"
        else:
            skew_text = "Highly skewed"

        if kurt_value > 1:
            kurt_text = "Heavy-tailed distribution"
        elif kurt_value < -1:
            kurt_text = "Light-tailed distribution"
        else:
            kurt_text = "Near-normal tail behavior"

        rows.append({
            "column_name": col,
            "skewness": round(float(skew_value), 6),
            "kurtosis": round(float(kurt_value), 6),
            "skewness_interpretation": skew_text,
            "kurtosis_interpretation": kurt_text
        })

    skew_df = pd.DataFrame(rows)

    if skew_df.empty:
        skew_df = pd.DataFrame({
            "message": ["No numeric columns found for skewness/kurtosis analysis."]
        })

    skew_df.to_csv(skew_csv, index=False)

    highly_skewed_cols = []
    heavy_tail_cols = []

    if "skewness_interpretation" in skew_df.columns:
        highly_skewed_cols = skew_df[
            skew_df["skewness_interpretation"] == "Highly skewed"
        ]["column_name"].tolist()

    if "kurtosis_interpretation" in skew_df.columns:
        heavy_tail_cols = skew_df[
            skew_df["kurtosis_interpretation"] == "Heavy-tailed distribution"
        ]["column_name"].tolist()

    warnings = []
    recommendations = []

    if not numeric_cols:
        warnings.append("No numeric columns found.")

    if highly_skewed_cols:
        warnings.append("Highly skewed numeric columns detected.")
        recommendations.append("Consider log transform, square-root transform, binning, or robust scaling if meaningful.")

    if heavy_tail_cols:
        warnings.append("Heavy-tailed numeric columns detected.")
        recommendations.append("Review extreme values and consider robust models or scaling.")

    if not recommendations:
        recommendations.append("No major skewness/kurtosis issue detected automatically.")

    layer_status = "PASS" if not warnings else "REVIEW_RECOMMENDED"

    summary = {
        "stage": "Layer 10 - Skewness and Kurtosis Analysis",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "numeric_columns_count": len(numeric_cols),
        "highly_skewed_columns": highly_skewed_cols,
        "heavy_tail_columns": heavy_tail_cols,
        "layer_status": layer_status,
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "report_txt": report_txt,
            "skewness_kurtosis_csv": skew_csv,
            "summary_json": summary_json
        },
        "next_action": "Run Layer 11 - Class Balance Analysis"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    report = f"""
LAYER 10: SKEWNESS AND KURTOSIS ANALYSIS REPORT
==================================================

Created On: {datetime.now()}

Dataset Name: {dataset_name}
Dataset Path: {dataset_path}

Layer Status: {layer_status}

Rows: {df.shape[0]}
Columns: {df.shape[1]}
Numeric Columns Count: {len(numeric_cols)}

Highly Skewed Columns:
{highly_skewed_cols}

Heavy-Tailed Columns:
{heavy_tail_cols}

Warnings:
{warnings}

Recommendations:
{recommendations}

Files Created:
1. {skew_csv}
2. {summary_json}

Meaning:
Layer 10 checks the shape of numeric distributions.

Skewness:
Shows whether values are balanced, right-skewed, or left-skewed.

Kurtosis:
Shows whether the column has heavy tails or extreme values.

Important:
Do not transform columns automatically. Confirm meaning first.

Next Action:
Run Layer 11 - Class Balance Analysis.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report)

    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 10 UPDATE: SKEWNESS AND KURTOSIS
==================================================

Layer 10 completed on: {datetime.now()}
Layer Status: {layer_status}
Highly Skewed Columns: {highly_skewed_cols}
Heavy-Tailed Columns: {heavy_tail_cols}
Next Required Stage: Layer 11 - Class Balance Analysis.
""")

    print("Layer 10 completed successfully.")
    print("Layer Status:", layer_status)
    print("Highly Skewed Columns:", highly_skewed_cols)
    print("Heavy-Tailed Columns:", heavy_tail_cols)
    print("Files created:")
    print(report_txt)
    print(skew_csv)
    print(summary_json)

    display(skew_df)


# Run Layer 10
run_layer_10_skewness_kurtosis_analysis()

Layer 10 completed successfully.
Layer Status: PASS
Highly Skewed Columns: []
Heavy-Tailed Columns: []
Files created:
d:\Med_data\stage0-launch-pad\10_skewness_kurtosis_analysis\layer10_skewness_kurtosis_report.txt
d:\Med_data\stage0-launch-pad\10_skewness_kurtosis_analysis\skewness_kurtosis_summary.csv
d:\Med_data\stage0-launch-pad\10_skewness_kurtosis_analysis\layer10_skewness_kurtosis_summary.json

,column_name,skewness,kurtosis,skewness_interpretation,kurtosis_interpretation
0,Age,-0.005735,-1.185576,Approximately symmetric,Light-tailed distribution
1,Billing Amount,-0.000978,-1.190630,Approximately symmetric,Light-tailed distribution
2,Room Number,-0.011200,-1.194189,Approximately symmetric,Light-tailed distribution

Layer 10 completed successfully.
Layer Status: PASS
Highly Skewed Columns: []
Heavy-Tailed Columns: []
Files created:
d:\Med_data\stage0-launch-pad\10_skewness_kurtosis_analysis\layer10_skewness_kurtosis_report.txt
d:\Med_data\stage0-launch-pad\10_skewness_kurtosis_analysis\skewness_kurtosis_summary.csv
d:\Med_data\stage0-launch-pad\10_skewness_kurtosis_analysis\layer10_skewness_kurtosis_summary.json

,column_name,skewness,kurtosis,skewness_interpretation,kurtosis_interpretation
0,Age,-0.005735,-1.185576,Approximately symmetric,Light-tailed distribution
1,Billing Amount,-0.000978,-1.190630,Approximately symmetric,Light-tailed distribution
2,Room Number,-0.011200,-1.194189,Approximately symmetric,Light-tailed distribution

In [51]:
# ============================================================
# LAYER 11: CLASS BALANCE ANALYSIS - SHORT VERSION
# Run after Layer 10
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_11_class_balance_analysis():

    layer_path = os.path.join(stage0_path, "11_class_balance_analysis")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer11_class_balance_report.txt")
    class_balance_csv = os.path.join(layer_path, "class_balance_report.csv")
    summary_json = os.path.join(layer_path, "layer11_class_balance_summary.json")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    def pct(part, total):
        return round((part / total) * 100, 4) if total else 0

    total_rows = int(df.shape[0])
    balance_rows = []
    imbalanced_columns = []
    balanced_columns = []

    # Check columns with 2 to 20 unique values
    for col in df.columns:
        series = df[col].dropna()
        unique_count = series.nunique()

        if 2 <= unique_count <= 20:
            counts = series.value_counts()
            max_pct = pct(counts.max(), len(series))
            min_pct = pct(counts.min(), len(series))

            if max_pct >= 80:
                balance_status = "Imbalanced"
                imbalanced_columns.append(str(col))
            else:
                balance_status = "Acceptable"
                balanced_columns.append(str(col))

            for value, count in counts.items():
                balance_rows.append({
                    "column_name": str(col),
                    "class_value": str(value),
                    "count": int(count),
                    "percentage": pct(count, len(series)),
                    "column_unique_values": int(unique_count),
                    "majority_class_percentage": max_pct,
                    "minority_class_percentage": min_pct,
                    "balance_status": balance_status
                })

    balance_df = pd.DataFrame(balance_rows)

    if balance_df.empty:
        balance_df = pd.DataFrame({
            "message": ["No low-cardinality columns found for class balance analysis."]
        })

    balance_df.to_csv(class_balance_csv, index=False)

    warnings = []
    recommendations = []

    if imbalanced_columns:
        warnings.append("Some low-cardinality columns are imbalanced.")
        recommendations.append("If used as target, consider stratified split, class weights, oversampling, or suitable metrics.")
    else:
        recommendations.append("No serious class imbalance detected automatically.")

    if balance_rows:
        recommendations.append("Review possible target columns carefully before ML.")
    else:
        warnings.append("No class-balance candidates found.")

    layer_status = "PASS" if not warnings else "REVIEW_RECOMMENDED"

    summary = {
        "stage": "Layer 11 - Class Balance Analysis",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": int(df.shape[1]),
        "balanced_columns": balanced_columns,
        "imbalanced_columns": imbalanced_columns,
        "layer_status": layer_status,
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "report_txt": report_txt,
            "class_balance_csv": class_balance_csv,
            "summary_json": summary_json
        },
        "next_action": "Run Layer 12 - Rare Category Analysis"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    report = f"""
LAYER 11: CLASS BALANCE ANALYSIS REPORT
==================================================

Created On: {datetime.now()}

Dataset Name: {dataset_name}
Dataset Path: {dataset_path}

Layer Status: {layer_status}

Rows: {df.shape[0]}
Columns: {df.shape[1]}

Balanced Columns:
{balanced_columns}

Imbalanced Columns:
{imbalanced_columns}

Warnings:
{warnings}

Recommendations:
{recommendations}

Files Created:
1. {class_balance_csv}
2. {summary_json}

Meaning:
Layer 11 checks low-cardinality columns with 2 to 20 unique values.
These columns may be possible classification targets or grouping variables.

Important:
If an imbalanced column is used as target, accuracy alone may be misleading.
Use better metrics such as precision, recall, F1-score, ROC-AUC, or balanced accuracy.

Next Action:
Run Layer 12 - Rare Category Analysis.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report)

    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 11 UPDATE: CLASS BALANCE ANALYSIS
==================================================

Layer 11 completed on: {datetime.now()}
Layer Status: {layer_status}
Balanced Columns: {balanced_columns}
Imbalanced Columns: {imbalanced_columns}
Next Required Stage: Layer 12 - Rare Category Analysis.
""")

    print("Layer 11 completed successfully.")
    print("Layer Status:", layer_status)
    print("Balanced Columns:", balanced_columns)
    print("Imbalanced Columns:", imbalanced_columns)
    print("Files created:")
    print(report_txt)
    print(class_balance_csv)
    print(summary_json)

    display(balance_df)


# Run Layer 11
run_layer_11_class_balance_analysis()

Layer 11 completed successfully.
Layer Status: PASS
Balanced Columns: ['Gender', 'Blood Type', 'Medical Condition', 'Insurance Provider', 'Admission Type', 'Medication', 'Test Results']
Imbalanced Columns: []
Files created:
d:\Med_data\stage0-launch-pad\11_class_balance_analysis\layer11_class_balance_report.txt
d:\Med_data\stage0-launch-pad\11_class_balance_analysis\class_balance_report.csv
d:\Med_data\stage0-launch-pad\11_class_balance_analysis\layer11_class_balance_summary.json

,column_name,class_value,count,percentage,column_unique_values,majority_class_percentage,minority_class_percentage,balance_status
0,Gender,Male,27774,50.0432,2,50.0432,49.9568,Acceptable
1,Gender,Female,27726,49.9568,2,50.0432,49.9568,Acceptable
2,Blood Type,A-,6969,12.5568,8,12.5568,12.3910,Acceptable
3,Blood Type,A+,6956,12.5333,8,12.5568,12.3910,Acceptable
4,Blood Type,AB+,6947,12.5171,8,12.5568,12.3910,Acceptable
5,Blood Type,AB-,6945,12.5135,8,12.5568,12.3910,Acceptable
6,Blood Type,B+,6945,12.5135,8,12.5568,12.3910,Acceptable
7,Blood Type,B-,6944,12.5117,8,12.5568,12.3910,Acceptable
8,Blood Type,O+,6917,12.4631,8,12.5568,12.3910,Acceptable
9,Blood Type,O-,6877,12.3910,8,12.5568,12.3910,Acceptable
10,Medical Condition,Arthritis,9308,16.7712,6,16.7712,16.5495,Acceptable
11,Medical Condition,Diabetes,9304,16.7640,6,16.7712,16.5495,Acceptable
12,Medical Condition,Hypertension,9245,16.6577,6,16.7712,16.5495,Acceptable
13,Medical Condition,Obesity,9231,16.6324,6,16.7712,16.5495,Acceptable
14,Medical Condition,Cancer,9227,16.6252,6,16.7712,16.5495,Acceptable
15,Medical Condition,Asthma,9185,16.5495,6,16.7712,16.5495,Acceptable
16,Insurance Provider,Cigna,11249,20.2685,5,20.2685,19.6631,Acceptable
17,Insurance Provider,Medicare,11154,20.0973,5,20.2685,19.6631,Acceptable
18,Insurance Provider,UnitedHealthcare,11125,20.0450,5,20.2685,19.6631,Acceptable
19,Insurance Provider,Blue Cross,11059,19.9261,5,20.2685,19.6631,Acceptable
20,Insurance Provider,Aetna,10913,19.6631,5,20.2685,19.6631,Acceptable
21,Admission Type,Elective,18655,33.6126,3,33.6126,32.9171,Acceptable
22,Admission Type,Urgent,18576,33.4703,3,33.6126,32.9171,Acceptable
23,Admission Type,Emergency,18269,32.9171,3,33.6126,32.9171,Acceptable
24,Medication,Lipitor,11140,20.0721,5,20.0721,19.9423,Acceptable
25,Medication,Ibuprofen,11127,20.0486,5,20.0721,19.9423,Acceptable
26,Medication,Aspirin,11094,19.9892,5,20.0721,19.9423,Acceptable
27,Medication,Paracetamol,11071,19.9477,5,20.0721,19.9423,Acceptable
28,Medication,Penicillin,11068,19.9423,5,20.0721,19.9423,Acceptable
29,Test Results,Abnormal,18627,33.5622,3,33.5622,33.0739,Acceptable
30,Test Results,Normal,18517,33.3640,3,33.5622,33.0739,Acceptable
31,Test Results,Inconclusive,18356,33.0739,3,33.5622,33.0739,Acceptable

In [53]:
# ============================================================
# LAYER 11: CLASS BALANCE ANALYSIS - SHORT VERSION
# Run after Layer 10
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_11_class_balance_analysis():

    layer_path = os.path.join(stage0_path, "11_class_balance_analysis")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer11_class_balance_report.txt")
    class_balance_csv = os.path.join(layer_path, "class_balance_report.csv")
    summary_json = os.path.join(layer_path, "layer11_class_balance_summary.json")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    def pct(part, total):
        return round((part / total) * 100, 4) if total else 0

    total_rows = int(df.shape[0])
    balance_rows = []
    imbalanced_columns = []
    balanced_columns = []

    # Check columns with 2 to 20 unique values
    for col in df.columns:
        series = df[col].dropna()
        unique_count = series.nunique()

        if 2 <= unique_count <= 20:
            counts = series.value_counts()
            max_pct = pct(counts.max(), len(series))
            min_pct = pct(counts.min(), len(series))

            if max_pct >= 80:
                balance_status = "Imbalanced"
                imbalanced_columns.append(str(col))
            else:
                balance_status = "Acceptable"
                balanced_columns.append(str(col))

            for value, count in counts.items():
                balance_rows.append({
                    "column_name": str(col),
                    "class_value": str(value),
                    "count": int(count),
                    "percentage": pct(count, len(series)),
                    "column_unique_values": int(unique_count),
                    "majority_class_percentage": max_pct,
                    "minority_class_percentage": min_pct,
                    "balance_status": balance_status
                })

    balance_df = pd.DataFrame(balance_rows)

    if balance_df.empty:
        balance_df = pd.DataFrame({
            "message": ["No low-cardinality columns found for class balance analysis."]
        })

    balance_df.to_csv(class_balance_csv, index=False)

    warnings = []
    recommendations = []

    if imbalanced_columns:
        warnings.append("Some low-cardinality columns are imbalanced.")
        recommendations.append("If used as target, consider stratified split, class weights, oversampling, or suitable metrics.")
    else:
        recommendations.append("No serious class imbalance detected automatically.")

    if balance_rows:
        recommendations.append("Review possible target columns carefully before ML.")
    else:
        warnings.append("No class-balance candidates found.")

    layer_status = "PASS" if not warnings else "REVIEW_RECOMMENDED"

    summary = {
        "stage": "Layer 11 - Class Balance Analysis",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": int(df.shape[1]),
        "balanced_columns": balanced_columns,
        "imbalanced_columns": imbalanced_columns,
        "layer_status": layer_status,
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "report_txt": report_txt,
            "class_balance_csv": class_balance_csv,
            "summary_json": summary_json
        },
        "next_action": "Run Layer 12 - Rare Category Analysis"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    report = f"""
LAYER 11: CLASS BALANCE ANALYSIS REPORT
==================================================

Created On: {datetime.now()}

Dataset Name: {dataset_name}
Dataset Path: {dataset_path}

Layer Status: {layer_status}

Rows: {df.shape[0]}
Columns: {df.shape[1]}

Balanced Columns:
{balanced_columns}

Imbalanced Columns:
{imbalanced_columns}

Warnings:
{warnings}

Recommendations:
{recommendations}

Files Created:
1. {class_balance_csv}
2. {summary_json}

Meaning:
Layer 11 checks low-cardinality columns with 2 to 20 unique values.
These columns may be possible classification targets or grouping variables.

Important:
If an imbalanced column is used as target, accuracy alone may be misleading.
Use better metrics such as precision, recall, F1-score, ROC-AUC, or balanced accuracy.

Next Action:
Run Layer 12 - Rare Category Analysis.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report)

    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 11 UPDATE: CLASS BALANCE ANALYSIS
==================================================

Layer 11 completed on: {datetime.now()}
Layer Status: {layer_status}
Balanced Columns: {balanced_columns}
Imbalanced Columns: {imbalanced_columns}
Next Required Stage: Layer 12 - Rare Category Analysis.
""")

    print("Layer 11 completed successfully.")
    print("Layer Status:", layer_status)
    print("Balanced Columns:", balanced_columns)
    print("Imbalanced Columns:", imbalanced_columns)
    print("Files created:")
    print(report_txt)
    print(class_balance_csv)
    print(summary_json)

    display(balance_df)


# Run Layer 11
run_layer_11_class_balance_analysis()

Layer 11 completed successfully.
Layer Status: PASS
Balanced Columns: ['Gender', 'Blood Type', 'Medical Condition', 'Insurance Provider', 'Admission Type', 'Medication', 'Test Results']
Imbalanced Columns: []
Files created:
d:\Med_data\stage0-launch-pad\11_class_balance_analysis\layer11_class_balance_report.txt
d:\Med_data\stage0-launch-pad\11_class_balance_analysis\class_balance_report.csv
d:\Med_data\stage0-launch-pad\11_class_balance_analysis\layer11_class_balance_summary.json

,column_name,class_value,count,percentage,column_unique_values,majority_class_percentage,minority_class_percentage,balance_status
0,Gender,Male,27774,50.0432,2,50.0432,49.9568,Acceptable
1,Gender,Female,27726,49.9568,2,50.0432,49.9568,Acceptable
2,Blood Type,A-,6969,12.5568,8,12.5568,12.3910,Acceptable
3,Blood Type,A+,6956,12.5333,8,12.5568,12.3910,Acceptable
4,Blood Type,AB+,6947,12.5171,8,12.5568,12.3910,Acceptable
5,Blood Type,AB-,6945,12.5135,8,12.5568,12.3910,Acceptable
6,Blood Type,B+,6945,12.5135,8,12.5568,12.3910,Acceptable
7,Blood Type,B-,6944,12.5117,8,12.5568,12.3910,Acceptable
8,Blood Type,O+,6917,12.4631,8,12.5568,12.3910,Acceptable
9,Blood Type,O-,6877,12.3910,8,12.5568,12.3910,Acceptable
10,Medical Condition,Arthritis,9308,16.7712,6,16.7712,16.5495,Acceptable
11,Medical Condition,Diabetes,9304,16.7640,6,16.7712,16.5495,Acceptable
12,Medical Condition,Hypertension,9245,16.6577,6,16.7712,16.5495,Acceptable
13,Medical Condition,Obesity,9231,16.6324,6,16.7712,16.5495,Acceptable
14,Medical Condition,Cancer,9227,16.6252,6,16.7712,16.5495,Acceptable
15,Medical Condition,Asthma,9185,16.5495,6,16.7712,16.5495,Acceptable
16,Insurance Provider,Cigna,11249,20.2685,5,20.2685,19.6631,Acceptable
17,Insurance Provider,Medicare,11154,20.0973,5,20.2685,19.6631,Acceptable
18,Insurance Provider,UnitedHealthcare,11125,20.0450,5,20.2685,19.6631,Acceptable
19,Insurance Provider,Blue Cross,11059,19.9261,5,20.2685,19.6631,Acceptable
20,Insurance Provider,Aetna,10913,19.6631,5,20.2685,19.6631,Acceptable
21,Admission Type,Elective,18655,33.6126,3,33.6126,32.9171,Acceptable
22,Admission Type,Urgent,18576,33.4703,3,33.6126,32.9171,Acceptable
23,Admission Type,Emergency,18269,32.9171,3,33.6126,32.9171,Acceptable
24,Medication,Lipitor,11140,20.0721,5,20.0721,19.9423,Acceptable
25,Medication,Ibuprofen,11127,20.0486,5,20.0721,19.9423,Acceptable
26,Medication,Aspirin,11094,19.9892,5,20.0721,19.9423,Acceptable
27,Medication,Paracetamol,11071,19.9477,5,20.0721,19.9423,Acceptable
28,Medication,Penicillin,11068,19.9423,5,20.0721,19.9423,Acceptable
29,Test Results,Abnormal,18627,33.5622,3,33.5622,33.0739,Acceptable
30,Test Results,Normal,18517,33.3640,3,33.5622,33.0739,Acceptable
31,Test Results,Inconclusive,18356,33.0739,3,33.5622,33.0739,Acceptable

In [55]:
# ============================================================
# LAYER 12: RARE CATEGORY ANALYSIS - SHORT VERSION
# Run after Layer 11
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_12_rare_category_analysis():

    layer_path = os.path.join(stage0_path, "12_rare_category_analysis")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer12_rare_category_report.txt")
    rare_csv = os.path.join(layer_path, "rare_category_report.csv")
    summary_json = os.path.join(layer_path, "layer12_rare_category_summary.json")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    def pct(part, total):
        return round((part / total) * 100, 4) if total else 0

    total_rows = int(df.shape[0])
    rare_rows = []
    rare_columns = []

    categorical_df = df.select_dtypes(include=["object", "category", "bool"])

    for col in categorical_df.columns:
        series = categorical_df[col].dropna()
        value_counts = series.value_counts()

        for value, count in value_counts.items():
            percentage = pct(count, len(series))

            if percentage < 1:
                rare_rows.append({
                    "column_name": str(col),
                    "rare_value": str(value),
                    "count": int(count),
                    "percentage_within_non_missing": percentage,
                    "total_non_missing": int(len(series)),
                    "recommendation": "Review before encoding; may need grouping into 'Other'."
                })

        if any(pct(count, len(series)) < 1 for count in value_counts.values):
            rare_columns.append(str(col))

    rare_df = pd.DataFrame(rare_rows)

    if rare_df.empty:
        rare_df = pd.DataFrame({
            "message": ["No rare categories below 1% found."]
        })

    rare_df.to_csv(rare_csv, index=False)

    warnings = []
    recommendations = []

    if rare_columns:
        warnings.append("Rare categories detected in categorical columns.")
        recommendations.append("Consider grouping rare categories into 'Other' before ML.")
        recommendations.append("Avoid one-hot encoding too many rare values without review.")
    else:
        recommendations.append("No rare category issue detected automatically.")

    layer_status = "PASS" if not warnings else "REVIEW_RECOMMENDED"

    summary = {
        "stage": "Layer 12 - Rare Category Analysis",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": int(df.shape[1]),
        "categorical_columns_count": int(len(categorical_df.columns)),
        "columns_with_rare_categories": rare_columns,
        "rare_category_threshold": "less than 1%",
        "layer_status": layer_status,
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "report_txt": report_txt,
            "rare_category_csv": rare_csv,
            "summary_json": summary_json
        },
        "next_action": "Run Layer 13 - Metadata Generator"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    report = f"""
LAYER 12: RARE CATEGORY ANALYSIS REPORT
==================================================

Created On: {datetime.now()}

Dataset Name: {dataset_name}
Dataset Path: {dataset_path}

Layer Status: {layer_status}

Rows: {df.shape[0]}
Columns: {df.shape[1]}

Categorical Columns Count: {len(categorical_df.columns)}

Columns With Rare Categories:
{rare_columns}

Warnings:
{warnings}

Recommendations:
{recommendations}

Files Created:
1. {rare_csv}
2. {summary_json}

Meaning:
Layer 12 checks categorical values that appear in less than 1% of records.

Important:
Rare categories may create weak ML signals or too many encoded columns.
Review them before encoding.

Next Action:
Run Layer 13 - Metadata Generator.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report)

    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 12 UPDATE: RARE CATEGORY ANALYSIS
==================================================

Layer 12 completed on: {datetime.now()}
Layer Status: {layer_status}
Columns With Rare Categories: {rare_columns}
Next Required Stage: Layer 13 - Metadata Generator.
""")

    print("Layer 12 completed successfully.")
    print("Layer Status:", layer_status)
    print("Columns With Rare Categories:", rare_columns)
    print("Files created:")
    print(report_txt)
    print(rare_csv)
    print(summary_json)

    display(rare_df)


# Run Layer 12
run_layer_12_rare_category_analysis()

Layer 12 completed successfully.
Layer Status: REVIEW_RECOMMENDED
Columns With Rare Categories: ['Name', 'Date of Admission', 'Doctor', 'Hospital', 'Discharge Date']
Files created:
d:\Med_data\stage0-launch-pad\12_rare_category_analysis\layer12_rare_category_report.txt
d:\Med_data\stage0-launch-pad\12_rare_category_analysis\rare_category_report.csv
d:\Med_data\stage0-launch-pad\12_rare_category_analysis\layer12_rare_category_summary.json

,column_name,rare_value,count,percentage_within_non_missing,total_non_missing,recommendation
0,Name,DAvId muNoZ,3,0.0054,55500,Review before encoding; may need grouping into...
1,Name,SOnYa aDams,2,0.0036,55500,Review before encoding; may need grouping into...
2,Name,terRY gONZaLeZ,2,0.0036,55500,Review before encoding; may need grouping into...
3,Name,JaCKsON BARbeR,2,0.0036,55500,Review before encoding; may need grouping into...
4,Name,doNALD aViLA,2,0.0036,55500,Review before encoding; may need grouping into...
...,...,...,...,...,...,...
133887,Discharge Date,2019-05-11,2,0.0036,55500,Review before encoding; may need grouping into...
133888,Discharge Date,2024-06-04,2,0.0036,55500,Review before encoding; may need grouping into...
133889,Discharge Date,2024-06-05,2,0.0036,55500,Review before encoding; may need grouping into...
133890,Discharge Date,2019-05-09,1,0.0018,55500,Review before encoding; may need grouping into...
133891,Discharge Date,2024-06-06,1,0.0018,55500,Review before encoding; may need grouping into...

In [57]:
# ============================================================
# LAYER 13: METADATA GENERATOR - SHORT VERSION
# Run after Layer 12
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_13_metadata_generator():

    layer_path = os.path.join(stage0_path, "13_metadata_generator")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer13_metadata_report.txt")
    metadata_json = os.path.join(layer_path, "dataset_metadata.json")
    metadata_questions_txt = os.path.join(layer_path, "metadata_questions_for_user.txt")
    data_dictionary_csv = os.path.join(layer_path, "data_dictionary_template.csv")
    datasheet_txt = os.path.join(layer_path, "dataset_datasheet_draft.txt")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    total_rows = int(df.shape[0])
    total_columns = int(df.shape[1])

    # --------------------------------------------------------
    # Data dictionary template
    # --------------------------------------------------------
    dictionary_rows = []

    for col in df.columns:
        series = df[col]

        dictionary_rows.append({
            "column_name": str(col),
            "current_dtype": str(series.dtype),
            "missing_count": int(series.isna().sum()),
            "unique_values": int(series.nunique(dropna=True)),
            "meaning_to_be_filled_by_user": "",
            "unit_if_any": "",
            "allowed_values_or_range": "",
            "is_sensitive_yes_no": "",
            "use_in_ml_yes_no": "",
            "possible_target_yes_no": "",
            "notes": ""
        })

    dictionary_df = pd.DataFrame(dictionary_rows)
    dictionary_df.to_csv(data_dictionary_csv, index=False)

    # --------------------------------------------------------
    # Metadata JSON
    # --------------------------------------------------------
    metadata = {
        "stage": "Layer 13 - Metadata Generator",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": total_columns,
        "column_names": [str(col) for col in df.columns],
        "metadata_status": "Auto-generated draft; user/domain expert confirmation required.",
        "files_created": {
            "report_txt": report_txt,
            "metadata_json": metadata_json,
            "metadata_questions_txt": metadata_questions_txt,
            "data_dictionary_csv": data_dictionary_csv,
            "datasheet_txt": datasheet_txt
        },
        "next_action": "Run Layer 14 - Data Dictionary and Datasheet Review"
    }

    with open(metadata_json, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=4, ensure_ascii=False, default=str)

    # --------------------------------------------------------
    # Metadata questions
    # --------------------------------------------------------
    questions = """
METADATA QUESTIONS FOR USER / DOMAIN EXPERT
==================================================

1. What does each row represent?
2. What does each column mean?
3. Which column is the real target column for ML?
4. Is the dataset real, synthetic, sampled, or modified?
5. Who collected or created this dataset?
6. When was the dataset collected?
7. What is the source of the dataset?
8. Are there privacy restrictions?
9. Are there sensitive columns?
10. Are there columns that must not be used in ML?
11. Are there known errors or biases?
12. What is the intended ML/AI use?
13. What should not be done with this dataset?
14. Are numeric units clearly defined?
15. Are category meanings clearly defined?
16. Are there legal, ethical, or consent limitations?
"""

    with open(metadata_questions_txt, "w", encoding="utf-8") as f:
        f.write(questions)

    # --------------------------------------------------------
    # Datasheet draft
    # --------------------------------------------------------
    datasheet = f"""
DATASET DATASHEET DRAFT
==================================================

Created On:
{datetime.now()}

Dataset Name:
{dataset_name}

Dataset Path:
{dataset_path}

Rows:
{total_rows}

Columns:
{total_columns}

1. Dataset Purpose:
[User/domain expert must fill]

2. What does one row represent?
[User/domain expert must fill]

3. Dataset Source:
[User/domain expert must fill]

4. Collection Method:
[User/domain expert must fill]

5. Time Period Covered:
[User/domain expert must fill]

6. Intended Use:
[User/domain expert must fill]

7. Not Intended Use:
[User/domain expert must fill]

8. Sensitive or Private Fields:
[User/domain expert must fill]

9. Known Biases or Limitations:
[User/domain expert must fill]

10. Target Column for ML:
[User/domain expert must fill]

11. Columns Not Allowed for ML:
[User/domain expert must fill]

12. Maintenance / Update Plan:
[User/domain expert must fill]

Data Dictionary File:
{data_dictionary_csv}

Important:
This datasheet is a draft. It must be reviewed before ML/AI implementation.
"""

    with open(datasheet_txt, "w", encoding="utf-8") as f:
        f.write(datasheet)

    # --------------------------------------------------------
    # Main report
    # --------------------------------------------------------
    report = f"""
LAYER 13: METADATA GENERATOR REPORT
==================================================

Created On: {datetime.now()}

Dataset Name: {dataset_name}
Dataset Path: {dataset_path}

Rows: {total_rows}
Columns: {total_columns}

Files Created:
1. {metadata_json}
2. {metadata_questions_txt}
3. {data_dictionary_csv}
4. {datasheet_txt}

Meaning:
Layer 13 creates metadata files that help the next ML/AI stage understand
the dataset purpose, source, column meanings, privacy risks, target column,
limitations, and intended use.

Important:
Metadata cannot be fully generated automatically.
User/domain expert confirmation is required.

Next Action:
Run Layer 14 - Data Dictionary and Datasheet Review.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report)

    # --------------------------------------------------------
    # Update root purpose file
    # --------------------------------------------------------
    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 13 UPDATE: METADATA GENERATOR
==================================================

Layer 13 completed on: {datetime.now()}

Metadata files created:
1. dataset_metadata.json
2. metadata_questions_for_user.txt
3. data_dictionary_template.csv
4. dataset_datasheet_draft.txt

Next Required Stage:
Layer 14 - Data Dictionary and Datasheet Review.
""")

    print("Layer 13 completed successfully.")
    print("Files created:")
    print(report_txt)
    print(metadata_json)
    print(metadata_questions_txt)
    print(data_dictionary_csv)
    print(datasheet_txt)

    display(dictionary_df)


# Run Layer 13
run_layer_13_metadata_generator()

Layer 13 completed successfully.
Files created:
d:\Med_data\stage0-launch-pad\13_metadata_generator\layer13_metadata_report.txt
d:\Med_data\stage0-launch-pad\13_metadata_generator\dataset_metadata.json
d:\Med_data\stage0-launch-pad\13_metadata_generator\metadata_questions_for_user.txt
d:\Med_data\stage0-launch-pad\13_metadata_generator\data_dictionary_template.csv
d:\Med_data\stage0-launch-pad\13_metadata_generator\dataset_datasheet_draft.txt

,column_name,current_dtype,missing_count,unique_values,meaning_to_be_filled_by_user,unit_if_any,allowed_values_or_range,is_sensitive_yes_no,use_in_ml_yes_no,possible_target_yes_no,notes
0,Name,object,0,49992,,,,,,,
1,Age,int64,0,77,,,,,,,
2,Gender,object,0,2,,,,,,,
3,Blood Type,object,0,8,,,,,,,
4,Medical Condition,object,0,6,,,,,,,
5,Date of Admission,object,0,1827,,,,,,,
6,Doctor,object,0,40341,,,,,,,
7,Hospital,object,0,39876,,,,,,,
8,Insurance Provider,object,0,5,,,,,,,
9,Billing Amount,float64,0,50000,,,,,,,
10,Room Number,int64,0,400,,,,,,,
11,Admission Type,object,0,3,,,,,,,
12,Discharge Date,object,0,1856,,,,,,,
13,Medication,object,0,5,,,,,,,
14,Test Results,object,0,3,,,,,,,

In [59]:
# ============================================================
# LAYER 14: DATA DICTIONARY & DATASHEET REVIEW - SHORT VERSION
# Run after Layer 13
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_14_dictionary_datasheet_review():

    layer_path = os.path.join(stage0_path, "14_dictionary_datasheet_review")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer14_dictionary_datasheet_review_report.txt")
    review_csv = os.path.join(layer_path, "dictionary_review_checklist.csv")
    missing_metadata_txt = os.path.join(layer_path, "missing_metadata_requirements.txt")
    summary_json = os.path.join(layer_path, "layer14_dictionary_datasheet_review_summary.json")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    total_rows = int(df.shape[0])
    total_columns = int(df.shape[1])

    review_rows = []

    for col in df.columns:
        series = df[col]

        review_rows.append({
            "column_name": str(col),
            "dtype": str(series.dtype),
            "missing_count": int(series.isna().sum()),
            "unique_values": int(series.nunique(dropna=True)),
            "meaning_provided": "No",
            "unit_provided": "No",
            "allowed_values_or_range_provided": "No",
            "sensitivity_confirmed": "No",
            "ml_usage_confirmed": "No",
            "target_status_confirmed": "No",
            "review_status": "Pending User/Domain Expert Review"
        })

    review_df = pd.DataFrame(review_rows)
    review_df.to_csv(review_csv, index=False)

    missing_metadata = f"""
MISSING METADATA REQUIREMENTS
==================================================

Created On: {datetime.now()}

Dataset Name: {dataset_name}
Dataset Path: {dataset_path}

Rows: {total_rows}
Columns: {total_columns}

The following metadata must be confirmed before ML/AI work:

1. Meaning of each column
2. Unit of each numeric column, if applicable
3. Allowed range for numeric columns
4. Allowed category values for categorical columns
5. Sensitive or private columns
6. Columns allowed for ML
7. Columns not allowed for ML
8. Real target column
9. Possible leakage columns
10. Dataset source
11. Dataset collection method
12. Dataset time period
13. Intended use
14. Not intended use
15. Known limitations or bias

Important:
This layer does not change the dataset.
It only checks whether the dataset is documented enough for reliable ML/AI use.
"""

    with open(missing_metadata_txt, "w", encoding="utf-8") as f:
        f.write(missing_metadata)

    warnings = [
        "Column meanings are still pending unless filled by user/domain expert.",
        "Target column must be confirmed before ML.",
        "Sensitive fields and ML-allowed fields must be confirmed."
    ]

    recommendations = [
        "Fill dictionary_review_checklist.csv before model training.",
        "Confirm target column and leakage-risk columns manually.",
        "Use this layer as a documentation checkpoint before feature engineering."
    ]

    summary = {
        "stage": "Layer 14 - Data Dictionary and Datasheet Review",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": total_rows,
        "columns": total_columns,
        "layer_status": "REVIEW_REQUIRED",
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "report_txt": report_txt,
            "review_csv": review_csv,
            "missing_metadata_txt": missing_metadata_txt,
            "summary_json": summary_json
        },
        "next_action": "Run Layer 15 - Governance, PII and Responsible AI Checklist"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    report = f"""
LAYER 14: DATA DICTIONARY AND DATASHEET REVIEW REPORT
==================================================

Created On: {datetime.now()}

Dataset Name: {dataset_name}
Dataset Path: {dataset_path}

Layer Status: REVIEW_REQUIRED

Rows: {total_rows}
Columns: {total_columns}

Files Created:
1. {review_csv}
2. {missing_metadata_txt}
3. {summary_json}

Meaning:
Layer 14 checks whether the dataset has enough documentation for ML/AI work.
It prepares a review checklist for column meaning, units, valid values,
sensitivity, ML usability, and target-column confirmation.

Warnings:
{warnings}

Recommendations:
{recommendations}

Important:
ML should not start until key metadata is confirmed.

Next Action:
Run Layer 15 - Governance, PII and Responsible AI Checklist.
"""

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report)

    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(f"""

==================================================
LAYER 14 UPDATE: DATA DICTIONARY AND DATASHEET REVIEW
==================================================

Layer 14 completed on: {datetime.now()}
Layer Status: REVIEW_REQUIRED
Next Required Stage: Layer 15 - Governance, PII and Responsible AI Checklist.
""")

    print("Layer 14 completed successfully.")
    print("Layer Status: REVIEW_REQUIRED")
    print("Files created:")
    print(report_txt)
    print(review_csv)
    print(missing_metadata_txt)
    print(summary_json)

    display(review_df)


# Run Layer 14
run_layer_14_dictionary_datasheet_review()

Layer 14 completed successfully.
Layer Status: REVIEW_REQUIRED
Files created:
d:\Med_data\stage0-launch-pad\14_dictionary_datasheet_review\layer14_dictionary_datasheet_review_report.txt
d:\Med_data\stage0-launch-pad\14_dictionary_datasheet_review\dictionary_review_checklist.csv
d:\Med_data\stage0-launch-pad\14_dictionary_datasheet_review\missing_metadata_requirements.txt
d:\Med_data\stage0-launch-pad\14_dictionary_datasheet_review\layer14_dictionary_datasheet_review_summary.json

,column_name,dtype,missing_count,unique_values,meaning_provided,unit_provided,allowed_values_or_range_provided,sensitivity_confirmed,ml_usage_confirmed,target_status_confirmed,review_status
0,Name,object,0,49992,No,No,No,No,No,No,Pending User/Domain Expert Review
1,Age,int64,0,77,No,No,No,No,No,No,Pending User/Domain Expert Review
2,Gender,object,0,2,No,No,No,No,No,No,Pending User/Domain Expert Review
3,Blood Type,object,0,8,No,No,No,No,No,No,Pending User/Domain Expert Review
4,Medical Condition,object,0,6,No,No,No,No,No,No,Pending User/Domain Expert Review
5,Date of Admission,object,0,1827,No,No,No,No,No,No,Pending User/Domain Expert Review
6,Doctor,object,0,40341,No,No,No,No,No,No,Pending User/Domain Expert Review
7,Hospital,object,0,39876,No,No,No,No,No,No,Pending User/Domain Expert Review
8,Insurance Provider,object,0,5,No,No,No,No,No,No,Pending User/Domain Expert Review
9,Billing Amount,float64,0,50000,No,No,No,No,No,No,Pending User/Domain Expert Review
10,Room Number,int64,0,400,No,No,No,No,No,No,Pending User/Domain Expert Review
11,Admission Type,object,0,3,No,No,No,No,No,No,Pending User/Domain Expert Review
12,Discharge Date,object,0,1856,No,No,No,No,No,No,Pending User/Domain Expert Review
13,Medication,object,0,5,No,No,No,No,No,No,Pending User/Domain Expert Review
14,Test Results,object,0,3,No,No,No,No,No,No,Pending User/Domain Expert Review

In [61]:
# ============================================================
# LAYER 15: GOVERNANCE, PII & RESPONSIBLE AI - SHORT VERSION
# Run after Layer 14
#
# Required variables:
# df, dataset_path, dataset_name, stage0_path
# ============================================================

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_15_governance_pii_responsible_ai():

    layer_path = os.path.join(stage0_path, "15_governance_pii_responsible_ai")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer15_governance_report.txt")
    pii_csv = os.path.join(layer_path, "pii_sensitive_scan.csv")
    checklist_txt = os.path.join(layer_path, "responsible_ai_checklist.txt")
    summary_json = os.path.join(layer_path, "layer15_summary.json")

    root_purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    pii_keywords = [
        "name", "email", "phone", "mobile", "address", "cnic",
        "passport", "ssn", "id", "patient", "student", "customer",
        "employee", "account", "iban", "card"
    ]

    sensitive_keywords = [
        "age", "gender", "sex", "dob", "birth", "religion",
        "race", "ethnicity", "blood", "medical", "condition",
        "diagnosis", "disease", "medication", "salary", "income",
        "test", "result"
    ]

    scan_rows = []
    pii_cols = []
    sensitive_cols = []

    for col in df.columns:
        col_text = str(col).lower()

        is_pii = any(word in col_text for word in pii_keywords)
        is_sensitive = any(word in col_text for word in sensitive_keywords)

        if is_pii:
            pii_cols.append(str(col))

        if is_sensitive:
            sensitive_cols.append(str(col))

        scan_rows.append({
            "column_name": str(col),
            "dtype": str(df[col].dtype),
            "possible_pii": is_pii,
            "possible_sensitive": is_sensitive,
            "manual_review_required": is_pii or is_sensitive
        })

    scan_df = pd.DataFrame(scan_rows)
    scan_df.to_csv(pii_csv, index=False)

    warnings = []
    recommendations = []

    if pii_cols:
        warnings.append("Possible PII columns detected.")
        recommendations.append("Mask, remove, anonymize, or approve PII before ML.")

    if sensitive_cols:
        warnings.append("Possible sensitive columns detected.")
        recommendations.append("Review fairness, ethics, and privacy before ML.")

    if not warnings:
        recommendations.append("No obvious PII detected automatically. Manual review is still required.")

    layer_status = "REVIEW_REQUIRED" if warnings else "PASS_WITH_MANUAL_REVIEW"

    checklist = (
        "RESPONSIBLE AI CHECKLIST\n"
        "========================\n\n"
        "1. Confirm dataset ownership.\n"
        "2. Confirm permission to use data.\n"
        "3. Review PII columns.\n"
        "4. Review sensitive columns.\n"
        "5. Remove or mask restricted fields.\n"
        "6. Confirm target column is ethical.\n"
        "7. Check leakage-risk columns.\n"
        "8. Document limitations and bias.\n"
        "9. Use human review for high-risk decisions.\n"
        "10. Do not start ML until governance review is complete.\n"
    )

    with open(checklist_txt, "w", encoding="utf-8") as f:
        f.write(checklist)

    summary = {
        "stage": "Layer 15 - Governance, PII and Responsible AI",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "layer_status": layer_status,
        "possible_pii_columns": pii_cols,
        "possible_sensitive_columns": sensitive_cols,
        "warnings": warnings,
        "recommendations": recommendations,
        "files_created": {
            "report_txt": report_txt,
            "pii_csv": pii_csv,
            "checklist_txt": checklist_txt,
            "summary_json": summary_json
        },
        "next_action": "Run Layer 16 - Feature Engineering Suggestions"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    report = (
        "LAYER 15: GOVERNANCE, PII AND RESPONSIBLE AI REPORT\n"
        "==================================================\n\n"
        f"Created On: {datetime.now()}\n"
        f"Dataset Name: {dataset_name}\n"
        f"Dataset Path: {dataset_path}\n\n"
        f"Layer Status: {layer_status}\n"
        f"Rows: {df.shape[0]}\n"
        f"Columns: {df.shape[1]}\n\n"
        f"Possible PII Columns: {pii_cols}\n"
        f"Possible Sensitive Columns: {sensitive_cols}\n\n"
        f"Warnings: {warnings}\n"
        f"Recommendations: {recommendations}\n\n"
        "Files Created:\n"
        f"1. {pii_csv}\n"
        f"2. {checklist_txt}\n"
        f"3. {summary_json}\n\n"
        "Next Action: Run Layer 16 - Feature Engineering Suggestions.\n"
    )

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write(report)

    with open(root_purpose_file, "a", encoding="utf-8") as f:
        f.write(
            "\n\nLAYER 15 UPDATE: GOVERNANCE, PII AND RESPONSIBLE AI\n"
            "==================================================\n"
            f"Completed On: {datetime.now()}\n"
            f"Layer Status: {layer_status}\n"
            f"Possible PII Columns: {pii_cols}\n"
            f"Possible Sensitive Columns: {sensitive_cols}\n"
            "Next Required Stage: Layer 16 - Feature Engineering Suggestions.\n"
        )

    print("Layer 15 completed successfully.")
    print("Layer Status:", layer_status)
    print("Possible PII Columns:", pii_cols)
    print("Possible Sensitive Columns:", sensitive_cols)
    print("Files created:")
    print(report_txt)
    print(pii_csv)
    print(checklist_txt)
    print(summary_json)

    display(scan_df)


# Run Layer 15
run_layer_15_governance_pii_responsible_ai()

Layer 15 completed successfully.
Layer Status: REVIEW_REQUIRED
Possible PII Columns: ['Name', 'Insurance Provider']
Possible Sensitive Columns: ['Age', 'Gender', 'Blood Type', 'Medical Condition', 'Medication', 'Test Results']
Files created:
d:\Med_data\stage0-launch-pad\15_governance_pii_responsible_ai\layer15_governance_report.txt
d:\Med_data\stage0-launch-pad\15_governance_pii_responsible_ai\pii_sensitive_scan.csv
d:\Med_data\stage0-launch-pad\15_governance_pii_responsible_ai\responsible_ai_checklist.txt
d:\Med_data\stage0-launch-pad\15_governance_pii_responsible_ai\layer15_summary.json

,column_name,dtype,possible_pii,possible_sensitive,manual_review_required
0,Name,object,True,False,True
1,Age,int64,False,True,True
2,Gender,object,False,True,True
3,Blood Type,object,False,True,True
4,Medical Condition,object,False,True,True
5,Date of Admission,object,False,False,False
6,Doctor,object,False,False,False
7,Hospital,object,False,False,False
8,Insurance Provider,object,True,False,True
9,Billing Amount,float64,False,False,False
10,Room Number,int64,False,False,False
11,Admission Type,object,False,False,False
12,Discharge Date,object,False,False,False
13,Medication,object,False,True,True
14,Test Results,object,False,True,True

In [63]:
# LAYER 16: FEATURE ENGINEERING SUGGESTIONS
# Required: df, dataset_path, dataset_name, stage0_path

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_16_feature_engineering_suggestions():

    layer_path = os.path.join(stage0_path, "16_feature_engineering_suggestions")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer16_report.txt")
    suggestions_csv = os.path.join(layer_path, "feature_suggestions.csv")
    summary_json = os.path.join(layer_path, "layer16_summary.json")
    purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    rows = []

    for col in df.columns:
        s = df[col]
        col_name = str(col)
        col_low = col_name.lower()
        dtype = str(s.dtype)
        unique_count = int(s.nunique(dropna=True))
        missing_pct = round(float(s.isna().mean() * 100), 4)

        if "date" in col_low or "time" in col_low:
            rows.append({
                "column_name": col_name,
                "dtype": dtype,
                "suggestion_type": "Date",
                "suggestion": "Extract year, month, day, weekday, duration.",
                "priority": "High"
            })

        elif pd.api.types.is_numeric_dtype(s):
            rows.append({
                "column_name": col_name,
                "dtype": dtype,
                "suggestion_type": "Numeric",
                "suggestion": "Consider scaling, binning, missing flag, outlier review.",
                "priority": "Medium"
            })

        elif s.dtype == "object" and unique_count <= 20:
            rows.append({
                "column_name": col_name,
                "dtype": dtype,
                "suggestion_type": "Categorical",
                "suggestion": "Consider one-hot encoding or label encoding.",
                "priority": "High"
            })

        elif s.dtype == "object" and unique_count > 20:
            rows.append({
                "column_name": col_name,
                "dtype": dtype,
                "suggestion_type": "High Cardinality",
                "suggestion": "Review grouping, rare labels, frequency encoding.",
                "priority": "Medium"
            })

        if missing_pct > 0:
            rows.append({
                "column_name": col_name,
                "dtype": dtype,
                "suggestion_type": "Missing Flag",
                "suggestion": "Create missing indicator if useful.",
                "priority": "Medium"
            })

    result_df = pd.DataFrame(rows)

    if result_df.empty:
        result_df = pd.DataFrame({
            "message": ["No feature suggestions generated."]
        })

    result_df.to_csv(suggestions_csv, index=False)

    summary = {
        "stage": "Layer 16 - Feature Engineering Suggestions",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "suggestions_file": suggestions_csv,
        "next_action": "Run Layer 17 - ML Readiness Score"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False)

    lines = [
        "LAYER 16: FEATURE ENGINEERING SUGGESTIONS",
        "=" * 45,
        "",
        "Created On: " + str(datetime.now()),
        "Dataset Name: " + str(dataset_name),
        "Dataset Path: " + str(dataset_path),
        "Rows: " + str(df.shape[0]),
        "Columns: " + str(df.shape[1]),
        "",
        "Files Created:",
        "1. " + suggestions_csv,
        "2. " + summary_json,
        "",
        "Next Action: Run Layer 17 - ML Readiness Score."
    ]

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    with open(purpose_file, "a", encoding="utf-8") as f:
        f.write("\n\nLAYER 16 COMPLETED\n")
        f.write("Next Required Stage: Layer 17 - ML Readiness Score.\n")

    print("Layer 16 completed successfully.")
    print(report_txt)
    print(suggestions_csv)
    print(summary_json)

    display(result_df)


run_layer_16_feature_engineering_suggestions()

Layer 16 completed successfully.
d:\Med_data\stage0-launch-pad\16_feature_engineering_suggestions\layer16_report.txt
d:\Med_data\stage0-launch-pad\16_feature_engineering_suggestions\feature_suggestions.csv
d:\Med_data\stage0-launch-pad\16_feature_engineering_suggestions\layer16_summary.json

,column_name,dtype,suggestion_type,suggestion,priority
0,Name,object,High Cardinality,"Review grouping, rare labels, frequency encoding.",Medium
1,Age,int64,Numeric,"Consider scaling, binning, missing flag, outli...",Medium
2,Gender,object,Categorical,Consider one-hot encoding or label encoding.,High
3,Blood Type,object,Categorical,Consider one-hot encoding or label encoding.,High
4,Medical Condition,object,Categorical,Consider one-hot encoding or label encoding.,High
5,Date of Admission,object,Date,"Extract year, month, day, weekday, duration.",High
6,Doctor,object,High Cardinality,"Review grouping, rare labels, frequency encoding.",Medium
7,Hospital,object,High Cardinality,"Review grouping, rare labels, frequency encoding.",Medium
8,Insurance Provider,object,Categorical,Consider one-hot encoding or label encoding.,High
9,Billing Amount,float64,Numeric,"Consider scaling, binning, missing flag, outli...",Medium
10,Room Number,int64,Numeric,"Consider scaling, binning, missing flag, outli...",Medium
11,Admission Type,object,Categorical,Consider one-hot encoding or label encoding.,High
12,Discharge Date,object,Date,"Extract year, month, day, weekday, duration.",High
13,Medication,object,Categorical,Consider one-hot encoding or label encoding.,High
14,Test Results,object,Categorical,Consider one-hot encoding or label encoding.,High

In [65]:
# LAYER 17: ML READINESS SCORE
# Required: df, dataset_path, dataset_name, stage0_path

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_17_ml_readiness_score():

    layer_path = os.path.join(stage0_path, "17_ml_readiness_score")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer17_report.txt")
    readiness_csv = os.path.join(layer_path, "ml_readiness_score.csv")
    summary_json = os.path.join(layer_path, "layer17_summary.json")
    purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    rows_count = int(df.shape[0])
    cols_count = int(df.shape[1])

    missing_pct = round(float(df.isna().mean().mean() * 100), 4)
    duplicate_count = int(df.duplicated().sum())
    duplicate_pct = round((duplicate_count / rows_count) * 100, 4) if rows_count else 0

    fully_null_cols = [str(c) for c in df.columns if df[c].isna().all()]
    constant_cols = [str(c) for c in df.columns if df[c].nunique(dropna=True) <= 1]

    numeric_cols = [str(c) for c in df.select_dtypes(include=["number"]).columns]
    categorical_cols = [str(c) for c in df.select_dtypes(include=["object", "category", "bool"]).columns]

    target_keywords = ["target", "label", "class", "result", "outcome", "condition", "status", "diagnosis"]
    possible_targets = []

    for col in df.columns:
        col_text = str(col).lower()
        unique_count = df[col].nunique(dropna=True)

        if unique_count > 1 and unique_count <= 50:
            if any(k in col_text for k in target_keywords):
                possible_targets.append(str(col))

    pii_keywords = ["name", "email", "phone", "address", "cnic", "passport", "id", "patient", "customer"]
    possible_pii_cols = [str(c) for c in df.columns if any(k in str(c).lower() for k in pii_keywords)]

    score = 100
    issues = []

    if rows_count < 1000:
        score -= 15
        issues.append("Low row count")

    if cols_count < 2:
        score -= 20
        issues.append("Too few columns")

    if missing_pct > 30:
        score -= 20
        issues.append("High missing values")
    elif missing_pct > 10:
        score -= 10
        issues.append("Moderate missing values")

    if duplicate_pct > 10:
        score -= 15
        issues.append("High duplicate rows")
    elif duplicate_pct > 0:
        score -= 5
        issues.append("Duplicate rows found")

    if fully_null_cols:
        score -= 10
        issues.append("Fully null columns found")

    if constant_cols:
        score -= 5
        issues.append("Constant columns found")

    if not possible_targets:
        score -= 15
        issues.append("No obvious target column found")

    if possible_pii_cols:
        score -= 10
        issues.append("Possible PII columns found")

    score = max(0, min(100, score))

    if score >= 80:
        status = "GOOD_FOR_NEXT_STAGE"
    elif score >= 60:
        status = "NEEDS_REVIEW_BEFORE_ML"
    else:
        status = "NOT_READY_FOR_ML"

    readiness = {
        "dataset_name": dataset_name,
        "rows": rows_count,
        "columns": cols_count,
        "ml_readiness_score": score,
        "readiness_status": status,
        "missing_percentage": missing_pct,
        "duplicate_rows": duplicate_count,
        "duplicate_percentage": duplicate_pct,
        "numeric_columns_count": len(numeric_cols),
        "categorical_columns_count": len(categorical_cols),
        "fully_null_columns": fully_null_cols,
        "constant_columns": constant_cols,
        "possible_target_columns": possible_targets,
        "possible_pii_columns": possible_pii_cols,
        "issues": issues
    }

    readiness_df = pd.DataFrame([readiness])
    readiness_df.to_csv(readiness_csv, index=False)

    summary = {
        "stage": "Layer 17 - ML Readiness Score",
        "created_on": str(datetime.now()),
        "dataset_path": dataset_path,
        "readiness": readiness,
        "files_created": {
            "report_txt": report_txt,
            "readiness_csv": readiness_csv,
            "summary_json": summary_json
        },
        "next_action": "Run Layer 18 - Possible ML Problem Definitions"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    lines = [
        "LAYER 17: ML READINESS SCORE",
        "=" * 35,
        "",
        "Created On: " + str(datetime.now()),
        "Dataset Name: " + str(dataset_name),
        "Dataset Path: " + str(dataset_path),
        "Rows: " + str(rows_count),
        "Columns: " + str(cols_count),
        "ML Readiness Score: " + str(score),
        "Readiness Status: " + status,
        "",
        "Issues:",
        str(issues),
        "",
        "Possible Target Columns:",
        str(possible_targets),
        "",
        "Possible PII Columns:",
        str(possible_pii_cols),
        "",
        "Files Created:",
        "1. " + readiness_csv,
        "2. " + summary_json,
        "",
        "Next Action: Run Layer 18 - Possible ML Problem Definitions."
    ]

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    with open(purpose_file, "a", encoding="utf-8") as f:
        f.write("\n\nLAYER 17 COMPLETED\n")
        f.write("ML Readiness Score: " + str(score) + "\n")
        f.write("Readiness Status: " + status + "\n")
        f.write("Next Required Stage: Layer 18 - Possible ML Problem Definitions.\n")

    print("Layer 17 completed successfully.")
    print("ML Readiness Score:", score)
    print("Readiness Status:", status)
    print(report_txt)
    print(readiness_csv)
    print(summary_json)

    display(readiness_df)


run_layer_17_ml_readiness_score()

Layer 17 completed successfully.
ML Readiness Score: 85
Readiness Status: GOOD_FOR_NEXT_STAGE
d:\Med_data\stage0-launch-pad\17_ml_readiness_score\layer17_report.txt
d:\Med_data\stage0-launch-pad\17_ml_readiness_score\ml_readiness_score.csv
d:\Med_data\stage0-launch-pad\17_ml_readiness_score\layer17_summary.json

,dataset_name,rows,columns,ml_readiness_score,readiness_status,missing_percentage,duplicate_rows,duplicate_percentage,numeric_columns_count,categorical_columns_count,fully_null_columns,constant_columns,possible_target_columns,possible_pii_columns,issues
0,dataset.csv,55500,15,85,GOOD_FOR_NEXT_STAGE,0.0,534,0.9622,3,12,[],[],"[Medical Condition, Test Results]","[Name, Insurance Provider]","[Duplicate rows found, Possible PII columns fo..."

In [67]:
# LAYER 18: ML PROBLEM DEFINITIONS
# Required: df, dataset_path, dataset_name, stage0_path

import os, json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_18_ml_problem_definitions():

    layer_path = os.path.join(stage0_path, "18_ml_problem_definitions")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer18_report.txt")
    problems_csv = os.path.join(layer_path, "ml_problem_definitions.csv")
    summary_json = os.path.join(layer_path, "layer18_summary.json")
    purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    target_words = ["target", "label", "class", "result", "outcome", "condition", "status", "diagnosis"]
    date_words = ["date", "time", "year", "month"]

    numeric_cols = list(df.select_dtypes(include=["number"]).columns)
    categorical_cols = list(df.select_dtypes(include=["object", "category", "bool"]).columns)

    rows = []
    possible_targets = []

    for col in df.columns:
        col_name = str(col)
        col_low = col_name.lower()
        unique_count = df[col].nunique(dropna=True)
        missing_pct = df[col].isna().mean() * 100

        if missing_pct < 40 and unique_count > 1:
            if any(w in col_low for w in target_words):
                possible_targets.append(col_name)

                if unique_count <= 30:
                    rows.append([col_name, "Classification", "Target-like column with limited classes", "F1, Recall, Precision, Accuracy"])

                elif pd.api.types.is_numeric_dtype(df[col]):
                    rows.append([col_name, "Regression", "Target-like numeric column", "MAE, RMSE, R2"])

    if len(numeric_cols) >= 2:
        rows.append(["No target", "Clustering", "Numeric columns available", "Silhouette score"])
        rows.append(["No target", "Anomaly Detection", "Numeric columns available", "Domain validation"])

    date_cols = [str(c) for c in df.columns if any(w in str(c).lower() for w in date_words)]

    if date_cols:
        rows.append(["Depends", "Time-based Analysis", "Date/time column detected", "Depends on task"])

    if not rows:
        rows.append(["Not confirmed", "Exploratory Analysis", "No clear ML target found", "Summary statistics"])

    problems_df = pd.DataFrame(rows, columns=[
        "possible_target",
        "problem_type",
        "reason",
        "recommended_metrics"
    ])

    problems_df.to_csv(problems_csv, index=False)

    summary = {
        "stage": "Layer 18 - ML Problem Definitions",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "numeric_columns_count": len(numeric_cols),
        "categorical_columns_count": len(categorical_cols),
        "possible_target_columns": possible_targets,
        "date_columns": date_cols,
        "next_action": "Run Layer 19 - Research Recommendations"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    report_lines = [
        "LAYER 18: ML PROBLEM DEFINITIONS",
        "================================",
        "Created On: " + str(datetime.now()),
        "Dataset Name: " + str(dataset_name),
        "Rows: " + str(df.shape[0]),
        "Columns: " + str(df.shape[1]),
        "Possible Targets: " + str(possible_targets),
        "Files:",
        problems_csv,
        summary_json,
        "Next: Layer 19 - Research Recommendations"
    ]

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))

    with open(purpose_file, "a", encoding="utf-8") as f:
        f.write("\n\nLAYER 18 COMPLETED\n")
        f.write("Next: Layer 19 - Research Recommendations\n")

    print("Layer 18 completed.")
    print(report_txt)
    print(problems_csv)
    print(summary_json)

    display(problems_df)


run_layer_18_ml_problem_definitions()

Layer 18 completed.
d:\Med_data\stage0-launch-pad\18_ml_problem_definitions\layer18_report.txt
d:\Med_data\stage0-launch-pad\18_ml_problem_definitions\ml_problem_definitions.csv
d:\Med_data\stage0-launch-pad\18_ml_problem_definitions\layer18_summary.json

,possible_target,problem_type,reason,recommended_metrics
0,Medical Condition,Classification,Target-like column with limited classes,"F1, Recall, Precision, Accuracy"
1,Test Results,Classification,Target-like column with limited classes,"F1, Recall, Precision, Accuracy"
2,No target,Clustering,Numeric columns available,Silhouette score
3,No target,Anomaly Detection,Numeric columns available,Domain validation
4,Depends,Time-based Analysis,Date/time column detected,Depends on task

In [69]:
# LAYER 19: RESEARCH RECOMMENDATIONS
# Required: df, dataset_path, dataset_name, stage0_path

import os, json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_19_research_recommendations():

    layer_path = os.path.join(stage0_path, "19_research_recommendations")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer19_report.txt")
    research_csv = os.path.join(layer_path, "research_recommendations.csv")
    summary_json = os.path.join(layer_path, "layer19_summary.json")
    purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    numeric_cols = [str(c) for c in df.select_dtypes(include=["number"]).columns]
    cat_cols = [str(c) for c in df.select_dtypes(include=["object", "category", "bool"]).columns]

    target_words = ["target", "label", "result", "outcome", "condition", "status", "diagnosis"]
    date_words = ["date", "time", "year", "month"]

    possible_targets = [
        str(c) for c in df.columns
        if any(w in str(c).lower() for w in target_words)
        and df[c].nunique(dropna=True) > 1
    ]

    date_cols = [
        str(c) for c in df.columns
        if any(w in str(c).lower() for w in date_words)
    ]

    rows = []

    if possible_targets:
        for target in possible_targets:
            rows.append([
                "Predictive Modeling",
                "Can we predict " + target + " using available features?",
                target,
                "Classification or regression",
                "Needs target and leakage confirmation"
            ])

    if len(numeric_cols) >= 2:
        rows.append([
            "Statistical Relationship",
            "Which numeric variables have strong relationships?",
            "Numeric columns",
            "Correlation and regression analysis",
            "Correlation does not prove causation"
        ])

        rows.append([
            "Patient / Record Segmentation",
            "Can records be grouped into meaningful clusters?",
            "No target required",
            "Clustering",
            "Clusters need domain interpretation"
        ])

    if cat_cols:
        rows.append([
            "Category Pattern Analysis",
            "Which categories appear most often and how do they differ?",
            "Categorical columns",
            "Frequency and group comparison",
            "Category meanings must be confirmed"
        ])

    if date_cols:
        rows.append([
            "Time-Based Analysis",
            "Do patterns change over time?",
            "Date/time columns",
            "Trend or time-aware analysis",
            "Date format must be validated"
        ])

    if not rows:
        rows.append([
            "Exploratory Research",
            "What are the main patterns in this dataset?",
            "Not confirmed",
            "EDA",
            "More metadata required"
        ])

    research_df = pd.DataFrame(rows, columns=[
        "research_area",
        "possible_research_question",
        "focus_column",
        "suggested_method",
        "limitation"
    ])

    research_df.to_csv(research_csv, index=False)

    summary = {
        "stage": "Layer 19 - Research Recommendations",
        "created_on": str(datetime.now()),
        "dataset_name": dataset_name,
        "dataset_path": dataset_path,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "numeric_columns_count": len(numeric_cols),
        "categorical_columns_count": len(cat_cols),
        "possible_target_columns": possible_targets,
        "date_columns": date_cols,
        "next_action": "Run Layer 20 - Next Stage Prompt Generator"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    report_lines = [
        "LAYER 19: RESEARCH RECOMMENDATIONS",
        "==================================",
        "Created On: " + str(datetime.now()),
        "Dataset Name: " + str(dataset_name),
        "Rows: " + str(df.shape[0]),
        "Columns: " + str(df.shape[1]),
        "Possible Targets: " + str(possible_targets),
        "Files:",
        research_csv,
        summary_json,
        "Next: Layer 20 - Next Stage Prompt Generator"
    ]

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))

    with open(purpose_file, "a", encoding="utf-8") as f:
        f.write("\n\nLAYER 19 COMPLETED\n")
        f.write("Next: Layer 20 - Next Stage Prompt Generator\n")

    print("Layer 19 completed.")
    print(report_txt)
    print(research_csv)
    print(summary_json)

    display(research_df)


run_layer_19_research_recommendations()

Layer 19 completed.
d:\Med_data\stage0-launch-pad\19_research_recommendations\layer19_report.txt
d:\Med_data\stage0-launch-pad\19_research_recommendations\research_recommendations.csv
d:\Med_data\stage0-launch-pad\19_research_recommendations\layer19_summary.json

,research_area,possible_research_question,focus_column,suggested_method,limitation
0,Predictive Modeling,Can we predict Medical Condition using availab...,Medical Condition,Classification or regression,Needs target and leakage confirmation
1,Predictive Modeling,Can we predict Test Results using available fe...,Test Results,Classification or regression,Needs target and leakage confirmation
2,Statistical Relationship,Which numeric variables have strong relationsh...,Numeric columns,Correlation and regression analysis,Correlation does not prove causation
3,Patient / Record Segmentation,Can records be grouped into meaningful clusters?,No target required,Clustering,Clusters need domain interpretation
4,Category Pattern Analysis,Which categories appear most often and how do ...,Categorical columns,Frequency and group comparison,Category meanings must be confirmed
5,Time-Based Analysis,Do patterns change over time?,Date/time columns,Trend or time-aware analysis,Date format must be validated

In [71]:
# LAYER 20: NEXT STAGE PROMPT GENERATOR
# Required: df, dataset_path, dataset_name, stage0_path

import os
import json
from datetime import datetime


def run_layer_20_next_stage_prompt_generator():

    layer_path = os.path.join(stage0_path, "20_next_stage_prompt")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer20_report.txt")
    prompt_txt = os.path.join(layer_path, "next_stage_ml_prompt.txt")
    contract_json = os.path.join(layer_path, "next_stage_contract.json")
    purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    numeric_cols = [str(c) for c in df.select_dtypes(include=["number"]).columns]
    cat_cols = [str(c) for c in df.select_dtypes(include=["object", "category", "bool"]).columns]

    target_words = ["target", "label", "class", "result", "outcome", "condition", "status", "diagnosis"]

    possible_targets = []
    for c in df.columns:
        c_text = str(c).lower()
        if any(w in c_text for w in target_words):
            if df[c].nunique(dropna=True) > 1:
                possible_targets.append(str(c))

    missing_pct = round(float(df.isna().mean().mean() * 100), 4)
    duplicate_rows = int(df.duplicated().sum())

    prompt_lines = []
    prompt_lines.append("NEXT STAGE ML PROMPT")
    prompt_lines.append("Dataset: " + str(dataset_name))
    prompt_lines.append("Path: " + str(dataset_path))
    prompt_lines.append("Rows: " + str(df.shape[0]))
    prompt_lines.append("Columns: " + str(df.shape[1]))
    prompt_lines.append("Numeric columns: " + str(numeric_cols))
    prompt_lines.append("Categorical columns: " + str(cat_cols))
    prompt_lines.append("Possible targets: " + str(possible_targets))
    prompt_lines.append("Missing percentage: " + str(missing_pct))
    prompt_lines.append("Duplicate rows: " + str(duplicate_rows))
    prompt_lines.append("")
    prompt_lines.append("Tasks for next stage:")
    prompt_lines.append("1. Read Stage0 reports.")
    prompt_lines.append("2. Confirm target column.")
    prompt_lines.append("3. Check PII and leakage columns.")
    prompt_lines.append("4. Define ML problem.")
    prompt_lines.append("5. Recommend cleaning plan.")
    prompt_lines.append("6. Recommend feature plan.")
    prompt_lines.append("7. Recommend models and metrics.")
    prompt_lines.append("")
    prompt_lines.append("Rules:")
    prompt_lines.append("Do not modify raw data.")
    prompt_lines.append("Do not train model before target confirmation.")

    with open(prompt_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(prompt_lines))

    contract = {
        "stage": "Layer 20 - Next Stage Prompt Generator",
        "created_on": str(datetime.now()),
        "dataset_name": str(dataset_name),
        "dataset_path": str(dataset_path),
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "numeric_columns": numeric_cols,
        "categorical_columns": cat_cols,
        "possible_targets": possible_targets,
        "missing_percentage": missing_pct,
        "duplicate_rows": duplicate_rows,
        "prompt_file": prompt_txt,
        "next_action": "Layer 21 - Final Stage0 Summary"
    }

    with open(contract_json, "w", encoding="utf-8") as f:
        json.dump(contract, f, indent=4, ensure_ascii=False, default=str)

    report_lines = []
    report_lines.append("LAYER 20 COMPLETED")
    report_lines.append("Dataset: " + str(dataset_name))
    report_lines.append("Prompt file: " + prompt_txt)
    report_lines.append("Contract file: " + contract_json)
    report_lines.append("Next: Layer 21 - Final Stage0 Summary")

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))

    with open(purpose_file, "a", encoding="utf-8") as f:
        f.write("\n\nLAYER 20 COMPLETED\n")
        f.write("Next: Layer 21 - Final Stage0 Summary\n")

    print("Layer 20 completed.")
    print(report_txt)
    print(prompt_txt)
    print(contract_json)


run_layer_20_next_stage_prompt_generator()

Layer 20 completed.
d:\Med_data\stage0-launch-pad\20_next_stage_prompt\layer20_report.txt
d:\Med_data\stage0-launch-pad\20_next_stage_prompt\next_stage_ml_prompt.txt
d:\Med_data\stage0-launch-pad\20_next_stage_prompt\next_stage_contract.json

In [73]:
# LAYER 21: FINAL STAGE0 SUMMARY
# Required: df, dataset_path, dataset_name, stage0_path

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_layer_21_final_stage0_summary():

    layer_path = os.path.join(stage0_path, "21_final_stage0_summary")
    os.makedirs(layer_path, exist_ok=True)

    report_txt = os.path.join(layer_path, "layer21_final_summary.txt")
    index_csv = os.path.join(layer_path, "stage0_file_index.csv")
    contract_json = os.path.join(layer_path, "stage0_final_contract.json")
    purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    file_rows = []

    for root, dirs, files in os.walk(stage0_path):
        for file in files:
            full_path = os.path.join(root, file)
            file_rows.append({
                "folder": os.path.relpath(root, stage0_path),
                "file_name": file,
                "full_path": full_path
            })

    index_df = pd.DataFrame(file_rows)
    index_df.to_csv(index_csv, index=False)

    numeric_cols = [str(c) for c in df.select_dtypes(include=["number"]).columns]
    cat_cols = [str(c) for c in df.select_dtypes(include=["object", "category", "bool"]).columns]

    final_contract = {
        "stage": "Layer 21 - Final Stage0 Summary",
        "created_on": str(datetime.now()),
        "dataset_name": str(dataset_name),
        "dataset_path": str(dataset_path),
        "stage0_path": str(stage0_path),
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "numeric_columns_count": len(numeric_cols),
        "categorical_columns_count": len(cat_cols),
        "stage0_files_count": len(index_df),
        "stage0_status": "Completed",
        "next_recommended_action": "Use next_stage_ml_prompt.txt for ML problem definition."
    }

    with open(contract_json, "w", encoding="utf-8") as f:
        json.dump(final_contract, f, indent=4, ensure_ascii=False, default=str)

    lines = []
    lines.append("LAYER 21: FINAL STAGE0 SUMMARY")
    lines.append("=" * 35)
    lines.append("Created On: " + str(datetime.now()))
    lines.append("Dataset: " + str(dataset_name))
    lines.append("Path: " + str(dataset_path))
    lines.append("Rows: " + str(df.shape[0]))
    lines.append("Columns: " + str(df.shape[1]))
    lines.append("Numeric Columns: " + str(len(numeric_cols)))
    lines.append("Categorical Columns: " + str(len(cat_cols)))
    lines.append("Stage0 Files Created: " + str(len(index_df)))
    lines.append("")
    lines.append("Important Next File:")
    lines.append(os.path.join(stage0_path, "20_next_stage_prompt", "next_stage_ml_prompt.txt"))
    lines.append("")
    lines.append("Stage0 Status: Completed")
    lines.append("Next: Start ML problem definition stage.")

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    with open(purpose_file, "a", encoding="utf-8") as f:
        f.write("\n\nLAYER 21 COMPLETED\n")
        f.write("Stage0 Status: Completed\n")
        f.write("Next: Start ML problem definition stage.\n")

    print("Layer 21 completed.")
    print(report_txt)
    print(index_csv)
    print(contract_json)

    display(index_df)


run_layer_21_final_stage0_summary()

Layer 21 completed.
d:\Med_data\stage0-launch-pad\21_final_stage0_summary\layer21_final_summary.txt
d:\Med_data\stage0-launch-pad\21_final_stage0_summary\stage0_file_index.csv
d:\Med_data\stage0-launch-pad\21_final_stage0_summary\stage0_final_contract.json

,folder,file_name,full_path
0,.,dataset_basic_verification_report.txt,d:\Med_data\stage0-launch-pad\dataset_basic_ve...
1,.,selected_dataset_path.txt,d:\Med_data\stage0-launch-pad\selected_dataset...
2,.,What_is_my_purpose_for_next_stage.txt,d:\Med_data\stage0-launch-pad\What_is_my_purpo...
3,00_control_and_purpose,layer0_control_summary.txt,d:\Med_data\stage0-launch-pad\00_control_and_p...
4,00_control_and_purpose,next_stage_read_me_first.txt,d:\Med_data\stage0-launch-pad\00_control_and_p...
...,...,...,...
101,19_research_recommendations,layer19_summary.json,d:\Med_data\stage0-launch-pad\19_research_reco...
102,19_research_recommendations,research_recommendations.csv,d:\Med_data\stage0-launch-pad\19_research_reco...
103,20_next_stage_prompt,layer20_report.txt,d:\Med_data\stage0-launch-pad\20_next_stage_pr...
104,20_next_stage_prompt,next_stage_contract.json,d:\Med_data\stage0-launch-pad\20_next_stage_pr...
105,20_next_stage_prompt,next_stage_ml_prompt.txt,d:\Med_data\stage0-launch-pad\20_next_stage_pr...

In [75]:
# LAYER 22: SELF EXPLAINER / USER GUIDE
# Required: df, dataset_path, dataset_name, stage0_path

import os
import json
from datetime import datetime


def run_layer_22_self_explainer():

    layer_path = os.path.join(stage0_path, "22_self_explainer")
    os.makedirs(layer_path, exist_ok=True)

    guide_txt = os.path.join(layer_path, "how_to_use_stage0_launchpad.txt")
    summary_json = os.path.join(layer_path, "layer22_summary.json")
    purpose_file = os.path.join(stage0_path, "What_is_my_purpose_for_next_stage.txt")

    next_prompt = os.path.join(stage0_path, "20_next_stage_prompt", "next_stage_ml_prompt.txt")
    final_summary = os.path.join(stage0_path, "21_final_stage0_summary", "layer21_final_summary.txt")

    guide_lines = [
        "STAGE0 LAUNCH PAD USER GUIDE",
        "============================",
        "",
        "Purpose:",
        "Stage0 prepares a dataset before ML or AI work.",
        "",
        "Dataset:",
        str(dataset_name),
        "",
        "Dataset Path:",
        str(dataset_path),
        "",
        "Important Files:",
        "1. " + str(purpose_file),
        "2. " + str(next_prompt),
        "3. " + str(final_summary),
        "",
        "How to Use:",
        "1. Review data quality reports.",
        "2. Review metadata and governance files.",
        "3. Confirm target column manually.",
        "4. Read next_stage_ml_prompt.txt.",
        "5. Start the next ML problem-definition stage.",
        "",
        "Important Rules:",
        "1. Do not modify raw data directly.",
        "2. Do not train ML before target confirmation.",
        "3. Review PII and leakage columns.",
        "4. Use Stage0 files as guidance, not final truth.",
        "",
        "Status:",
        "Stage0 documentation completed."
    ]

    with open(guide_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(guide_lines))

    summary = {
        "stage": "Layer 22 - Self Explainer",
        "created_on": str(datetime.now()),
        "dataset_name": str(dataset_name),
        "dataset_path": str(dataset_path),
        "stage0_path": str(stage0_path),
        "guide_file": guide_txt,
        "purpose_file": purpose_file,
        "next_prompt_file": next_prompt,
        "final_summary_file": final_summary,
        "status": "Completed"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    with open(purpose_file, "a", encoding="utf-8") as f:
        f.write("\n\nLAYER 22 COMPLETED\n")
        f.write("Self-explainer guide created.\n")

    print("Layer 22 completed.")
    print(guide_txt)
    print(summary_json)


run_layer_22_self_explainer()

Layer 22 completed.
d:\Med_data\stage0-launch-pad\22_self_explainer\how_to_use_stage0_launchpad.txt
d:\Med_data\stage0-launch-pad\22_self_explainer\layer22_summary.json

In [77]:
# STAGE0 CHECKPOINT - CLEAN MINIMAL VERSION
# Required variables before running:
# dataset_name, dataset_path, stage0_path

import os
import json
import pandas as pd
from datetime import datetime

try:
    from IPython.display import display
except Exception:
    display = print


def run_stage0_checkpoint():
    folder = os.path.join(stage0_path, "Stage0_CheckPoint")
    os.makedirs(folder, exist_ok=True)

    csv_file = os.path.join(folder, "Stage0_CheckPoint.csv")
    json_file = os.path.join(folder, "Stage0_CheckPoint.json")
    txt_file = os.path.join(folder, "Stage0_CheckPoint.txt")

    stages = [
        ["0", "Control and Purpose", "Creates main purpose and control files"],
        ["1", "Raw File Rescue", "Checks encoding delimiter empty lines broken rows"],
        ["2", "Dataset Structure", "Checks rows columns datatypes null columns sample values"],
        ["3", "Data Quality", "Checks missing duplicates empty rows noisy values"],
        ["4A", "Basic Column Semantics", "Finds numeric categorical date text ID like columns"],
        ["4B", "Target PII Leakage ML Usability", "Finds target PII leakage and usable features"],
        ["5", "Numeric Basic Statistics", "Creates numeric statistics"],
        ["6", "Categorical Basic Statistics", "Creates categorical statistics"],
        ["7", "Distribution Summary", "Checks unique dominant cardinality patterns"],
        ["8", "Correlation Analysis", "Checks numeric correlations"],
        ["9", "Outlier Analysis", "Finds numeric outliers using IQR"],
        ["10", "Skewness and Kurtosis", "Checks numeric distribution shape"],
        ["11", "Class Balance Analysis", "Checks low cardinality class balance"],
        ["12", "Rare Category Analysis", "Finds rare categorical values"],
        ["13", "Metadata Generator", "Creates metadata dictionary datasheet draft"],
        ["14", "Dictionary Datasheet Review", "Checks missing documentation"],
        ["15", "Governance PII Responsible AI", "Checks privacy sensitive fields AI risk"],
        ["16", "Feature Engineering Suggestions", "Suggests possible new features"],
        ["17", "ML Readiness Score", "Scores dataset readiness for ML"],
        ["18", "ML Problem Definitions", "Suggests ML problem types"],
        ["19", "Research Recommendations", "Suggests research questions"],
        ["20", "Next Stage Prompt Generator", "Creates next ML prompt"],
        ["21", "Final Stage0 Summary", "Creates final index and summary"],
        ["22", "Self Explainer", "Creates user guide"],
    ]

    df_cp = pd.DataFrame(stages, columns=["stage_no", "stage_name", "purpose"])
    df_cp.to_csv(csv_file, index=False, encoding="utf-8-sig")

    data = {
        "created_on": str(datetime.now()),
        "dataset_name": str(dataset_name),
        "dataset_path": str(dataset_path),
        "stage0_path": str(stage0_path),
        "total_stages": len(stages),
        "stages": df_cp.to_dict(orient="records"),
    }

    with open(json_file, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

    # Write TXT with short lines only.
    with open(txt_file, "w", encoding="utf-8-sig") as f:
        f.write("STAGE0 CHECKPOINT\n")
        f.write("Created: " + str(datetime.now()) + "\n")
        f.write("Dataset: " + str(dataset_name) + "\n")
        f.write("\n")
        for stage in stages:
            f.write("Layer " + stage[0] + ": " + stage[1] + "\n")
            f.write("Purpose: " + stage[2] + "\n")
            f.write("\n")

    print("Stage0_CheckPoint created")
    print(txt_file)
    print(csv_file)
    print(json_file)
    display(df_cp)


run_stage0_checkpoint()

Stage0_CheckPoint created
d:\Med_data\stage0-launch-pad\Stage0_CheckPoint\Stage0_CheckPoint.txt
d:\Med_data\stage0-launch-pad\Stage0_CheckPoint\Stage0_CheckPoint.csv
d:\Med_data\stage0-launch-pad\Stage0_CheckPoint\Stage0_CheckPoint.json

,stage_no,stage_name,purpose
0,0,Control and Purpose,Creates main purpose and control files
1,1,Raw File Rescue,Checks encoding delimiter empty lines broken rows
2,2,Dataset Structure,Checks rows columns datatypes null columns sam...
3,3,Data Quality,Checks missing duplicates empty rows noisy values
4,4A,Basic Column Semantics,Finds numeric categorical date text ID like co...
5,4B,Target PII Leakage ML Usability,Finds target PII leakage and usable features
6,5,Numeric Basic Statistics,Creates numeric statistics
7,6,Categorical Basic Statistics,Creates categorical statistics
8,7,Distribution Summary,Checks unique dominant cardinality patterns
9,8,Correlation Analysis,Checks numeric correlations
10,9,Outlier Analysis,Finds numeric outliers using IQR
11,10,Skewness and Kurtosis,Checks numeric distribution shape
12,11,Class Balance Analysis,Checks low cardinality class balance
13,12,Rare Category Analysis,Finds rare categorical values
14,13,Metadata Generator,Creates metadata dictionary datasheet draft
15,14,Dictionary Datasheet Review,Checks missing documentation
16,15,Governance PII Responsible AI,Checks privacy sensitive fields AI risk
17,16,Feature Engineering Suggestions,Suggests possible new features
18,17,ML Readiness Score,Scores dataset readiness for ML
19,18,ML Problem Definitions,Suggests ML problem types
20,19,Research Recommendations,Suggests research questions
21,20,Next Stage Prompt Generator,Creates next ML prompt
22,21,Final Stage0 Summary,Creates final index and summary
23,22,Self Explainer,Creates user guide

In [79]:
# LAYER 23: STAGE1 READY EXPORT - NO LONG TEXT VERSION
# Run in Jupyter with:
# %run -i layer23_stage1_export_clean_no_text.py
#
# Required variables in notebook:
# df, dataset_path, dataset_name, stage0_path

import os
import re
import json
import numpy as np
import pandas as pd
from datetime import datetime

try:
    from IPython.display import display
except Exception:
    display = print


def run_layer_23_stage1_ready_export():
    main_folder = os.path.dirname(dataset_path)
    out_folder = os.path.join(stage0_path, "23_stage1_ready_export")
    os.makedirs(out_folder, exist_ok=True)

    stage1_csv = os.path.join(main_folder, "dataset_for_stage_1.csv")
    contract_json = os.path.join(out_folder, "stage1_handover_contract.json")
    col_map_csv = os.path.join(out_folder, "column_name_mapping.csv")
    missing_map_csv = os.path.join(out_folder, "missing_indicator_map.csv")
    risk_csv = os.path.join(out_folder, "risk_columns_for_review.csv")
    file_index_csv = os.path.join(out_folder, "stage0_file_index.csv")
    process_csv = os.path.join(out_folder, "stage1_processing_summary.csv")

    def clean_col(x):
        x = str(x).strip().lower()
        x = re.sub(r"[^a-zA-Z0-9]+", "_", x)
        x = re.sub(r"_+", "_", x).strip("_")
        return x if x else "unnamed_column"

    def unique_cols(cols):
        seen = {}
        final = []
        for col in cols:
            seen[col] = seen.get(col, 0)
            final.append(col if seen[col] == 0 else f"{col}_{seen[col]}")
            seen[col] += 1
        return final

    def add_step(step_name):
        processing_steps.append({
            "step": step_name,
            "rows": int(work.shape[0]),
            "columns": int(work.shape[1])
        })

    missing_tokens = {
        "", " ", "na", "n/a", "null", "none", "nan",
        "?", "??", "-", "--", "unknown", "missing",
        "not available", "not_applicable"
    }

    work = df.copy()
    processing_steps = []
    add_step("original_loaded")

    original_columns = [str(c) for c in work.columns]
    cleaned_columns = unique_cols([clean_col(c) for c in original_columns])
    work.columns = cleaned_columns

    pd.DataFrame({
        "original_column": original_columns,
        "stage1_column": cleaned_columns,
        "changed": [a != b for a, b in zip(original_columns, cleaned_columns)]
    }).to_csv(col_map_csv, index=False)

    add_step("column_names_cleaned")

    for col in work.columns:
        if work[col].dtype == "object":
            work[col] = work[col].apply(
                lambda v: np.nan if isinstance(v, str) and v.strip().lower() in missing_tokens else v
            )

    add_step("missing_tokens_normalized")

    rows_before = int(work.shape[0])
    work = work.dropna(how="all")
    removed_empty_rows = rows_before - int(work.shape[0])
    add_step("fully_empty_rows_removed")

    fully_null_columns = [c for c in work.columns if work[c].isna().all()]
    work = work.drop(columns=fully_null_columns)
    add_step("fully_null_columns_removed")

    missing_rows = []
    missing_flags_added = 0

    for col in list(work.columns):
        missing_count = int(work[col].isna().sum())
        if missing_count > 0:
            flag_col = col + "_missing"
            work[flag_col] = work[col].isna().astype(int)
            missing_flags_added += 1
            missing_rows.append({
                "column_name": col,
                "missing_flag_column": flag_col,
                "missing_count": missing_count,
                "missing_percentage": round(float(work[col].isna().mean() * 100), 4)
            })

    missing_map = pd.DataFrame(missing_rows)
    if missing_map.empty:
        missing_map = pd.DataFrame([{
            "column_name": "",
            "missing_flag_column": "",
            "missing_count": 0,
            "missing_percentage": 0
        }])

    missing_map.to_csv(missing_map_csv, index=False)
    add_step("missing_flags_added")

    risk_rules = {
        "possible_pii": [
            "name", "email", "phone", "mobile", "address",
            "cnic", "passport", "ssn"
        ],
        "possible_id": ["id"],
        "possible_sensitive": [
            "age", "gender", "sex", "dob", "birth", "race",
            "religion", "salary", "income"
        ],
        "possible_target_or_leakage": [
            "target", "label", "result", "outcome", "status",
            "score", "final"
        ]
    }

    risk_rows = []

    for col in work.columns:
        low = col.lower()
        found = []
        for risk_type, words in risk_rules.items():
            for word in words:
                if word == "id":
                    if low == "id" or low.endswith("_id") or "_id_" in low:
                        found.append(risk_type)
                elif word in low:
                    found.append(risk_type)

        if found:
            risk_rows.append({
                "column_name": col,
                "risk_type": ", ".join(sorted(set(found))),
                "action": "review_before_ml"
            })

    risk_df = pd.DataFrame(risk_rows)
    if risk_df.empty:
        risk_df = pd.DataFrame([{
            "column_name": "",
            "risk_type": "none_detected",
            "action": "manual_review_still_required"
        }])

    risk_df.to_csv(risk_csv, index=False)
    add_step("risk_columns_scanned")

    file_rows = []
    for root, dirs, files in os.walk(stage0_path):
        for file in files:
            full_path = os.path.join(root, file)
            file_rows.append({
                "folder": os.path.relpath(root, stage0_path),
                "file_name": file,
                "full_path": full_path
            })

    file_index = pd.DataFrame(file_rows)
    file_index.to_csv(file_index_csv, index=False)
    add_step("stage0_files_indexed")

    work.to_csv(stage1_csv, index=False)
    add_step("stage1_dataset_saved")

    process_df = pd.DataFrame(processing_steps)
    process_df.to_csv(process_csv, index=False)

    contract = {
        "stage": "Layer 23 - Stage1 Ready Export",
        "created_on": str(datetime.now()),
        "original_dataset": str(dataset_path),
        "stage1_dataset": str(stage1_csv),
        "original_rows": int(df.shape[0]),
        "original_columns": int(df.shape[1]),
        "stage1_rows": int(work.shape[0]),
        "stage1_columns": int(work.shape[1]),
        "removed_empty_rows": int(removed_empty_rows),
        "removed_fully_null_columns": [str(c) for c in fully_null_columns],
        "missing_indicator_columns_added": int(missing_flags_added),
        "stage0_files_indexed": int(len(file_index)),
        "files": {
            "processing_summary": process_csv,
            "column_mapping": col_map_csv,
            "missing_indicator_map": missing_map_csv,
            "risk_columns": risk_csv,
            "stage0_file_index": file_index_csv
        },
        "next_action": "Stage1 reads dataset_for_stage_1.csv and stage1_handover_contract.json"
    }

    with open(contract_json, "w", encoding="utf-8") as f:
        json.dump(contract, f, indent=4, ensure_ascii=False, default=str)

    print("Layer 23 completed")
    print("Rows:", int(df.shape[0]), "->", int(work.shape[0]))
    print("Columns:", int(df.shape[1]), "->", int(work.shape[1]))
    print("Empty rows removed:", int(removed_empty_rows))
    print("Fully null columns removed:", len(fully_null_columns))
    print("Missing flag columns added:", int(missing_flags_added))
    print("Stage0 files indexed:", int(len(file_index)))
    print("Stage1 dataset:", stage1_csv)
    print("Contract:", contract_json)

    display(process_df)
    display(missing_map)
    display(risk_df)

    return work, process_df, missing_map, risk_df, contract


dataset_for_stage_1_df, layer23_process_df, layer23_missing_map_df, layer23_risk_df, layer23_contract = run_layer_23_stage1_ready_export()

Layer 23 completed
Rows: 55500 -> 55500
Columns: 15 -> 15
Empty rows removed: 0
Fully null columns removed: 0
Missing flag columns added: 0
Stage0 files indexed: 117
Stage1 dataset: d:\Med_data\dataset_for_stage_1.csv
Contract: d:\Med_data\stage0-launch-pad\23_stage1_ready_export\stage1_handover_contract.json

                         step   rows  columns
0             original_loaded  55500       15
1        column_names_cleaned  55500       15
2   missing_tokens_normalized  55500       15
3    fully_empty_rows_removed  55500       15
4  fully_null_columns_removed  55500       15
5         missing_flags_added  55500       15
6        risk_columns_scanned  55500       15
7        stage0_files_indexed  55500       15
8        stage1_dataset_saved  55500       15

  column_name missing_flag_column  missing_count  missing_percentage
0                                              0                   0

    column_name                   risk_type            action
0          name                possible_pii  review_before_ml
1           age          possible_sensitive  review_before_ml
2        gender          possible_sensitive  review_before_ml
3  test_results  possible_target_or_leakage  review_before_ml

In [83]:
# STAGE 24: STAGE0 TOTAL INTELLIGENCE
# Use after Layer 23
# Required variables in Jupyter:
# df, dataset_path, dataset_name, stage0_path

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_stage24_total_intelligence():
    out_dir = os.path.join(stage0_path, "24_stage0_total_intelligence")
    os.makedirs(out_dir, exist_ok=True)

    main_folder = os.path.dirname(dataset_path)
    stage1_dataset = os.path.join(main_folder, "dataset_for_stage_1.csv")

    total_json = os.path.join(out_dir, "stage0_total_intelligence.json")
    total_csv = os.path.join(out_dir, "stage0_total_intelligence.csv")
    start_txt = os.path.join(out_dir, "stage1_start_here.txt")
    input_files_csv = os.path.join(out_dir, "stage1_input_files.csv")
    actions_csv = os.path.join(out_dir, "stage1_required_actions.csv")
    blockers_csv = os.path.join(out_dir, "stage1_blockers_and_warnings.csv")

    def stage0_files():
        rows = []
        for root, dirs, files in os.walk(stage0_path):
            for file in files:
                full_path = os.path.join(root, file)
                rel_folder = os.path.relpath(root, stage0_path)
                rows.append({
                    "folder": rel_folder,
                    "file_name": file,
                    "full_path": full_path
                })
        return pd.DataFrame(rows)

    def find_key_files(files_df):
        if files_df.empty:
            return files_df
        keys = [
            "handover", "risk", "readiness", "problem", "research",
            "metadata", "quality", "semantics", "prompt", "missing",
            "contract", "stage1", "dataset_for_stage_1"
        ]
        mask = files_df["file_name"].str.lower().apply(
            lambda x: any(k in x for k in keys)
        )
        return files_df[mask].copy()

    def possible_targets_from_df(dataframe):
        words = [
            "target", "label", "class", "result", "outcome",
            "condition", "status", "diagnosis", "risk", "score"
        ]
        targets = []
        for col in dataframe.columns:
            name = str(col).lower()
            if any(w in name for w in words):
                if dataframe[col].nunique(dropna=True) > 1:
                    targets.append(str(col))
        return targets

    raw_rows = int(df.shape[0])
    raw_cols = int(df.shape[1])

    if os.path.exists(stage1_dataset):
        try:
            stage1_df = pd.read_csv(stage1_dataset)
            stage1_exists = True
        except Exception:
            stage1_df = pd.DataFrame()
            stage1_exists = False
    else:
        stage1_df = pd.DataFrame()
        stage1_exists = False

    stage1_rows = int(stage1_df.shape[0]) if stage1_exists else 0
    stage1_cols = int(stage1_df.shape[1]) if stage1_exists else 0

    numeric_count = int(len(df.select_dtypes(include=["number"]).columns))
    categorical_count = int(len(df.select_dtypes(include=["object", "category", "bool"]).columns))

    missing_pct = round(float(df.isna().mean().mean() * 100), 4)
    duplicate_rows = int(df.duplicated().sum())

    possible_targets = possible_targets_from_df(df)

    files_df = stage0_files()
    files_df.to_csv(input_files_csv, index=False)

    key_files_df = find_key_files(files_df)

    risk_count = 0
    if not files_df.empty:
        risk_files = files_df[files_df["file_name"].str.lower().str.contains("risk_columns_for_review", na=False)]
        if not risk_files.empty:
            try:
                risk_df = pd.read_csv(risk_files.iloc[-1]["full_path"])
                if "column_name" in risk_df.columns:
                    risk_count = int(len(risk_df))
            except Exception:
                risk_count = 0

    blockers = []

    if not stage1_exists:
        blockers.append({
            "severity": "High",
            "issue": "dataset_for_stage_1.csv not found or not readable",
            "stage1_action": "Run Layer 23 again"
        })

    if not possible_targets:
        blockers.append({
            "severity": "Medium",
            "issue": "No obvious target column found",
            "stage1_action": "Ask user to confirm target or choose clustering/EDA"
        })

    if risk_count > 0:
        blockers.append({
            "severity": "High",
            "issue": "Risk columns detected",
            "stage1_action": "Review risk_columns_for_review.csv before ML"
        })

    if missing_pct > 20:
        blockers.append({
            "severity": "Medium",
            "issue": "High missing percentage",
            "stage1_action": "Define missing-value strategy"
        })

    if duplicate_rows > 0:
        blockers.append({
            "severity": "Low",
            "issue": "Duplicate rows found",
            "stage1_action": "Decide whether duplicates are valid"
        })

    if not blockers:
        blockers.append({
            "severity": "Info",
            "issue": "No major automatic blocker detected",
            "stage1_action": "Manual review still required"
        })

    blockers_df = pd.DataFrame(blockers)
    blockers_df.to_csv(blockers_csv, index=False)

    actions = [
        {"step": 1, "required_action": "Load dataset_for_stage_1.csv"},
        {"step": 2, "required_action": "Read stage0_total_intelligence.json"},
        {"step": 3, "required_action": "Review risk columns"},
        {"step": 4, "required_action": "Confirm target column"},
        {"step": 5, "required_action": "Choose ML direction"},
        {"step": 6, "required_action": "Write Stage1 decision report"},
        {"step": 7, "required_action": "Do not train models until target and risks are confirmed"}
    ]
    actions_df = pd.DataFrame(actions)
    actions_df.to_csv(actions_csv, index=False)

    intelligence = {
        "stage": "Stage 24 - Stage0 Total Intelligence",
        "created_on": str(datetime.now()),
        "dataset_name": str(dataset_name),
        "raw_dataset_path": str(dataset_path),
        "stage0_path": str(stage0_path),
        "stage1_dataset_path": str(stage1_dataset),
        "stage1_dataset_exists": bool(stage1_exists),
        "raw_rows": raw_rows,
        "raw_columns": raw_cols,
        "stage1_rows": stage1_rows,
        "stage1_columns": stage1_cols,
        "numeric_columns_count": numeric_count,
        "categorical_columns_count": categorical_count,
        "raw_missing_percentage": missing_pct,
        "raw_duplicate_rows": duplicate_rows,
        "possible_target_columns": possible_targets,
        "risk_columns_count": risk_count,
        "stage0_files_count": int(len(files_df)),
        "key_stage0_files_count": int(len(key_files_df)),
        "stage1_input_files_csv": str(input_files_csv),
        "stage1_required_actions_csv": str(actions_csv),
        "stage1_blockers_csv": str(blockers_csv),
        "stage1_instruction": "Read this JSON first, then load dataset_for_stage_1.csv."
    }

    with open(total_json, "w", encoding="utf-8") as f:
        json.dump(intelligence, f, indent=4, ensure_ascii=False, default=str)

    pd.DataFrame([intelligence]).to_csv(total_csv, index=False)

    start_lines = [
        "STAGE1 START HERE",
        "Dataset: " + str(dataset_name),
        "Stage1 dataset: " + str(stage1_dataset),
        "Raw rows: " + str(raw_rows),
        "Stage1 rows: " + str(stage1_rows),
        "Raw columns: " + str(raw_cols),
        "Stage1 columns: " + str(stage1_cols),
        "Possible targets: " + str(possible_targets),
        "Risk columns count: " + str(risk_count),
        "Read JSON: " + str(total_json)
    ]

    with open(start_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(start_lines))

    print("Stage 24 completed.")
    print("Raw rows -> Stage1 rows:", raw_rows, "->", stage1_rows)
    print("Raw columns -> Stage1 columns:", raw_cols, "->", stage1_cols)
    print("Possible targets:", possible_targets)
    print("Risk columns count:", risk_count)
    print("JSON:", total_json)

    display(pd.DataFrame([intelligence]))
    display(blockers_df)
    display(actions_df)


run_stage24_total_intelligence()

Stage 24 completed.
Raw rows -> Stage1 rows: 55500 -> 55500
Raw columns -> Stage1 columns: 15 -> 15
Possible targets: ['Medical Condition', 'Test Results']
Risk columns count: 4
JSON: d:\Med_data\stage0-launch-pad\24_stage0_total_intelligence\stage0_total_intelligence.json

,stage,created_on,dataset_name,raw_dataset_path,stage0_path,stage1_dataset_path,stage1_dataset_exists,raw_rows,raw_columns,stage1_rows,...,raw_missing_percentage,raw_duplicate_rows,possible_target_columns,risk_columns_count,stage0_files_count,key_stage0_files_count,stage1_input_files_csv,stage1_required_actions_csv,stage1_blockers_csv,stage1_instruction
0,Stage 24 - Stage0 Total Intelligence,2026-05-13 23:11:48.157880,dataset.csv,d:\Med_data\dataset.csv,d:\Med_data\stage0-launch-pad,d:\Med_data\dataset_for_stage_1.csv,True,55500,15,55500,...,0.0,534,"[Medical Condition, Test Results]",4,126,30,d:\Med_data\stage0-launch-pad\24_stage0_total_...,d:\Med_data\stage0-launch-pad\24_stage0_total_...,d:\Med_data\stage0-launch-pad\24_stage0_total_...,"Read this JSON first, then load dataset_for_st..."

,severity,issue,stage1_action
0,High,Risk columns detected,Review risk_columns_for_review.csv before ML
1,Low,Duplicate rows found,Decide whether duplicates are valid

   step                                    required_action
0     1                       Load dataset_for_stage_1.csv
1     2                Read stage0_total_intelligence.json
2     3                                Review risk columns
3     4                              Confirm target column
4     5                                Choose ML direction
5     6                       Write Stage1 decision report
6     7  Do not train models until target and risks are...

In [1]:
print("===============================================  Next stage =========================")

===============================================  Next stage =========================

In [5]:
import os

drive = input("Enter drive, e.g. D: ")
folder_name = input("Enter dataset folder name/path, e.g. med_data: ")
dataset_name = input("Enter original dataset file name, e.g. data.csv: ")

base_path = os.path.join(drive + "\\", folder_name)
dataset_path = os.path.join(base_path, dataset_name)
stage0_path = os.path.join(base_path, "stage0-launch-pad")

stage1_dataset_path = os.path.join(base_path, "dataset_for_stage_1.csv")

print("Base Path:", base_path)
print("Original Dataset Path:", dataset_path)
print("Stage0 Path:", stage0_path)
print("Stage1 Dataset Path:", stage1_dataset_path)

print("Original dataset exists:", os.path.exists(dataset_path))
print("Stage0 folder exists:", os.path.exists(stage0_path))
print("Stage1 dataset exists:", os.path.exists(stage1_dataset_path))

Enter drive, e.g. D:  d:
Enter dataset folder name/path, e.g. med_data:  med_data
Enter original dataset file name, e.g. data.csv:  dataset.csv

Base Path: d:\med_data
Original Dataset Path: d:\med_data\dataset.csv
Stage0 Path: d:\med_data\stage0-launch-pad
Stage1 Dataset Path: d:\med_data\dataset_for_stage_1.csv
Original dataset exists: True
Stage0 folder exists: True
Stage1 dataset exists: True

In [7]:
df_stage1 = run_stage1_module1_input_reader()

Stage 1 Module 1 completed.
Rows: 55500
Columns: 15
Numeric columns: 3
Categorical columns: 12
Missing %: 0.0
Duplicate rows: 534
Risk columns: 4
Output folder: d:\med_data\stage1-dataset-intelligence

,input_name,path,exists
0,stage1_dataset,d:\med_data\dataset_for_stage_1.csv,True
1,stage0_total_intelligence,d:\med_data\stage0-launch-pad\24_stage0_total_...,True
2,stage1_handover_contract,d:\med_data\stage0-launch-pad\23_stage1_ready_...,True
3,risk_columns,d:\med_data\stage0-launch-pad\23_stage1_ready_...,True
4,stage0_file_index,d:\med_data\stage0-launch-pad\23_stage1_ready_...,True

,stage,created_on,stage1_dataset,rows,columns,numeric_columns_count,categorical_columns_count,missing_percentage,duplicate_rows,risk_columns_count,risk_columns,file_check_csv,next_module
0,Stage 1 - Module 1 Input Reader,2026-05-13 21:42:08.273949,d:\med_data\dataset_for_stage_1.csv,55500,15,3,12,0.0,534,4,"[name, age, gender, test_results]",d:\med_data\stage1-dataset-intelligence\Stage1...,Stage 1 Module 2 - Stage0 Intelligence Interpr...

In [85]:
# STAGE 1 - MODULE 1: INPUT READER
# Required: dataset_path, stage0_path

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_stage1_module1_input_reader():

    main_folder = os.path.dirname(dataset_path)
    stage1_path = os.path.join(main_folder, "stage1-dataset-intelligence")
    os.makedirs(stage1_path, exist_ok=True)

    stage1_dataset = os.path.join(main_folder, "dataset_for_stage_1.csv")

    output_json = os.path.join(stage1_path, "Stage1_Input_Summary.json")
    output_csv = os.path.join(stage1_path, "Stage1_Input_Summary.csv")
    file_check_csv = os.path.join(stage1_path, "Stage1_Input_File_Check.csv")

    expected_files = {
        "stage1_dataset": stage1_dataset,
        "stage0_total_intelligence": os.path.join(
            stage0_path,
            "24_stage0_total_intelligence",
            "stage0_total_intelligence.json"
        ),
        "stage1_handover_contract": os.path.join(
            stage0_path,
            "23_stage1_ready_export",
            "stage1_handover_contract.json"
        ),
        "risk_columns": os.path.join(
            stage0_path,
            "23_stage1_ready_export",
            "risk_columns_for_review.csv"
        ),
        "stage0_file_index": os.path.join(
            stage0_path,
            "23_stage1_ready_export",
            "stage0_file_index.csv"
        )
    }

    file_rows = []

    for name, path in expected_files.items():
        file_rows.append({
            "input_name": name,
            "path": path,
            "exists": os.path.exists(path)
        })

    file_check_df = pd.DataFrame(file_rows)
    file_check_df.to_csv(file_check_csv, index=False)

    if not os.path.exists(stage1_dataset):
        raise FileNotFoundError("dataset_for_stage_1.csv not found. Please run Layer 23 first.")

    df_stage1 = pd.read_csv(stage1_dataset)

    rows_count = int(df_stage1.shape[0])
    cols_count = int(df_stage1.shape[1])

    numeric_cols = [str(c) for c in df_stage1.select_dtypes(include=["number"]).columns]
    categorical_cols = [
        str(c) for c in df_stage1.select_dtypes(include=["object", "category", "bool"]).columns
    ]

    missing_pct = round(float(df_stage1.isna().mean().mean() * 100), 4)
    duplicate_rows = int(df_stage1.duplicated().sum())

    risk_count = 0
    risk_columns = []

    risk_path = expected_files["risk_columns"]

    if os.path.exists(risk_path):
        risk_df = pd.read_csv(risk_path)
        if "column_name" in risk_df.columns:
            risk_columns = risk_df["column_name"].dropna().astype(str).tolist()
            risk_count = len(risk_columns)
    else:
        risk_df = pd.DataFrame()

    summary = {
        "stage": "Stage 1 - Module 1 Input Reader",
        "created_on": str(datetime.now()),
        "stage1_dataset": stage1_dataset,
        "rows": rows_count,
        "columns": cols_count,
        "numeric_columns_count": len(numeric_cols),
        "categorical_columns_count": len(categorical_cols),
        "missing_percentage": missing_pct,
        "duplicate_rows": duplicate_rows,
        "risk_columns_count": risk_count,
        "risk_columns": risk_columns,
        "file_check_csv": file_check_csv,
        "next_module": "Stage 1 Module 2 - Stage0 Intelligence Interpreter"
    }

    with open(output_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    pd.DataFrame([summary]).to_csv(output_csv, index=False)

    print("Stage 1 Module 1 completed.")
    print("Rows:", rows_count)
    print("Columns:", cols_count)
    print("Numeric columns:", len(numeric_cols))
    print("Categorical columns:", len(categorical_cols))
    print("Missing %:", missing_pct)
    print("Duplicate rows:", duplicate_rows)
    print("Risk columns:", risk_count)
    print("Output folder:", stage1_path)

    display(file_check_df)
    display(pd.DataFrame([summary]))

    return df_stage1


df_stage1 = run_stage1_module1_input_reader()

Stage 1 Module 1 completed.
Rows: 55500
Columns: 15
Numeric columns: 3
Categorical columns: 12
Missing %: 0.0
Duplicate rows: 534
Risk columns: 4
Output folder: d:\Med_data\stage1-dataset-intelligence

,input_name,path,exists
0,stage1_dataset,d:\Med_data\dataset_for_stage_1.csv,True
1,stage0_total_intelligence,d:\Med_data\stage0-launch-pad\24_stage0_total_...,True
2,stage1_handover_contract,d:\Med_data\stage0-launch-pad\23_stage1_ready_...,True
3,risk_columns,d:\Med_data\stage0-launch-pad\23_stage1_ready_...,True
4,stage0_file_index,d:\Med_data\stage0-launch-pad\23_stage1_ready_...,True

,stage,created_on,stage1_dataset,rows,columns,numeric_columns_count,categorical_columns_count,missing_percentage,duplicate_rows,risk_columns_count,risk_columns,file_check_csv,next_module
0,Stage 1 - Module 1 Input Reader,2026-05-13 23:12:08.075809,d:\Med_data\dataset_for_stage_1.csv,55500,15,3,12,0.0,534,4,"[name, age, gender, test_results]",d:\Med_data\stage1-dataset-intelligence\Stage1...,Stage 1 Module 2 - Stage0 Intelligence Interpr...

In [87]:
# STAGE 1 - MODULE 2: STAGE0 INTELLIGENCE INTERPRETER
# Required: dataset_path, stage0_path, df_stage1

import os
import json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_stage1_module2_stage0_interpreter():

    main_folder = os.path.dirname(dataset_path)
    stage1_path = os.path.join(main_folder, "stage1-dataset-intelligence")
    os.makedirs(stage1_path, exist_ok=True)

    out_json = os.path.join(stage1_path, "Stage1_Stage0_Intelligence_Interpretation.json")
    out_csv = os.path.join(stage1_path, "Stage1_Stage0_Intelligence_Interpretation.csv")
    out_txt = os.path.join(stage1_path, "Stage1_Stage0_Intelligence_Interpretation.txt")

    total_intel_json = os.path.join(
        stage0_path,
        "24_stage0_total_intelligence",
        "stage0_total_intelligence.json"
    )

    handover_json = os.path.join(
        stage0_path,
        "23_stage1_ready_export",
        "stage1_handover_contract.json"
    )

    risk_csv = os.path.join(
        stage0_path,
        "23_stage1_ready_export",
        "risk_columns_for_review.csv"
    )

    def load_json(path):
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        return {}

    total_intel = load_json(total_intel_json)
    handover = load_json(handover_json)

    rows_count = int(df_stage1.shape[0])
    cols_count = int(df_stage1.shape[1])

    numeric_cols = [str(c) for c in df_stage1.select_dtypes(include=["number"]).columns]
    cat_cols = [str(c) for c in df_stage1.select_dtypes(include=["object", "category", "bool"]).columns]

    missing_pct = round(float(df_stage1.isna().mean().mean() * 100), 4)
    duplicate_rows = int(df_stage1.duplicated().sum())

    possible_targets = total_intel.get("possible_target_columns", [])
    if not isinstance(possible_targets, list):
        possible_targets = []

    risk_count = 0
    risk_cols = []

    if os.path.exists(risk_csv):
        risk_df = pd.read_csv(risk_csv)
        if "column_name" in risk_df.columns:
            risk_cols = risk_df["column_name"].dropna().astype(str).tolist()
            risk_count = len(risk_cols)

    interpretation_rows = []

    def add_item(area, score, level, reason, action):
        interpretation_rows.append({
            "assessment_area": area,
            "score_out_of_100": score,
            "level": level,
            "reason": reason,
            "stage1_action": action
        })

    if rows_count >= 10000:
        add_item("Row strength", 90, "Strong", "Large row count.", "Good base for ML experiments.")
    elif rows_count >= 1000:
        add_item("Row strength", 70, "Moderate", "Medium row count.", "Use baseline models carefully.")
    else:
        add_item("Row strength", 45, "Weak", "Small row count.", "Avoid overclaiming ML results.")

    if cols_count >= 10:
        add_item("Feature width", 80, "Good", "Many columns available.", "Review feature usefulness.")
    elif cols_count >= 3:
        add_item("Feature width", 60, "Moderate", "Some columns available.", "Feature engineering may be needed.")
    else:
        add_item("Feature width", 30, "Weak", "Very few columns.", "ML options may be limited.")

    if missing_pct <= 5:
        add_item("Missing values", 90, "Strong", "Low missing percentage.", "Proceed with normal review.")
    elif missing_pct <= 20:
        add_item("Missing values", 65, "Moderate", "Moderate missing percentage.", "Define imputation strategy.")
    else:
        add_item("Missing values", 35, "Weak", "High missing percentage.", "Resolve missing values before ML.")

    if duplicate_rows == 0:
        add_item("Duplicate rows", 90, "Strong", "No duplicate rows detected.", "No duplicate action needed.")
    else:
        add_item("Duplicate rows", 55, "Review", "Duplicate rows detected.", "Decide whether duplicates are valid.")

    if len(numeric_cols) >= 2:
        add_item("Numeric feature strength", 80, "Good", "Multiple numeric columns exist.", "Regression, clustering, anomaly may be possible.")
    elif len(numeric_cols) == 1:
        add_item("Numeric feature strength", 55, "Limited", "Only one numeric column exists.", "Numeric ML options limited.")
    else:
        add_item("Numeric feature strength", 25, "Weak", "No numeric columns found.", "Focus on categorical/text analysis.")

    if len(cat_cols) >= 2:
        add_item("Categorical feature strength", 80, "Good", "Multiple categorical columns exist.", "Classification or segmentation may be possible.")
    elif len(cat_cols) == 1:
        add_item("Categorical feature strength", 55, "Limited", "Only one categorical column exists.", "Review category usefulness.")
    else:
        add_item("Categorical feature strength", 25, "Weak", "No categorical columns found.", "Categorical analysis limited.")

    if possible_targets:
        add_item("Target clarity", 70, "Possible", "Possible target columns detected.", "User must confirm final target.")
    else:
        add_item("Target clarity", 35, "Unclear", "No strong target detected.", "Ask user to confirm goal or use unsupervised/EDA.")

    if risk_count == 0:
        add_item("Risk column status", 80, "Low automatic risk", "No risk columns detected automatically.", "Manual review still required.")
    else:
        add_item("Risk column status", 45, "Review required", "Risk columns detected.", "Review before ML.")

    scores = [r["score_out_of_100"] for r in interpretation_rows]
    overall_score = round(sum(scores) / len(scores), 2)

    if overall_score >= 75:
        overall_level = "Strong Stage0 foundation"
    elif overall_score >= 55:
        overall_level = "Moderate Stage0 foundation"
    else:
        overall_level = "Weak Stage0 foundation"

    result_df = pd.DataFrame(interpretation_rows)
    result_df.to_csv(out_csv, index=False)

    summary = {
        "stage": "Stage 1 Module 2 - Stage0 Intelligence Interpreter",
        "created_on": str(datetime.now()),
        "rows": rows_count,
        "columns": cols_count,
        "numeric_columns_count": len(numeric_cols),
        "categorical_columns_count": len(cat_cols),
        "missing_percentage": missing_pct,
        "duplicate_rows": duplicate_rows,
        "possible_target_columns": possible_targets,
        "risk_columns_count": risk_count,
        "risk_columns": risk_cols,
        "overall_stage0_foundation_score": overall_score,
        "overall_stage0_foundation_level": overall_level,
        "next_module": "Stage 1 Module 3 - ML Possibility Scorer"
    }

    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    lines = [
        "STAGE 1 MODULE 2 COMPLETED",
        "Overall Score: " + str(overall_score),
        "Overall Level: " + overall_level,
        "Rows: " + str(rows_count),
        "Columns: " + str(cols_count),
        "Missing %: " + str(missing_pct),
        "Possible Targets: " + str(possible_targets),
        "Risk Columns Count: " + str(risk_count),
        "Next: Stage 1 Module 3 - ML Possibility Scorer"
    ]

    with open(out_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("Stage 1 Module 2 completed.")
    print("Overall Score:", overall_score)
    print("Overall Level:", overall_level)
    print("Possible Targets:", possible_targets)
    print("Risk Columns Count:", risk_count)
    print(out_csv)
    print(out_json)

    display(result_df)

    return result_df, summary


stage1_interpretation_df, stage1_interpretation_summary = run_stage1_module2_stage0_interpreter()

Stage 1 Module 2 completed.
Overall Score: 73.75
Overall Level: Moderate Stage0 foundation
Possible Targets: ['Medical Condition', 'Test Results']
Risk Columns Count: 4
d:\Med_data\stage1-dataset-intelligence\Stage1_Stage0_Intelligence_Interpretation.csv
d:\Med_data\stage1-dataset-intelligence\Stage1_Stage0_Intelligence_Interpretation.json

,assessment_area,score_out_of_100,level,reason,stage1_action
0,Row strength,90,Strong,Large row count.,Good base for ML experiments.
1,Feature width,80,Good,Many columns available.,Review feature usefulness.
2,Missing values,90,Strong,Low missing percentage.,Proceed with normal review.
3,Duplicate rows,55,Review,Duplicate rows detected.,Decide whether duplicates are valid.
4,Numeric feature strength,80,Good,Multiple numeric columns exist.,"Regression, clustering, anomaly may be possible."
5,Categorical feature strength,80,Good,Multiple categorical columns exist.,Classification or segmentation may be possible.
6,Target clarity,70,Possible,Possible target columns detected.,User must confirm final target.
7,Risk column status,45,Review required,Risk columns detected.,Review before ML.

In [89]:
# STAGE 1 - MODULE 3: ML POSSIBILITY SCORER
# Required: dataset_path, stage0_path, df_stage1

import os, json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_stage1_module3_ml_possibility_scorer():

    main_folder = os.path.dirname(dataset_path)
    stage1_path = os.path.join(main_folder, "stage1-dataset-intelligence")
    os.makedirs(stage1_path, exist_ok=True)

    scores_csv = os.path.join(stage1_path, "Stage1_ML_Possibility_Scores.csv")
    top3_csv = os.path.join(stage1_path, "Stage1_Top_3_Directions.csv")
    summary_json = os.path.join(stage1_path, "Stage1_Module3_Summary.json")
    short_txt = os.path.join(stage1_path, "Stage1_Module3_Short_Result.txt")

    risk_path = os.path.join(
        stage0_path,
        "23_stage1_ready_export",
        "risk_columns_for_review.csv"
    )

    rows = int(df_stage1.shape[0])
    cols = int(df_stage1.shape[1])

    numeric_cols = [str(c) for c in df_stage1.select_dtypes(include=["number"]).columns]
    cat_cols = [str(c) for c in df_stage1.select_dtypes(include=["object", "category", "bool"]).columns]

    missing_pct = round(float(df_stage1.isna().mean().mean() * 100), 4)
    duplicate_rows = int(df_stage1.duplicated().sum())

    risk_cols = []
    if os.path.exists(risk_path):
        temp = pd.read_csv(risk_path)
        if "column_name" in temp.columns:
            risk_cols = temp["column_name"].dropna().astype(str).tolist()

    target_words = [
        "target", "label", "class", "result", "outcome",
        "condition", "status", "diagnosis", "risk", "score"
    ]

    class_targets = []
    reg_targets = []

    for col in df_stage1.columns:
        s = df_stage1[col]
        name = str(col).lower()
        unique_count = int(s.nunique(dropna=True))
        miss = float(s.isna().mean() * 100)

        target_like = any(w in name for w in target_words)

        if target_like and unique_count > 1 and miss < 40:
            if unique_count <= 30:
                class_targets.append(str(col))
            elif pd.api.types.is_numeric_dtype(s):
                reg_targets.append(str(col))

    low_card_cols = [
        str(c) for c in df_stage1.columns
        if 2 <= df_stage1[c].nunique(dropna=True) <= 30
    ]

    def base_score():
        score = 50

        if rows >= 10000:
            score += 20
        elif rows >= 1000:
            score += 12
        elif rows >= 300:
            score += 5
        else:
            score -= 10

        if cols >= 10:
            score += 10
        elif cols >= 4:
            score += 5
        else:
            score -= 10

        if missing_pct > 30:
            score -= 15
        elif missing_pct > 10:
            score -= 7

        if duplicate_rows > 0:
            score -= 3

        if len(risk_cols) > 0:
            score -= 5

        return max(0, min(100, score))

    b = base_score()
    results = []

    def add(direction, score, reason, target, metrics, confirm):
        score = int(max(0, min(100, score)))

        if score >= 80:
            level = "Highly suitable"
        elif score >= 60:
            level = "Moderately suitable"
        elif score >= 40:
            level = "Weakly suitable"
        else:
            level = "Not suitable yet"

        results.append({
            "direction": direction,
            "score_out_of_100": score,
            "suitability_level": level,
            "possible_target": target,
            "reason": reason,
            "recommended_metrics": metrics,
            "required_user_confirmation": confirm
        })

    add(
        "Prediction",
        b + (15 if class_targets or reg_targets else -15),
        "Possible if a meaningful target column is confirmed.",
        str(class_targets + reg_targets),
        "Depends on target type",
        "Confirm prediction goal and target column."
    )

    add(
        "Classification",
        b + (20 if class_targets else 5 if low_card_cols else -20),
        "Suitable when a meaningful low-cardinality target exists.",
        str(class_targets if class_targets else low_card_cols[:5]),
        "F1, Recall, Precision, Accuracy, ROC-AUC",
        "Confirm categorical target and class meaning."
    )

    add(
        "Regression",
        b + (20 if reg_targets else 5 if len(numeric_cols) >= 2 else -20),
        "Suitable when a meaningful numeric target exists.",
        str(reg_targets),
        "MAE, RMSE, R2",
        "Confirm numeric target column."
    )

    add(
        "Clustering",
        b + (15 if len(numeric_cols) >= 2 else -10),
        "Useful when no target is confirmed but grouping records is valuable.",
        "No target required",
        "Silhouette score, cluster profiles",
        "Confirm clustering purpose and useful features."
    )

    add(
        "Anomaly Detection",
        b + (10 if len(numeric_cols) >= 2 and rows >= 500 else -10),
        "Useful if unusual records are important.",
        "No target required",
        "Anomaly review, domain validation",
        "Confirm what type of anomaly matters."
    )

    add(
        "Reporting / Dashboard",
        b + 20,
        "Usually useful for tabular datasets even before ML.",
        "No target required",
        "KPIs, summaries, charts",
        "Confirm reporting questions."
    )

    add(
        "Research",
        b + (15 if len(numeric_cols) + len(cat_cols) >= 4 else 0),
        "Useful if dataset supports questions, patterns, or comparisons.",
        "Depends on research question",
        "Statistical summaries, tests, models",
        "Confirm research objective."
    )

    scores_df = pd.DataFrame(results)
    scores_df = scores_df.sort_values("score_out_of_100", ascending=False)
    top3_df = scores_df.head(3)

    scores_df.to_csv(scores_csv, index=False)
    top3_df.to_csv(top3_csv, index=False)

    summary = {
        "stage": "Stage 1 Module 3 - ML Possibility Scorer",
        "created_on": str(datetime.now()),
        "rows": rows,
        "columns": cols,
        "numeric_columns_count": len(numeric_cols),
        "categorical_columns_count": len(cat_cols),
        "missing_percentage": missing_pct,
        "duplicate_rows": duplicate_rows,
        "risk_columns_count": len(risk_cols),
        "classification_targets": class_targets,
        "regression_targets": reg_targets,
        "top_3_directions": top3_df.to_dict(orient="records"),
        "next_module": "Stage 1 Module 4 - Interactive User Decision Interview"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    with open(short_txt, "w", encoding="utf-8") as f:
        f.write("STAGE 1 MODULE 3 COMPLETED\n")
        f.write("Top directions saved in: " + top3_csv + "\n")
        f.write("Next: Stage 1 Module 4\n")

    print("Stage 1 Module 3 completed.")
    print("Rows:", rows)
    print("Columns:", cols)
    print("Missing %:", missing_pct)
    print("Risk columns:", len(risk_cols))
    print("Top 3 directions:")
    display(top3_df)

    return scores_df, top3_df, summary


stage1_scores_df, stage1_top3_df, stage1_module3_summary = run_stage1_module3_ml_possibility_scorer()

Stage 1 Module 3 completed.
Rows: 55500
Columns: 15
Missing %: 0.0
Risk columns: 4
Top 3 directions:

,direction,score_out_of_100,suitability_level,possible_target,reason,recommended_metrics,required_user_confirmation
1,Classification,92,Highly suitable,"['medical_condition', 'test_results']",Suitable when a meaningful low-cardinality tar...,"F1, Recall, Precision, Accuracy, ROC-AUC",Confirm categorical target and class meaning.
5,Reporting / Dashboard,92,Highly suitable,No target required,Usually useful for tabular datasets even befor...,"KPIs, summaries, charts",Confirm reporting questions.
0,Prediction,87,Highly suitable,"['medical_condition', 'test_results']",Possible if a meaningful target column is conf...,Depends on target type,Confirm prediction goal and target column.

In [91]:
# STAGE 1 - MODULE 4: INTERACTIVE USER DECISION INTERVIEW
# Required: dataset_path, df_stage1
# Optional: stage1_top3_df

import os, json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_stage1_module4_user_interview():

    main_folder = os.path.dirname(dataset_path)
    stage1_path = os.path.join(main_folder, "stage1-dataset-intelligence")
    os.makedirs(stage1_path, exist_ok=True)

    answers_json = os.path.join(stage1_path, "Stage1_User_Answers.json")
    answers_csv = os.path.join(stage1_path, "Stage1_User_Answers.csv")
    short_txt = os.path.join(stage1_path, "Stage1_Module4_Short_Result.txt")

    print("STAGE 1 MODULE 4: USER DECISION INTERVIEW")
    print("-" * 45)
    print("Please answer briefly. Press Enter if unsure.")
    print()

    top_directions = []

    try:
        if "stage1_top3_df" in globals():
            if "direction" in stage1_top3_df.columns:
                top_directions = stage1_top3_df["direction"].astype(str).tolist()
    except:
        top_directions = []

    print("Suggested top directions from Module 3:")
    print(top_directions)
    print()

    questions = [
        ("main_goal", "What is your main goal with this dataset?"),
        ("preferred_direction", "Preferred direction: prediction / classification / regression / clustering / anomaly / reporting / research?"),
        ("preferred_target", "Which column do you think should be the target?"),
        ("forbidden_columns", "Any columns forbidden for ML? Separate by comma."),
        ("exclude_sensitive", "Should PII/sensitive columns be excluded? yes/no"),
        ("priority", "Priority: explainability / accuracy / speed / research value?"),
        ("use_case", "Use case: business / academic / dashboard / production / experiment?"),
        ("known_issues", "Any known errors, bias, or special rules?"),
        ("approval_to_continue", "Can Stage 1 continue to final direction planning? yes/no")
    ]

    rows = []

    for key, question in questions:
        answer = input(question + " ")
        rows.append({
            "question_key": key,
            "question": question,
            "user_answer": answer.strip()
        })

    answers_df = pd.DataFrame(rows)
    answers_df.to_csv(answers_csv, index=False)

    answers_dict = {
        "stage": "Stage 1 Module 4 - Interactive User Decision Interview",
        "created_on": str(datetime.now()),
        "dataset_path": dataset_path,
        "rows": int(df_stage1.shape[0]),
        "columns": int(df_stage1.shape[1]),
        "suggested_top_directions": top_directions,
        "answers": rows,
        "next_module": "Stage 1 Module 5 - Target and Column Use Decision"
    }

    with open(answers_json, "w", encoding="utf-8") as f:
        json.dump(answers_dict, f, indent=4, ensure_ascii=False, default=str)

    with open(short_txt, "w", encoding="utf-8") as f:
        f.write("STAGE 1 MODULE 4 COMPLETED\n")
        f.write("User answers saved.\n")
        f.write("Next: Stage 1 Module 5\n")

    print()
    print("Stage 1 Module 4 completed.")
    print(answers_csv)
    print(answers_json)

    display(answers_df)

    return answers_df, answers_dict


stage1_user_answers_df, stage1_user_answers = run_stage1_module4_user_interview()

STAGE 1 MODULE 4: USER DECISION INTERVIEW
---------------------------------------------
Please answer briefly. Press Enter if unsure.

Suggested top directions from Module 3:
['Classification', 'Reporting / Dashboard', 'Prediction']

What is your main goal with this dataset?  'Classification'
Preferred direction: prediction / classification / regression / clustering / anomaly / reporting / research?  classification
Which column do you think should be the target?  any
Any columns forbidden for ML? Separate by comma.  no
Should PII/sensitive columns be excluded? yes/no  no
Priority: explainability / accuracy / speed / research value?  explainability
Use case: business / academic / dashboard / production / experiment?  academic
Any known errors, bias, or special rules?  no
Can Stage 1 continue to final direction planning? yes/no  no

Stage 1 Module 4 completed.
d:\Med_data\stage1-dataset-intelligence\Stage1_User_Answers.csv
d:\Med_data\stage1-dataset-intelligence\Stage1_User_Answers.json

,question_key,question,user_answer
0,main_goal,What is your main goal with this dataset?,'Classification'
1,preferred_direction,Preferred direction: prediction / classificati...,classification
2,preferred_target,Which column do you think should be the target?,any
3,forbidden_columns,Any columns forbidden for ML? Separate by comma.,no
4,exclude_sensitive,Should PII/sensitive columns be excluded? yes/no,no
5,priority,Priority: explainability / accuracy / speed / ...,explainability
6,use_case,Use case: business / academic / dashboard / pr...,academic
7,known_issues,"Any known errors, bias, or special rules?",no
8,approval_to_continue,Can Stage 1 continue to final direction planni...,no

In [93]:
# STAGE 1 - MODULE 5: TARGET AND COLUMN USE DECISION
# Required: dataset_path, stage0_path, df_stage1

import os, json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_stage1_module5_target_column_use_decision():

    main_folder = os.path.dirname(dataset_path)
    stage1_path = os.path.join(main_folder, "stage1-dataset-intelligence")
    os.makedirs(stage1_path, exist_ok=True)

    column_plan_csv = os.path.join(stage1_path, "Stage1_Column_Use_Plan.csv")
    target_decision_csv = os.path.join(stage1_path, "Stage1_Target_Decision.csv")
    summary_json = os.path.join(stage1_path, "Stage1_Module5_Summary.json")
    short_txt = os.path.join(stage1_path, "Stage1_Module5_Short_Result.txt")

    user_answers_csv = os.path.join(stage1_path, "Stage1_User_Answers.csv")
    risk_csv = os.path.join(stage0_path, "23_stage1_ready_export", "risk_columns_for_review.csv")

    preferred_target = ""
    forbidden_cols = []
    exclude_sensitive = "yes"

    if os.path.exists(user_answers_csv):
        ans = pd.read_csv(user_answers_csv)
        if "question_key" in ans.columns and "user_answer" in ans.columns:
            d = dict(zip(ans["question_key"], ans["user_answer"].fillna("").astype(str)))
            preferred_target = d.get("preferred_target", "").strip()
            forbidden_cols = [x.strip() for x in d.get("forbidden_columns", "").split(",") if x.strip()]
            exclude_sensitive = d.get("exclude_sensitive", "yes").strip().lower()

    risk_cols = []
    risk_types = {}

    if os.path.exists(risk_csv):
        r = pd.read_csv(risk_csv)
        if "column_name" in r.columns:
            risk_cols = r["column_name"].dropna().astype(str).tolist()
        if "risk_type" in r.columns and "column_name" in r.columns:
            risk_types = dict(zip(r["column_name"].astype(str), r["risk_type"].astype(str)))

    target_words = ["target", "label", "class", "result", "outcome", "condition", "status", "diagnosis", "risk", "score"]

    column_rows = []
    target_rows = []

    for col in df_stage1.columns:
        col_name = str(col)
        col_low = col_name.lower()
        s = df_stage1[col]

        unique_count = int(s.nunique(dropna=True))
        missing_pct = round(float(s.isna().mean() * 100), 4)

        is_numeric = pd.api.types.is_numeric_dtype(s)
        is_risk = col_name in risk_cols
        is_forbidden = col_name in forbidden_cols
        is_user_target = preferred_target.lower() == col_low if preferred_target else False
        is_auto_target = any(w in col_low for w in target_words) and unique_count > 1

        if is_user_target:
            column_role = "Confirmed Target Candidate"
            use_decision = "Use as target after final confirmation"
        elif is_forbidden:
            column_role = "Forbidden by user"
            use_decision = "Exclude"
        elif is_risk and exclude_sensitive in ["yes", "y"]:
            column_role = "Risk column"
            use_decision = "Review or exclude"
        elif "_missing" in col_low:
            column_role = "Missing indicator feature"
            use_decision = "Use as feature if useful"
        elif unique_count <= 1:
            column_role = "Constant or weak column"
            use_decision = "Exclude"
        elif is_auto_target:
            column_role = "Possible target"
            use_decision = "Review as target or feature"
        else:
            column_role = "Possible feature"
            use_decision = "Use as feature"

        column_rows.append({
            "column_name": col_name,
            "dtype": str(s.dtype),
            "unique_values": unique_count,
            "missing_percentage": missing_pct,
            "risk_type": risk_types.get(col_name, ""),
            "column_role": column_role,
            "use_decision": use_decision
        })

        if is_user_target or is_auto_target:
            if unique_count <= 30:
                ml_type = "Classification"
            elif is_numeric:
                ml_type = "Regression"
            else:
                ml_type = "Needs review"

            target_rows.append({
                "target_column": col_name,
                "source": "User selected" if is_user_target else "Auto suggested",
                "unique_values": unique_count,
                "missing_percentage": missing_pct,
                "possible_ml_type": ml_type,
                "decision_status": "Needs final confirmation"
            })

    column_plan_df = pd.DataFrame(column_rows)
    target_decision_df = pd.DataFrame(target_rows)

    if target_decision_df.empty:
        target_decision_df = pd.DataFrame({
            "message": ["No target candidate found. User must confirm target or choose unsupervised/EDA."]
        })

    column_plan_df.to_csv(column_plan_csv, index=False)
    target_decision_df.to_csv(target_decision_csv, index=False)

    excluded_count = int((column_plan_df["use_decision"] == "Exclude").sum())
    review_count = int(column_plan_df["use_decision"].str.contains("Review", case=False, na=False).sum())
    feature_count = int(column_plan_df["use_decision"].str.contains("feature", case=False, na=False).sum())

    summary = {
        "stage": "Stage 1 Module 5 - Target and Column Use Decision",
        "created_on": str(datetime.now()),
        "dataset_path": dataset_path,
        "rows": int(df_stage1.shape[0]),
        "columns": int(df_stage1.shape[1]),
        "preferred_target_from_user": preferred_target,
        "forbidden_columns_from_user": forbidden_cols,
        "risk_columns_count": len(risk_cols),
        "feature_columns_count": feature_count,
        "review_columns_count": review_count,
        "excluded_columns_count": excluded_count,
        "next_module": "Stage 1 Module 6 - Top Direction Recommendation"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    with open(short_txt, "w", encoding="utf-8") as f:
        f.write("STAGE 1 MODULE 5 COMPLETED\n")
        f.write("Column use plan saved.\n")
        f.write("Target decision file saved.\n")
        f.write("Next: Stage 1 Module 6\n")

    print("Stage 1 Module 5 completed.")
    print("Feature columns:", feature_count)
    print("Review columns:", review_count)
    print("Excluded columns:", excluded_count)
    print(column_plan_csv)
    print(target_decision_csv)
    print(summary_json)

    display(column_plan_df)
    display(target_decision_df)

    return column_plan_df, target_decision_df, summary


stage1_column_plan_df, stage1_target_decision_df, stage1_module5_summary = run_stage1_module5_target_column_use_decision()

Stage 1 Module 5 completed.
Feature columns: 15
Review columns: 2
Excluded columns: 0
d:\Med_data\stage1-dataset-intelligence\Stage1_Column_Use_Plan.csv
d:\Med_data\stage1-dataset-intelligence\Stage1_Target_Decision.csv
d:\Med_data\stage1-dataset-intelligence\Stage1_Module5_Summary.json

,column_name,dtype,unique_values,missing_percentage,risk_type,column_role,use_decision
0,name,object,49992,0.0,possible_pii,Possible feature,Use as feature
1,age,int64,77,0.0,possible_sensitive,Possible feature,Use as feature
2,gender,object,2,0.0,possible_sensitive,Possible feature,Use as feature
3,blood_type,object,8,0.0,,Possible feature,Use as feature
4,medical_condition,object,6,0.0,,Possible target,Review as target or feature
5,date_of_admission,object,1827,0.0,,Possible feature,Use as feature
6,doctor,object,40341,0.0,,Possible feature,Use as feature
7,hospital,object,39876,0.0,,Possible feature,Use as feature
8,insurance_provider,object,5,0.0,,Possible feature,Use as feature
9,billing_amount,float64,50000,0.0,,Possible feature,Use as feature
10,room_number,int64,400,0.0,,Possible feature,Use as feature
11,admission_type,object,3,0.0,,Possible feature,Use as feature
12,discharge_date,object,1856,0.0,,Possible feature,Use as feature
13,medication,object,5,0.0,,Possible feature,Use as feature
14,test_results,object,3,0.0,possible_target_or_leakage,Possible target,Review as target or feature

,target_column,source,unique_values,missing_percentage,possible_ml_type,decision_status
0,medical_condition,Auto suggested,6,0.0,Classification,Needs final confirmation
1,test_results,Auto suggested,3,0.0,Classification,Needs final confirmation

In [95]:
# STAGE 1 - MODULE 6: TOP DIRECTION RECOMMENDATION
# Required: dataset_path, df_stage1

import os, json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_stage1_module6_top_direction_recommendation():

    main_folder = os.path.dirname(dataset_path)
    stage1_path = os.path.join(main_folder, "stage1-dataset-intelligence")
    os.makedirs(stage1_path, exist_ok=True)

    scores_csv = os.path.join(stage1_path, "Stage1_ML_Possibility_Scores.csv")
    top3_csv = os.path.join(stage1_path, "Stage1_Top_3_Directions_Final.csv")
    report_txt = os.path.join(stage1_path, "Stage1_Decision_Report.txt")
    summary_json = os.path.join(stage1_path, "Stage1_Module6_Summary.json")

    user_answers_csv = os.path.join(stage1_path, "Stage1_User_Answers.csv")
    column_plan_csv = os.path.join(stage1_path, "Stage1_Column_Use_Plan.csv")
    target_decision_csv = os.path.join(stage1_path, "Stage1_Target_Decision.csv")

    if os.path.exists(scores_csv):
        scores_df = pd.read_csv(scores_csv)
    else:
        raise FileNotFoundError("Stage1_ML_Possibility_Scores.csv not found. Run Module 3 first.")

    user_goal = ""
    user_direction = ""
    user_target = ""

    if os.path.exists(user_answers_csv):
        ans = pd.read_csv(user_answers_csv)
        if "question_key" in ans.columns and "user_answer" in ans.columns:
            d = dict(zip(ans["question_key"], ans["user_answer"].fillna("").astype(str)))
            user_goal = d.get("main_goal", "")
            user_direction = d.get("preferred_direction", "")
            user_target = d.get("preferred_target", "")

    excluded_cols = []
    review_cols = []
    feature_cols = []

    if os.path.exists(column_plan_csv):
        plan = pd.read_csv(column_plan_csv)
        if "use_decision" in plan.columns and "column_name" in plan.columns:
            excluded_cols = plan[plan["use_decision"].str.contains("Exclude", case=False, na=False)]["column_name"].astype(str).tolist()
            review_cols = plan[plan["use_decision"].str.contains("Review", case=False, na=False)]["column_name"].astype(str).tolist()
            feature_cols = plan[plan["use_decision"].str.contains("feature", case=False, na=False)]["column_name"].astype(str).tolist()
    else:
        plan = pd.DataFrame()

    target_candidates = []

    if os.path.exists(target_decision_csv):
        target_df = pd.read_csv(target_decision_csv)
        if "target_column" in target_df.columns:
            target_candidates = target_df["target_column"].dropna().astype(str).tolist()
    else:
        target_df = pd.DataFrame()

    scores_df = scores_df.sort_values("score_out_of_100", ascending=False).copy()

    if user_direction:
        scores_df["user_preference_boost"] = scores_df["direction"].astype(str).str.lower().apply(
            lambda x: 10 if user_direction.lower() in x else 0
        )
    else:
        scores_df["user_preference_boost"] = 0

    scores_df["final_score"] = scores_df["score_out_of_100"] + scores_df["user_preference_boost"]
    scores_df["final_score"] = scores_df["final_score"].clip(upper=100)

    final_top3 = scores_df.sort_values("final_score", ascending=False).head(3).copy()
    final_top3["rank"] = range(1, len(final_top3) + 1)

    final_top3["stage1_decision"] = final_top3["rank"].apply(
        lambda x: "Primary recommendation" if x == 1 else "Secondary option"
    )

    final_top3.to_csv(top3_csv, index=False)

    primary_direction = final_top3.iloc[0]["direction"] if len(final_top3) > 0 else "Not decided"
    primary_score = final_top3.iloc[0]["final_score"] if len(final_top3) > 0 else 0

    blockers = []

    if len(review_cols) > 0:
        blockers.append("Review risk/sensitive/leakage columns.")

    if primary_direction in ["Classification", "Regression", "Prediction"]:
        if not user_target and not target_candidates:
            blockers.append("Target column not confirmed.")

    if len(feature_cols) == 0:
        blockers.append("No confirmed feature columns found.")

    if not blockers:
        blockers.append("No major blocker detected automatically.")

    summary = {
        "stage": "Stage 1 Module 6 - Top Direction Recommendation",
        "created_on": str(datetime.now()),
        "dataset_path": dataset_path,
        "rows": int(df_stage1.shape[0]),
        "columns": int(df_stage1.shape[1]),
        "user_goal": user_goal,
        "user_preferred_direction": user_direction,
        "user_preferred_target": user_target,
        "primary_direction": str(primary_direction),
        "primary_direction_score": float(primary_score),
        "target_candidates": target_candidates,
        "feature_columns_count": len(feature_cols),
        "review_columns_count": len(review_cols),
        "excluded_columns_count": len(excluded_cols),
        "blockers": blockers,
        "next_module": "Stage 1 Module 7 - Stage2 Handover Package"
    }

    with open(summary_json, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False, default=str)

    lines = [
        "STAGE 1 MODULE 6 COMPLETED",
        "Primary Direction: " + str(primary_direction),
        "Primary Score: " + str(primary_score),
        "User Goal: " + str(user_goal),
        "User Target: " + str(user_target),
        "Target Candidates: " + str(target_candidates),
        "Feature Columns Count: " + str(len(feature_cols)),
        "Review Columns Count: " + str(len(review_cols)),
        "Excluded Columns Count: " + str(len(excluded_cols)),
        "Blockers: " + str(blockers),
        "Next: Stage 1 Module 7"
    ]

    with open(report_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print("Stage 1 Module 6 completed.")
    print("Primary Direction:", primary_direction)
    print("Primary Score:", primary_score)
    print("Blockers:", blockers)
    print(top3_csv)
    print(report_txt)
    print(summary_json)

    display(final_top3)

    return final_top3, summary


stage1_final_top3_df, stage1_module6_summary = run_stage1_module6_top_direction_recommendation()

Stage 1 Module 6 completed.
Primary Direction: Classification
Primary Score: 100
Blockers: ['Review risk/sensitive/leakage columns.']
d:\Med_data\stage1-dataset-intelligence\Stage1_Top_3_Directions_Final.csv
d:\Med_data\stage1-dataset-intelligence\Stage1_Decision_Report.txt
d:\Med_data\stage1-dataset-intelligence\Stage1_Module6_Summary.json

,direction,score_out_of_100,suitability_level,possible_target,reason,recommended_metrics,required_user_confirmation,user_preference_boost,final_score,rank,stage1_decision
0,Classification,92,Highly suitable,"['medical_condition', 'test_results']",Suitable when a meaningful low-cardinality tar...,"F1, Recall, Precision, Accuracy, ROC-AUC",Confirm categorical target and class meaning.,10,100,1,Primary recommendation
1,Reporting / Dashboard,92,Highly suitable,No target required,Usually useful for tabular datasets even befor...,"KPIs, summaries, charts",Confirm reporting questions.,0,92,2,Secondary option
2,Prediction,87,Highly suitable,"['medical_condition', 'test_results']",Possible if a meaningful target column is conf...,Depends on target type,Confirm prediction goal and target column.,0,87,3,Secondary option

In [97]:
# STAGE 1 - MODULE 7: STAGE2 HANDOVER PACKAGE
# Required: dataset_path, df_stage1

import os, json
import pandas as pd
from datetime import datetime
from IPython.display import display


def run_stage1_module7_stage2_handover():

    main_folder = os.path.dirname(dataset_path)
    stage1_path = os.path.join(main_folder, "stage1-dataset-intelligence")
    out = os.path.join(stage1_path, "Stage2_Handover_Package")
    os.makedirs(out, exist_ok=True)

    column_plan_csv = os.path.join(stage1_path, "Stage1_Column_Use_Plan.csv")
    target_csv = os.path.join(stage1_path, "Stage1_Target_Decision.csv")
    top3_csv = os.path.join(stage1_path, "Stage1_Top_3_Directions_Final.csv")
    user_csv = os.path.join(stage1_path, "Stage1_User_Answers.csv")

    allowed_csv = os.path.join(out, "Stage2_Allowed_Features.csv")
    excluded_csv = os.path.join(out, "Stage2_Excluded_Columns.csv")
    prep_csv = os.path.join(out, "Stage2_Preprocessing_Requirements.csv")
    plan_txt = os.path.join(out, "Stage2_Modeling_Plan.txt")
    next_prompt_txt = os.path.join(out, "Stage2_Next_Prompt.txt")
    handover_json = os.path.join(out, "Stage2_Handover_Contract.json")

    def read_csv(path):
        return pd.read_csv(path) if os.path.exists(path) else pd.DataFrame()

    plan_df = read_csv(column_plan_csv)
    target_df = read_csv(target_csv)
    top3_df = read_csv(top3_csv)
    user_df = read_csv(user_csv)

    user_target = ""
    if not user_df.empty and {"question_key", "user_answer"}.issubset(user_df.columns):
        ans = dict(zip(user_df["question_key"], user_df["user_answer"].fillna("").astype(str)))
        user_target = ans.get("preferred_target", "").strip()

    primary_direction = "Not decided"
    if not top3_df.empty and "direction" in top3_df.columns:
        primary_direction = str(top3_df.iloc[0]["direction"])

    if user_target:
        final_target = user_target
    elif not target_df.empty and "target_column" in target_df.columns:
        final_target = str(target_df.iloc[0]["target_column"])
    else:
        final_target = ""

    allowed = []
    excluded = []
    review = []

    if not plan_df.empty and {"column_name", "use_decision"}.issubset(plan_df.columns):
        for _, row in plan_df.iterrows():
            col = str(row["column_name"])
            decision = str(row["use_decision"]).lower()

            if col == final_target:
                continue
            elif "use as feature" in decision:
                allowed.append(col)
            elif "exclude" in decision:
                excluded.append(col)
            elif "review" in decision:
                review.append(col)

    if not allowed:
        allowed = [str(c) for c in df_stage1.columns if str(c) != final_target]

    allowed_df = pd.DataFrame({"allowed_feature": allowed})
    excluded_df = pd.DataFrame({
        "column_name": excluded + review,
        "stage2_action": ["Exclude"] * len(excluded) + ["Review before use"] * len(review)
    })

    allowed_df.to_csv(allowed_csv, index=False)
    excluded_df.to_csv(excluded_csv, index=False)

    prep_rows = []

    for col in allowed:
        if col not in df_stage1.columns:
            continue

        s = df_stage1[col]
        dtype = str(s.dtype)
        miss = round(float(s.isna().mean() * 100), 4)
        unique = int(s.nunique(dropna=True))

        if pd.api.types.is_numeric_dtype(s):
            prep = "Impute if missing; scale if model needs it."
        elif unique <= 30:
            prep = "Impute if missing; encode categorical values."
        else:
            prep = "Review high cardinality; group or encode carefully."

        prep_rows.append({
            "column_name": col,
            "dtype": dtype,
            "missing_percentage": miss,
            "unique_values": unique,
            "preprocessing_need": prep
        })

    prep_df = pd.DataFrame(prep_rows)
    prep_df.to_csv(prep_csv, index=False)

    contract = {
        "stage": "Stage 1 Module 7 - Stage2 Handover",
        "created_on": str(datetime.now()),
        "dataset_for_stage2": os.path.join(main_folder, "dataset_for_stage_1.csv"),
        "primary_direction": primary_direction,
        "target_column": final_target,
        "allowed_features_count": len(allowed),
        "excluded_columns_count": len(excluded),
        "review_columns_count": len(review),
        "allowed_features_file": allowed_csv,
        "excluded_columns_file": excluded_csv,
        "preprocessing_requirements_file": prep_csv,
        "next_action": "Start Stage 2 preprocessing and baseline modeling only after final confirmation."
    }

    with open(handover_json, "w", encoding="utf-8") as f:
        json.dump(contract, f, indent=4, ensure_ascii=False, default=str)

    plan_lines = [
        "STAGE2 MODELING PLAN",
        "Primary direction: " + primary_direction,
        "Target column: " + str(final_target),
        "Allowed features: " + str(len(allowed)),
        "Excluded columns: " + str(len(excluded)),
        "Review columns: " + str(len(review)),
        "Do not use review columns until cleared.",
        "Do not train final model before target confirmation."
    ]

    with open(plan_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(plan_lines))

    prompt_lines = [
        "STAGE2 NEXT PROMPT",
        "Load dataset_for_stage_1.csv.",
        "Use Stage2_Allowed_Features.csv.",
        "Exclude columns in Stage2_Excluded_Columns.csv.",
        "Apply preprocessing from Stage2_Preprocessing_Requirements.csv.",
        "Build baseline model only for confirmed direction and target.",
        "Report metrics, limitations, and risks."
    ]

    with open(next_prompt_txt, "w", encoding="utf-8") as f:
        f.write("\n".join(prompt_lines))

    print("Stage 1 Module 7 completed.")
    print("Primary direction:", primary_direction)
    print("Target column:", final_target)
    print("Allowed features:", len(allowed))
    print("Excluded columns:", len(excluded))
    print("Review columns:", len(review))
    print("Output folder:", out)

    display(allowed_df.head())
    display(excluded_df.head())
    display(prep_df.head())

    return contract, prep_df


stage2_handover_contract, stage2_prep_df = run_stage1_module7_stage2_handover()

Stage 1 Module 7 completed.
Primary direction: Classification
Target column: any
Allowed features: 13
Excluded columns: 0
Review columns: 2
Output folder: d:\Med_data\stage1-dataset-intelligence\Stage2_Handover_Package

     allowed_feature
0               name
1                age
2             gender
3         blood_type
4  date_of_admission

         column_name      stage2_action
0  medical_condition  Review before use
1       test_results  Review before use

,column_name,dtype,missing_percentage,unique_values,preprocessing_need
0,name,object,0.0,49992,Review high cardinality; group or encode caref...
1,age,int64,0.0,77,Impute if missing; scale if model needs it.
2,gender,object,0.0,2,Impute if missing; encode categorical values.
3,blood_type,object,0.0,8,Impute if missing; encode categorical values.
4,date_of_admission,object,0.0,1827,Review high cardinality; group or encode caref...

In [23]:
# STAGE 1 - MODULE 8
# Dataset Knowledge Synthesis and ML Research Base Builder
# Required in notebook: dataset_path, stage0_path
# Optional: df_stage1

import os
import json
import shutil
from datetime import datetime

import pandas as pd
import numpy as np
from IPython.display import display


def run_stage1_module8_knowledge_synthesis():
    # ---------- paths ----------
    if "dataset_path" not in globals():
        raise NameError("dataset_path is not defined. Define original dataset_path first.")

    main_folder = os.path.dirname(dataset_path)
    local_stage0_path = globals().get("stage0_path", os.path.join(main_folder, "stage0-launch-pad"))
    stage1_path = os.path.join(main_folder, "stage1-dataset-intelligence")

    base = os.path.join(main_folder, "Base_Folder_for_ML_Research_After_Stage_0_and_1")
    core = os.path.join(base, "01_Core_Dataset")
    intel = os.path.join(base, "02_Dataset_Intelligence")
    decision = os.path.join(base, "03_ML_Decision_Base")
    guide = os.path.join(base, "04_Human_Guidance_and_Miscellaneous")

    for p in [base, core, intel, decision, guide]:
        os.makedirs(p, exist_ok=True)

    stage1_dataset = os.path.join(main_folder, "dataset_for_stage_1.csv")
    stage2_dataset = os.path.join(core, "dataset_for_stage_2.csv")

    # ---------- safe readers ----------
    def read_csv(path):
        try:
            return pd.read_csv(path)
        except Exception:
            return pd.DataFrame()

    def read_json(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return {}

    def save_json(path, data):
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False, default=str)

    def pct(x):
        try:
            return round(float(x) * 100, 4)
        except Exception:
            return 0.0

    # ---------- load dataset ----------
    if "df_stage1" in globals():
        df2 = globals()["df_stage1"].copy()
    elif os.path.exists(stage1_dataset):
        df2 = pd.read_csv(stage1_dataset)
    else:
        raise FileNotFoundError("dataset_for_stage_1.csv not found. Run Stage0 Layer 23 first.")

    df2.to_csv(stage2_dataset, index=False)

    # ---------- important source files ----------
    total_intel_json = os.path.join(local_stage0_path, "24_stage0_total_intelligence", "stage0_total_intelligence.json")
    handover_json = os.path.join(local_stage0_path, "23_stage1_ready_export", "stage1_handover_contract.json")
    risk_csv = os.path.join(local_stage0_path, "23_stage1_ready_export", "risk_columns_for_review.csv")
    missing_map_csv = os.path.join(local_stage0_path, "23_stage1_ready_export", "missing_indicator_map.csv")

    m1_json = os.path.join(stage1_path, "Stage1_Input_Summary.json")
    m2_csv = os.path.join(stage1_path, "Stage1_Stage0_Intelligence_Interpretation.csv")
    m3_scores_csv = os.path.join(stage1_path, "Stage1_ML_Possibility_Scores.csv")
    m4_answers_csv = os.path.join(stage1_path, "Stage1_User_Answers.csv")
    m5_plan_csv = os.path.join(stage1_path, "Stage1_Column_Use_Plan.csv")
    m5_target_csv = os.path.join(stage1_path, "Stage1_Target_Decision.csv")
    m6_top3_csv = os.path.join(stage1_path, "Stage1_Top_3_Directions_Final.csv")

    st2_allowed_csv = os.path.join(stage1_path, "Stage2_Handover_Package", "Stage2_Allowed_Features.csv")
    st2_excluded_csv = os.path.join(stage1_path, "Stage2_Handover_Package", "Stage2_Excluded_Columns.csv")
    st2_prep_csv = os.path.join(stage1_path, "Stage2_Handover_Package", "Stage2_Preprocessing_Requirements.csv")
    st2_contract_json = os.path.join(stage1_path, "Stage2_Handover_Package", "Stage2_Handover_Contract.json")

    total_intel = read_json(total_intel_json)
    handover = read_json(handover_json)
    m1 = read_json(m1_json)
    st2_contract = read_json(st2_contract_json)

    risk_df = read_csv(risk_csv)
    missing_map_df = read_csv(missing_map_csv)
    m2_df = read_csv(m2_csv)
    scores_df = read_csv(m3_scores_csv)
    answers_df = read_csv(m4_answers_csv)
    plan_df = read_csv(m5_plan_csv)
    target_df = read_csv(m5_target_csv)
    top3_df = read_csv(m6_top3_csv)
    allowed_df_src = read_csv(st2_allowed_csv)
    excluded_df_src = read_csv(st2_excluded_csv)
    prep_df_src = read_csv(st2_prep_csv)

    # ---------- user answers ----------
    user_answers = {}
    if not answers_df.empty and {"question_key", "user_answer"}.issubset(answers_df.columns):
        user_answers = dict(zip(answers_df["question_key"].astype(str), answers_df["user_answer"].fillna("").astype(str)))

    user_goal = user_answers.get("main_goal", "")
    user_direction = user_answers.get("preferred_direction", "")
    user_target = user_answers.get("preferred_target", "")

    # ---------- useful sets ----------
    risk_types = {}
    if not risk_df.empty and {"column_name", "risk_type"}.issubset(risk_df.columns):
        risk_types = dict(zip(risk_df["column_name"].astype(str), risk_df["risk_type"].astype(str)))

    plan_decisions = {}
    if not plan_df.empty and {"column_name", "use_decision"}.issubset(plan_df.columns):
        plan_decisions = dict(zip(plan_df["column_name"].astype(str), plan_df["use_decision"].astype(str)))

    target_candidates = []
    if not target_df.empty and "target_column" in target_df.columns:
        target_candidates = target_df["target_column"].dropna().astype(str).tolist()
    if not target_candidates:
        target_candidates = total_intel.get("possible_target_columns", []) if isinstance(total_intel.get("possible_target_columns", []), list) else []

    final_target = st2_contract.get("target_column", "") or user_target
    if not final_target and target_candidates:
        final_target = target_candidates[0]

    # ---------- dataset profile ----------
    rows = int(df2.shape[0])
    cols = int(df2.shape[1])
    numeric_cols = [str(c) for c in df2.select_dtypes(include=["number"]).columns]
    cat_cols = [str(c) for c in df2.select_dtypes(include=["object", "category", "bool"]).columns]
    missing_pct = round(float(df2.isna().mean().mean() * 100), 4)
    duplicate_rows = int(df2.duplicated().sum())

    dataset_profile = {
        "created_on": str(datetime.now()),
        "dataset_name": str(os.path.basename(dataset_path)),
        "original_dataset_path": str(dataset_path),
        "dataset_for_stage2": str(stage2_dataset),
        "rows": rows,
        "columns": cols,
        "numeric_columns_count": len(numeric_cols),
        "categorical_columns_count": len(cat_cols),
        "average_missing_percentage": missing_pct,
        "duplicate_rows": duplicate_rows,
        "possible_target_columns": target_candidates,
        "user_preferred_target": user_target,
        "system_selected_target_candidate": final_target,
        "user_goal_low_weight": user_goal,
        "base_folder": str(base)
    }

    save_json(os.path.join(core, "dataset_profile.json"), dataset_profile)
    pd.DataFrame([dataset_profile]).to_csv(os.path.join(core, "dataset_profile.csv"), index=False)

    # ---------- column intelligence ----------
    col_rows = []
    ev_rows = []
    misc_rows = []

    target_words = ["target", "label", "class", "result", "outcome", "condition", "status", "diagnosis", "risk", "score"]

    for col in df2.columns:
        col = str(col)
        s = df2[col]
        low = col.lower()
        uniq = int(s.nunique(dropna=True))
        miss = round(float(s.isna().mean() * 100), 4)
        is_num = pd.api.types.is_numeric_dtype(s)
        risk = risk_types.get(col, "")
        plan_decision = plan_decisions.get(col, "")
        is_target_candidate = col in target_candidates or any(w in low for w in target_words)
        is_missing_flag = low.endswith("_missing")
        is_constant = uniq <= 1
        is_high_card = uniq > 50 and not is_num

        feature_score = 50
        if is_num:
            feature_score += 12
        if 2 <= uniq <= 30:
            feature_score += 8
        if miss > 30:
            feature_score -= 25
        elif miss > 10:
            feature_score -= 10
        if is_constant:
            feature_score -= 45
        if risk:
            feature_score -= 35
        if is_high_card:
            feature_score -= 10
        if is_missing_flag:
            feature_score += 5
        feature_score = int(max(0, min(100, feature_score)))

        target_score = 0
        if is_target_candidate and uniq > 1:
            target_score += 45
        if 2 <= uniq <= 30:
            target_score += 20
        if is_num and uniq > 30:
            target_score += 15
        if miss > 30:
            target_score -= 20
        if risk:
            target_score -= 20
        target_score = int(max(0, min(100, target_score)))

        risk_score = 0
        if risk:
            risk_score += 60
        if miss > 30:
            risk_score += 20
        if is_constant:
            risk_score += 20
        risk_score = int(max(0, min(100, risk_score)))

        if risk:
            rec = "review_before_use"
        elif is_constant:
            rec = "exclude"
        elif col == final_target or target_score >= 60:
            rec = "possible_target"
        elif feature_score >= 60:
            rec = "use_as_feature"
        elif feature_score >= 40:
            rec = "review_before_use"
        else:
            rec = "exclude"

        reason_bits = []
        reason_bits.append("numeric" if is_num else "non_numeric")
        reason_bits.append("missing_" + str(miss) + "%")
        reason_bits.append("unique_" + str(uniq))
        if risk:
            reason_bits.append("risk_" + risk)
        if is_target_candidate:
            reason_bits.append("target_candidate")

        col_rows.append({
            "column_name": col,
            "dtype": str(s.dtype),
            "missing_percentage": miss,
            "unique_values": uniq,
            "is_numeric": bool(is_num),
            "risk_type": risk,
            "stage1_use_decision": plan_decision,
            "feature_score": feature_score,
            "target_score": target_score,
            "risk_score": risk_score,
            "recommended_use": rec,
            "confidence": "medium",
            "reason": "; ".join(reason_bits),
            "requires_user_confirmation": "yes" if rec in ["possible_target", "review_before_use"] else "no"
        })

        if miss > 0:
            ev_rows.append(["missing_values", col, str(miss) + "% missing", "missing strategy needed", "medium", "medium", "create/impute missing strategy"])
        if risk:
            ev_rows.append(["risk_column", col, risk, "review before ML", "high", "high", "exclude or clear by user"])
        if is_constant:
            ev_rows.append(["constant_column", col, "one or zero unique values", "weak ML value", "medium", "medium", "exclude"])
        if is_target_candidate:
            ev_rows.append(["target_candidate", col, "name/shape suggests target", "possible supervised ML", "medium", "medium", "confirm target"])
        if is_high_card:
            misc_rows.append(["high_cardinality_note", col, "many unique text/category values", "may need grouping or special encoding"])

    col_intel_df = pd.DataFrame(col_rows)
    col_intel_path = os.path.join(intel, "column_intelligence.csv")
    col_intel_df.to_csv(col_intel_path, index=False)

    ev_df = pd.DataFrame(ev_rows, columns=["evidence_type", "column_name", "evidence_value", "inference", "severity", "ml_impact", "recommended_action"])
    ev_path = os.path.join(intel, "evidence_to_judgment.csv")
    ev_df.to_csv(ev_path, index=False)

    misc_df = pd.DataFrame(misc_rows, columns=["fact_type", "column_name", "fact", "possible_use"])
    if misc_df.empty:
        misc_df = pd.DataFrame({"message": ["No additional miscellaneous facts generated."]})
    misc_path = os.path.join(intel, "miscellaneous_dataset_facts.csv")
    misc_df.to_csv(misc_path, index=False)

    # ---------- limitations ----------
    limitations = [
        ["column_meaning", "Column meanings are not fully known automatically.", "User/domain confirmation required."],
        ["target", "Target column suggestions are heuristic.", "Reconfirm target before modeling."],
        ["risk", "PII/leakage detection is name-based.", "Review risk columns manually."],
        ["outliers", "Outliers may be valid values.", "Do not remove automatically."],
        ["missing_values", "Missingness may have real meaning.", "Choose strategy carefully."],
        ["correlation", "Correlation does not prove causation.", "Avoid causal claims without design."],
        ["user_feedback", "User preferences are treated as low-weight evidence.", "Verify again before Stage2."],
    ]
    lim_df = pd.DataFrame(limitations, columns=["limitation_area", "limitation", "recommended_protection"])
    lim_path = os.path.join(intel, "dataset_understanding_limitations.csv")
    lim_df.to_csv(lim_path, index=False)

    # ---------- ML direction scorecard ----------
    if not scores_df.empty and "direction" in scores_df.columns:
        ml_score_df = scores_df.copy()
    else:
        ml_score_df = pd.DataFrame([
            ["reporting", 75, "moderately suitable", "Reporting usually works for tabular data."],
            ["research", 70, "moderately suitable", "Research analysis is possible after metadata review."],
            ["clustering", 60 if len(numeric_cols) >= 2 else 35, "depends", "Needs useful features."],
            ["classification", 65 if target_candidates else 35, "depends", "Needs confirmed categorical target."],
            ["regression", 55 if len(numeric_cols) >= 2 else 30, "depends", "Needs confirmed numeric target."],
            ["anomaly_detection", 55 if len(numeric_cols) >= 2 else 30, "depends", "Needs anomaly purpose."],
        ], columns=["direction", "score_out_of_100", "suitability_level", "reason"])

    if not top3_df.empty and "direction" in top3_df.columns:
        top_dirs = top3_df["direction"].astype(str).head(3).tolist()
    else:
        top_dirs = ml_score_df.sort_values("score_out_of_100", ascending=False)["direction"].astype(str).head(3).tolist()

    ml_score_path = os.path.join(decision, "ml_direction_scorecard.csv")
    ml_score_df.to_csv(ml_score_path, index=False)

    # ---------- features/targets/exclusions ----------
    allowed = col_intel_df[col_intel_df["recommended_use"].eq("use_as_feature")]["column_name"].tolist()
    review = col_intel_df[col_intel_df["recommended_use"].eq("review_before_use")]["column_name"].tolist()
    excluded = col_intel_df[col_intel_df["recommended_use"].eq("exclude")]["column_name"].tolist()
    possible_target_df = col_intel_df[col_intel_df["recommended_use"].eq("possible_target")].copy()

    allowed_df = pd.DataFrame({"allowed_feature": allowed})
    review_df = pd.DataFrame({"review_column": review})
    excluded_df = pd.DataFrame({"excluded_column": excluded})

    allowed_path = os.path.join(decision, "system_recommended_features.csv")
    review_path = os.path.join(decision, "review_columns.csv")
    excluded_path = os.path.join(decision, "excluded_columns.csv")
    targets_path = os.path.join(decision, "system_recommended_targets.csv")

    allowed_df.to_csv(allowed_path, index=False)
    review_df.to_csv(review_path, index=False)
    excluded_df.to_csv(excluded_path, index=False)
    possible_target_df.to_csv(targets_path, index=False)

    # ---------- user preference verification ----------
    validation = []
    if user_target:
        exists = user_target in df2.columns
        if not exists:
            result = "not_found"
            evidence = "User-selected target not found in Stage2 dataset."
        else:
            row = col_intel_df[col_intel_df["column_name"].eq(user_target)].iloc[0].to_dict()
            if row["risk_type"]:
                result = "needs_review"
                evidence = "Selected target has risk flag: " + str(row["risk_type"])
            elif row["target_score"] >= 60:
                result = "supported"
                evidence = "Selected target has acceptable target score."
            else:
                result = "weak_support"
                evidence = "Selected target has low/medium target score."
        validation.append([user_goal, user_direction, user_target, result, evidence, "Ask user to reconfirm before Stage2."])
    else:
        validation.append([user_goal, user_direction, "", "not_provided", "No user-selected target.", "Ask user to select target or choose unsupervised/reporting."])

    user_ver_df = pd.DataFrame(validation, columns=["user_goal", "user_direction", "user_target", "system_validation", "evidence", "next_action"])
    user_ver_path = os.path.join(decision, "user_preference_verification.csv")
    user_ver_df.to_csv(user_ver_path, index=False)

    # ---------- preprocessing requirements ----------
    if not prep_df_src.empty:
        prep_df = prep_df_src.copy()
    else:
        prep_rows = []
        for col in allowed:
            if col in df2.columns:
                s = df2[col]
                if pd.api.types.is_numeric_dtype(s):
                    need = "impute numeric if missing; scale if needed"
                elif s.nunique(dropna=True) <= 30:
                    need = "impute categorical if missing; encode categories"
                else:
                    need = "review high cardinality; group or encode carefully"
                prep_rows.append([col, str(s.dtype), round(float(s.isna().mean()*100), 4), int(s.nunique(dropna=True)), need])
        prep_df = pd.DataFrame(prep_rows, columns=["column_name", "dtype", "missing_percentage", "unique_values", "preprocessing_need"])
    prep_path = os.path.join(decision, "preprocessing_requirements.csv")
    prep_df.to_csv(prep_path, index=False)

    # ---------- GO/NO-GO ----------
    blockers = []
    if not os.path.exists(stage2_dataset):
        blockers.append("Stage2 dataset missing.")
    if len(allowed) < 2:
        blockers.append("Too few allowed features.")
    if len(review) > 0:
        blockers.append("Some columns require review.")
    if len(possible_target_df) == 0 and any(str(d).lower() in ["classification", "regression", "prediction"] for d in top_dirs):
        blockers.append("Supervised direction needs confirmed target.")
    if user_ver_df.iloc[0]["system_validation"] in ["not_found", "needs_review", "weak_support"]:
        blockers.append("User preference needs reconfirmation.")

    if len(blockers) == 0:
        stage2_status = "GO"
    elif len(allowed) >= 2:
        stage2_status = "CONDITIONAL_GO"
    else:
        stage2_status = "NO_GO"

    decision_packet = {
        "created_on": str(datetime.now()),
        "stage2_status": stage2_status,
        "dataset_for_stage2": str(stage2_dataset),
        "best_direction": top_dirs[0] if top_dirs else "not_decided",
        "second_direction": top_dirs[1] if len(top_dirs) > 1 else "",
        "third_direction": top_dirs[2] if len(top_dirs) > 2 else "",
        "system_selected_target_candidate": final_target,
        "target_status": "requires_reconfirmation",
        "allowed_features_count": len(allowed),
        "review_columns_count": len(review),
        "excluded_columns_count": len(excluded),
        "main_blockers": blockers,
        "important_rule": "User feedback has low weight until verified against dataset evidence.",
        "next_stage": "Stage2 may use this base folder only. Reconfirm target and columns first."
    }
    decision_packet_path = os.path.join(decision, "stage2_decision_packet.json")
    save_json(decision_packet_path, decision_packet)
    pd.DataFrame([decision_packet]).to_csv(os.path.join(decision, "stage2_go_nogo.csv"), index=False)

    # ---------- guidance files ----------
    master_lines = [
        "MASTER GUIDELINE FOR DATASET UNDERSTANDING",
        "Dataset: " + str(os.path.basename(dataset_path)),
        "Rows: " + str(rows),
        "Columns: " + str(cols),
        "Numeric columns: " + str(len(numeric_cols)),
        "Categorical columns: " + str(len(cat_cols)),
        "Average missing percentage: " + str(missing_pct),
        "Duplicate rows: " + str(duplicate_rows),
        "Best directions: " + str(top_dirs),
        "Stage2 status: " + stage2_status,
        "System target candidate: " + str(final_target),
        "Allowed features: " + str(len(allowed)),
        "Review columns: " + str(len(review)),
        "Excluded columns: " + str(len(excluded)),
        "Main blockers: " + str(blockers),
        "Rule: Dataset facts and statistical evidence have higher weight than user preference.",
        "Rule: User should reconfirm target and columns before Stage2 modeling.",
        "This folder is designed to work independently of Stage0 and Stage1 folders."
    ]
    master_path = os.path.join(guide, "Master_Guideline_for_Dataset_Understanding.txt")
    with open(master_path, "w", encoding="utf-8") as f:
        f.write("\n".join(master_lines))

    readme_path = os.path.join(guide, "read_me_first.txt")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write("Start with 03_ML_Decision_Base/stage2_decision_packet.json\n")
        f.write("Then read 02_Dataset_Intelligence/column_intelligence.csv\n")
        f.write("Then load 01_Core_Dataset/dataset_for_stage_2.csv\n")

    questions = [
        "Confirm final ML direction.",
        "Confirm final target column if supervised ML is selected.",
        "Confirm whether review columns may be used.",
        "Confirm whether excluded columns must stay excluded.",
        "Confirm whether reporting/research is preferred over model training."
    ]
    questions_path = os.path.join(guide, "stage2_user_reconfirmation_questions.txt")
    with open(questions_path, "w", encoding="utf-8") as f:
        f.write("\n".join(questions))

    github_path = os.path.join(guide, "github_dataset_blueprint.txt")
    with open(github_path, "w", encoding="utf-8") as f:
        f.write("This folder contains cleaned data, dataset intelligence, ML decision base, limitations, and Stage2 guidance.\n")
        f.write("It can be used without opening Stage0 and Stage1 folders.\n")

    # ---------- folder index ----------
    file_rows = []
    for root, dirs, files in os.walk(base):
        for file in files:
            full = os.path.join(root, file)
            file_rows.append({"folder": os.path.relpath(root, base), "file_name": file, "full_path": full})
    index_df = pd.DataFrame(file_rows)
    index_path = os.path.join(base, "Base_Folder_Index.csv")
    index_df.to_csv(index_path, index=False)

    # ---------- console ----------
    print("Stage 1 Module 8 completed.")
    print("Base folder:", base)
    print("Stage2 dataset:", stage2_dataset)
    print("Stage2 status:", stage2_status)
    print("Best directions:", top_dirs)
    print("Allowed features:", len(allowed))
    print("Review columns:", len(review))
    print("Excluded columns:", len(excluded))
    print("Decision packet:", decision_packet_path)

    display(pd.DataFrame([decision_packet]))
    display(col_intel_df.head(20))
    display(user_ver_df)

    return decision_packet, col_intel_df


stage2_decision_packet, final_column_intelligence_df = run_stage1_module8_knowledge_synthesis()

Stage 1 Module 8 completed.
Base folder: d:\med_data\Base_Folder_for_ML_Research_After_Stage_0_and_1
Stage2 dataset: d:\med_data\Base_Folder_for_ML_Research_After_Stage_0_and_1\01_Core_Dataset\dataset_for_stage_2.csv
Stage2 status: CONDITIONAL_GO
Best directions: ['Classification', 'Reporting / Dashboard', 'Prediction']
Allowed features: 2
Review columns: 12
Excluded columns: 0
Decision packet: d:\med_data\Base_Folder_for_ML_Research_After_Stage_0_and_1\03_ML_Decision_Base\stage2_decision_packet.json

,created_on,stage2_status,dataset_for_stage2,best_direction,second_direction,third_direction,system_selected_target_candidate,target_status,allowed_features_count,review_columns_count,excluded_columns_count,main_blockers,important_rule,next_stage
0,2026-05-13 23:02:10.839027,CONDITIONAL_GO,d:\med_data\Base_Folder_for_ML_Research_After_...,Classification,Reporting / Dashboard,Prediction,medical_condition,requires_reconfirmation,2,12,0,[Some columns require review.],User feedback has low weight until verified ag...,Stage2 may use this base folder only. Reconfir...

,column_name,dtype,missing_percentage,unique_values,is_numeric,risk_type,stage1_use_decision,feature_score,target_score,risk_score,recommended_use,confidence,reason,requires_user_confirmation
0,name,object,0.0,49992,False,possible_pii,Use as feature,5,0,60,review_before_use,medium,non_numeric; missing_0.0%; unique_49992; risk_...,yes
1,age,int64,0.0,77,True,possible_sensitive,Use as feature,27,0,60,review_before_use,medium,numeric; missing_0.0%; unique_77; risk_possibl...,yes
2,gender,object,0.0,2,False,possible_sensitive,Use as feature,23,0,60,review_before_use,medium,non_numeric; missing_0.0%; unique_2; risk_poss...,yes
3,blood_type,object,0.0,8,False,,Use as feature,58,20,0,review_before_use,medium,non_numeric; missing_0.0%; unique_8,yes
4,medical_condition,object,0.0,6,False,,Use as target after final confirmation,58,65,0,possible_target,medium,non_numeric; missing_0.0%; unique_6; target_ca...,yes
5,date_of_admission,object,0.0,1827,False,,Use as feature,40,0,0,review_before_use,medium,non_numeric; missing_0.0%; unique_1827,yes
6,doctor,object,0.0,40341,False,,Use as feature,40,0,0,review_before_use,medium,non_numeric; missing_0.0%; unique_40341,yes
7,hospital,object,0.0,39876,False,,Use as feature,40,0,0,review_before_use,medium,non_numeric; missing_0.0%; unique_39876,yes
8,insurance_provider,object,0.0,5,False,,Use as feature,58,20,0,review_before_use,medium,non_numeric; missing_0.0%; unique_5,yes
9,billing_amount,float64,0.0,50000,True,,Use as feature,62,15,0,use_as_feature,medium,numeric; missing_0.0%; unique_50000,no
10,room_number,int64,0.0,400,True,,Use as feature,62,15,0,use_as_feature,medium,numeric; missing_0.0%; unique_400,no
11,admission_type,object,0.0,3,False,,Use as feature,58,20,0,review_before_use,medium,non_numeric; missing_0.0%; unique_3,yes
12,discharge_date,object,0.0,1856,False,,Use as feature,40,0,0,review_before_use,medium,non_numeric; missing_0.0%; unique_1856,yes
13,medication,object,0.0,5,False,,Use as feature,58,20,0,review_before_use,medium,non_numeric; missing_0.0%; unique_5,yes
14,test_results,object,0.0,3,False,possible_target_or_leakage,Review as target or feature,23,45,60,review_before_use,medium,non_numeric; missing_0.0%; unique_3; risk_poss...,yes

,user_goal,user_direction,user_target,system_validation,evidence,next_action
0,Classification,classification,medical_condition,supported,Selected target has acceptable target score.,Ask user to reconfirm before Stage2.